### ISSUE TITLE
IndexError: too many indices for array when using label-based registration with a single translation

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2528]
### Description

When using label-based registration with only dof=Tx (single translation along x), it produces an error.

### Steps to Reproduce

~~~
sct_download_data -d sct_testing_data
cd sct_testing_data/t2
sct_label_utils -i t2.nii.gz -create 30,27,25,1 -o label_src.nii
sct_label_utils -i t2.nii.gz -create 31,27,25,1 -o label_dest.nii
sct_register_multimodal -i t2.nii.gz -ilabel label_src.nii -d t2.nii.gz -dlabel label_dest.nii -param step=0,type=label,dof=Tx 

--
Spinal Cord Toolbox (git-master-8e790d825d9124cc80fd819c669e904f3c1d70b8)


Input parameters:
  Source .............. t2.nii.gz
  Destination ......... t2.nii.gz
  Init transfo ........ 
  Mask ................ 
  Output name ......... 
  Remove temp files ... 1
  Verbose ............. 1

Check if input data are 3D...

Create temporary folder (/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20191115095002.924511-npu7q8xw)...

Copying input data to tmp folder and convert to nii...

--
ESTIMATE TRANSFORMATION FOR STEP #0
Registration parameters:
  type ........... label
  algo ........... syn
  slicewise ...... 0
  metric ......... MI
  iter ........... 0
  smooth ......... 0
  laplacian ...... 0
  shrink ......... 1
  gradStep ....... 0.5
  deformation .... 1x1x0
  init ........... 
  poly ........... 5
  dof ............ Tx
  smoothWarpXY ... 2
  rot_method ... pca
Labels src: [[7.2192840576171875, -1.7866058349609375, 7.6783294677734375]]
Labels dest: [[7.2192840576171875, -0.7866058349609375, 7.6783294677734375]]
Degrees of freedom (dof): Tx
Optimization terminated successfully.
         Current function value: 1.000000
         Iterations: 1
         Function evaluations: 42
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_register_multimodal.py", line 895, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_register_multimodal.py", line 518, in main
    warp_forward_out, warp_inverse_out = register(src, dest, paramreg, param, str(i_step))
  File "/Users/julien/code/sct/scripts/sct_register_multimodal.py", line 856, in register
    verbose=param.verbose)
  File "/Users/julien/code/sct/scripts/msct_register_landmarks.py", line 87, in register_landmarks
    (rotation_matrix, translation_array, points_moving_reg, points_moving_barycenter) = getRigidTransformFromLandmarks(points_src, points_dest, constraints=dof, verbose=verbose, path_qc=path_qc)
  File "/Users/julien/code/sct/scripts/msct_register_landmarks.py", line 235, in getRigidTransformFromLandmarks
    dof[dict_dof[list_constraints[i]]] = res.x[i]
IndexError: too many indices for array
~~~

**Comment by joshuacwnewton** [comment]
I am not able to reproduce the issue using the steps provided:

<details>

```console
(master) joshua@tadpole:~/repos/spinalcordtoolbox/data$ sct_download_data -d sct_testing_data

--
Spinal Cord Toolbox (git-master-3636667fa6c01ce80d4d04f7eb63aa5a36e5cadb*)

sct_download_data -d sct_testing_data
--

Removing existing destination folder '/home/joshua/repos/spinalcordtoolbox/data/sct_testing_data'
Trying URL: https://github.com/spinalcordtoolbox/sct_testing_data/releases/download/r20210330230310/sct_testing_data-r20210330230310.zip
Downloading: sct_testing_data-r20210330230310.zip
Status: 100%|██████████████████████████████████████████████████| 7.17M/7.17M [00:00<00:00, 45.8MB/s]
Creating temporary folder (/tmp/sct_2023-01-19_00-31-35_install-data_3c9vc_ld)
Unzip data to: /tmp/sct_2023-01-19_00-31-35_install-data_3c9vc_ld
Copying data to: /home/joshua/repos/spinalcordtoolbox/data/sct_testing_data
Removing temporary folders...
Done!

(master) joshua@tadpole:~/repos/spinalcordtoolbox/data$ cd sct_testing_data/t2
(master) joshua@tadpole:~/repos/spinalcordtoolbox/data/sct_testing_data/t2$ sct_label_utils -i t2.nii.gz -create 30,27,25,1 -o label_src.nii

--
Spinal Cord Toolbox (git-master-3636667fa6c01ce80d4d04f7eb63aa5a36e5cadb*)

sct_label_utils -i t2.nii.gz -create 30,27,25,1 -o label_src.nii
--

Generating output files...

Done! To view results, type:
fsleyes t2.nii.gz label_src.nii &

(master) joshua@tadpole:~/repos/spinalcordtoolbox/data/sct_testing_data/t2$ sct_label_utils -i t2.nii.gz -create 31,27,25,1 -o label_dest.nii

--
Spinal Cord Toolbox (git-master-3636667fa6c01ce80d4d04f7eb63aa5a36e5cadb*)

sct_label_utils -i t2.nii.gz -create 31,27,25,1 -o label_dest.nii
--

Generating output files...

Done! To view results, type:
fsleyes t2.nii.gz label_dest.nii &

(master) joshua@tadpole:~/repos/spinalcordtoolbox/data/sct_testing_data/t2$ sct_register_multimodal -i t2.nii.gz -ilabel label_src.nii -d t2.nii.gz -dlabel label_dest.nii -param step=0,type=label,dof=Tx 

--
Spinal Cord Toolbox (git-master-3636667fa6c01ce80d4d04f7eb63aa5a36e5cadb*)

sct_register_multimodal -i t2.nii.gz -ilabel label_src.nii -d t2.nii.gz -dlabel label_dest.nii -param step=0,type=label,dof=Tx
--


Input parameters:
  Source .............. t2.nii.gz (60, 55, 52)
  Destination ......... t2.nii.gz (60, 55, 52)
  Init transfo ........ 
  Mask ................ 
  Output name ......... 
  Remove temp files ... 1
  Verbose ............. 1

Check if input data are 3D...
Creating temporary folder (/tmp/sct_2023-01-19_00-31-56_register-wrapper_kixbomo4)

Copying input data to tmp folder and convert to nii...

--
ESTIMATE TRANSFORMATION FOR STEP #0
Registration parameters:
  type ........... label
  algo ........... syn
  slicewise ...... 0
  metric ......... MI
  samplStrategy .. None
  samplPercent ... 0.2
  iter ........... 0
  smooth ......... 0
  laplacian ...... 0
  shrink ......... 1
  gradStep ....... 0.5
  deformation .... 1x1x0
  init ........... 
  poly ........... 5
  filter_size .... 5
  dof ............ Tx
  smoothWarpXY ... 2
  rot_method ..... pca
Parameter 'algo=syn' has no effect for 'type=label' registration.
Labels src: [[7.2192840576171875, -1.7866058349609375, 7.6783294677734375]]
Labels dest: [[7.2192840576171875, -0.7866058349609375, 7.6783294677734375]]
Degrees of freedom (dof): Tx
Optimization terminated successfully.
         Current function value: 1.000000
         Iterations: 1
         Function evaluations: 41
Matrix:
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]
Center:
 [ 7.21928406 -0.78660583  7.67832947]
Translation:
 [[-3.19598595e-11  0.00000000e+00  0.00000000e+00]]

--
ESTIMATE TRANSFORMATION FOR STEP #1

Apply transformation from previous step
/home/joshua/repos/spinalcordtoolbox/bin/isct_antsApplyTransforms -d 3 -i src.nii -o src_reg.nii -t warp_forward_0.txt -r dest_RPI.nii -n 'BSpline[3]' # in /tmp/sct_2023-01-19_00-31-56_register-wrapper_kixbomo4
Registration parameters:
  type ........... im
  algo ........... syn
  slicewise ...... 0
  metric ......... MeanSquares
  samplStrategy .. None
  samplPercent ... 0.2
  iter ........... 10
  smooth ......... 0
  laplacian ...... 0
  shrink ......... 1
  gradStep ....... 0.5
  deformation .... 1x1x0
  init ........... 
  poly ........... 5
  filter_size .... 5
  dof ............ Tx_Ty_Tz_Rx_Ry_Rz
  smoothWarpXY ... 2
  rot_method ..... pca

Estimate transformation
/home/joshua/repos/spinalcordtoolbox/bin/isct_antsRegistration --dimensionality 3 --transform 'syn[0.5,3,0]' --metric 'MeanSquares[dest_RPI_pad.nii,src_reg.nii,1,4]' --convergence 10 --shrink-factors 1 --smoothing-sigmas 0mm --restrict-deformation 1x1x0 --output '[step1,src_reg_regStep1.nii]' --interpolation 'BSpline[3]' --verbose 1 # in /tmp/sct_2023-01-19_00-31-56_register-wrapper_kixbomo4

Concatenate transformations...
/home/joshua/repos/spinalcordtoolbox/bin/isct_ComposeMultiTransform 3 warp_src2dest.nii.gz -R dest.nii warp_forward_1.nii.gz warp_forward_0.txt # in /tmp/sct_2023-01-19_00-31-56_register-wrapper_kixbomo4
/home/joshua/repos/spinalcordtoolbox/bin/isct_ComposeMultiTransform 3 warp_dest2src.nii.gz -R src.nii -i warp_forward_0.txt warp_inverse_1.nii.gz # in /tmp/sct_2023-01-19_00-31-56_register-wrapper_kixbomo4

Apply transfo source --> dest...
/home/joshua/repos/spinalcordtoolbox/bin/isct_antsApplyTransforms -d 3 -i src.nii -o src_reg.nii -t warp_src2dest.nii.gz -r dest.nii -n Linear # in /tmp/sct_2023-01-19_00-31-56_register-wrapper_kixbomo4

Apply transfo dest --> source...
/home/joshua/repos/spinalcordtoolbox/bin/isct_antsApplyTransforms -d 3 -i dest.nii -o dest_reg.nii -t warp_dest2src.nii.gz -r src.nii -n Linear # in /tmp/sct_2023-01-19_00-31-56_register-wrapper_kixbomo4

Generate output files...
File created: t2_src_reg.nii.gz
mv /tmp/sct_2023-01-19_00-31-56_register-wrapper_kixbomo4/warp_src2dest.nii.gz warp_t22t2.nii.gz
File created: warp_t22t2.nii.gz
File created: t2_dest_reg.nii.gz
File warp_t22t2.nii.gz already exists. Deleting it..
mv /tmp/sct_2023-01-19_00-31-56_register-wrapper_kixbomo4/warp_dest2src.nii.gz warp_t22t2.nii.gz
File created: warp_t22t2.nii.gz

Remove temporary files...
rm -rf /tmp/sct_2023-01-19_00-31-56_register-wrapper_kixbomo4

Finished! Elapsed time: 9s

Done! To view results, type:
fsleyes t2.nii.gz t2_dest_reg.nii.gz &


Done! To view results, type:
fsleyes t2.nii.gz t2_src_reg.nii.gz &

(master) joshua@tadpole:~/repos/spinalcordtoolbox/data/sct_testing_data/t2$ 
```
</details>

When I inspect the line that errored:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/377bfb88a9845bb8348e760aea5d70bb4f4bcb42/spinalcordtoolbox/registration/landmarks.py#L233-L234

- `i` is just `0`, so `res.x[i]` is safe
- `list_constraints[i]` is `'Tx'`, `dict_dof['Tx']` is `0`, `dof[0]` is `0`.

These are all just single indexes into lists!

But, "too many indices for array" is a [numpy-specific error](https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/core/tests/test_indexerrors.py#L116-L123). So, this error seems impossible to achieve with the current codebase, where no numpy arrays are used here. Maybe some sort of refactor changed this behavior? Not sure.

Either way, this seems safe to close to me.
