### ISSUE TITLE
Backport PAM50 url bugfix to previous versions

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3184]
Several users have asked to keep using older versions of SCT. This is valid and understandable: sticking with a single version of SCT helps ensure reproducibility across studies. 

But, there is a bug (#2588) that interrupts the installation process. It was introduced by cf1d9d06b4c58e818e934cb752e4e75ea9541e07, which was first included in v4.2.0. The fix, #2671, was only included in v4.3. So, I believe the affected releases are v4.2.0, v4.2.1, and v4.2.2.

Whether or not we can realistically support all versions, or backport all fixes, is a much larger discussion. But, in this specific case:

* The bug has a huge impact. It results in a broken installation, which is time-consuming to fix manually when helping out users on the forums. (See [this forum thread](https://forum.spinalcordmri.org/t/sct-version-4-2-2-download-problems/607)).
* The bug is very simple to fix -- just a URL swap.

Because of that, I think it would be worthwhile to backport a fix (even if our overall strategy for supporting older releases is uncertain at the moment.)

**Comment by joshuacwnewton** [comment]
I've tried to address this issue by following the steps from [this gist](https://gist.github.com/danielestevez/2044589), plus the `GIT_COMMITTER_DATE` suggestion from [this SO post](https://stackoverflow.com/questions/21738647/change-date-of-git-tag-or-github-release-based-on-it):

```bash
# Get timestamp of previous tag
git checkout 4.2.0
echo "$(git show --format=%aD | head -1)"  # Thu, 19 Dec 2019 10:59:52 -0500

# Apply and commit fix
sed -i 's,https://osf.io/u79sr/?pid=6zbyf/?action=download,https://osf.io/u79sr/download,g' scripts/sct_download_data.py
git add scripts/sct_download_data.py
git commit -m "Backport fix from #2671" -m "Fixes #3184"

# Update and push tag
git tag -d 4.2.0
GIT_COMMITTER_DATE="Thu, 19 Dec 2019 10:59:52 -0500" git tag 4.2.0
git push origin :4.2.0
git push origin 4.2.0
git fetch --tags
```

Deleting the 4.2.0 tag put the 4.2.0 release into "Draft" mode. But, since the date of the tag was preserved, it's safe to just go ahead and re-publish the draft release.

**Comment by joshuacwnewton** [comment]
Additionally, I tried installing 4.2.0 before/after this change, and got:

Before:

```
-
Spinal Cord Toolbox (4.2.0)


Trying URL: https://osf.io/u79sr/?pid=6zbyf/?action=download
Unexpected: link doesn't provide a filename

Trying URL: https://www.neuro.polymtl.ca/_media/downloads/sct/20191029_PAM50.zip
Unexpected: link doesn't provide a filename

Download error

Create temporary folder (/tmp/sct-20220908100456.255330-1kmo9mtr)...

Unzip data to: /tmp/sct-20220908100456.255330-1kmo9mtr
Traceback (most recent call last):
  File "/home/joshua/sct_4.2.0/scripts/sct_download_data.py", line 248, in <module>
    res = main()
  File "/home/joshua/sct_4.2.0/scripts/sct_download_data.py", line 140, in main
    unzip(tmp_file, dest_tmp_folder, verbose)
  File "/home/joshua/sct_4.2.0/scripts/sct_download_data.py", line 174, in unzip
    if compressed.endswith('zip'):
AttributeError: 'NoneType' object has no attribute 'endswith'

ERROR: Command failed.


Installation failed
```

After:

```
--
Spinal Cord Toolbox (4.2.0)


Trying URL: https://osf.io/u79sr/download
Downloading 20191029_PAM50.zip...
Status: 100%|##############################| 70.8M/70.8M [00:08<00:00, 8.74MB/s]

Create temporary folder (/tmp/sct-20220908103701.118949-jkrg1sgm)...

Unzip data to: /tmp/sct-20220908103701.118949-jkrg1sgm

Check if folder already exists on the destination path...

Remove temporary folders...
Done!

[...]

To use SCT, please update your environment by running:
export PATH="/home/joshua/sct_4.2.0/bin:$PATH"


Installation finished successfully!
```

**Comment by joshuacwnewton** [comment]
I'm going to repeat these steps for 4.2.1 and 4.2.2, then close this issue.

**Comment by joshuacwnewton** [comment]
I've tested `./install_sct` for 4.2.0, 4.2.1, and 4.2.2. They all work now! Closing this issue. :slightly_smiling_face:
