### ISSUE TITLE
FSLeyes can't close when SCT plugin is loaded

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3537]
When I load the SCT plugin, then try to close FSLeyes, I get the following error, which seems to prevent FSLeyes from actually closing.

```python
Traceback (most recent call last):
  File "/home/joshua/miniconda3/lib/python3.9/site-packages/fsleyes/frame.py", line 1272, in __onClose
    layout   = layouts.serialiseLayout(self)
  File "/home/joshua/miniconda3/lib/python3.9/site-packages/fsleyes/layouts.py", line 375, in serialiseLayout
    frameLayout   = patchLayoutString(auiMgr, viewPanels, True)
  File "/home/joshua/miniconda3/lib/python3.9/site-packages/fsleyes/layouts.py", line 320, in patchLayoutString
    panel        = panels[pi]
IndexError: list index out of range
```

I'm not familiar enough with FSLeyes script design/layouts to know the cause, but I'm investigating.

**Comment by joshuacwnewton** [comment]
After some research into [how FSLeyes organizes its GUI](https://open.win.ox.ac.uk/pages/fsl/fsleyes/fsleyes/apidoc/fsleyes.html#frames-views-and-controls), I believe I understand the problem. 

#### Context

1. The `FSLeyesFrame` is the top level GUI object. 
2. It is a container for one or more views, which are added using [`ViewPanels`](https://open.win.ox.ac.uk/pages/fsl/fsleyes/fsleyes/apidoc/fsleyes.views.viewpanel.html#fsleyes.views.viewpanel.ViewPanel).
3. You then use the `ViewPanel`'s `auiManager` to add child panes (i.e. text boxes, etc.).

#### Problem

The problem is, right now `sct_plugin.py` skips using a `ViewPanel` and adds the child panes directly to the _frame's_ `AuiManager`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/67221f3fce0327e3af99c1e522a1d0c26eb38ade/contrib/fsl_integration/sct_plugin.py#L35

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/67221f3fce0327e3af99c1e522a1d0c26eb38ade/contrib/fsl_integration/sct_plugin.py#L786

Because we're not using a `ViewPanel`, we're essentially missing an expected layer between FSLeyes and the SCT Plugin. This causes an error when FSLeyes tries to close...

<details>

> I traced the FSLeyes code, and the error occurs in `"fsleyes/layouts.py", line 324, in patchLayoutString`:
> 
> ```python
>         for si, s in enumerate(sections):
>             if s.find('name=') > -1:
>                 panel        = panels[pi]
>                 panelInfo    = auiMgr.GetPane(panel)
>                 panelLayout  = auiMgr.SavePaneInfo(panelInfo)
>                 pi          += 1
>                 sections[si] = panelLayout
> 
>                 if rename:
>                     sections[si] = patchPanelName(sections[si], pi)
> ```
> 
> This code essentially makes sure that there is 1 `panel` for every `section`. But, since we're not using a `ViewPanel`, there is a panel missing, and this code fails.

</details>

To fix the error, I think the most appropriate solution is to create a new `ViewPanel`, then use the panel's `auiManager`, rather than the frame's `auiManager`:

```diff
+    sct_view_panel = frame.addViewPanel(viewpanel.ViewPanel, 
+                                        title="Spinal Cord Toolbox")

-    aui_manager = frame.auiManager
+    aui_manager = sct_view_panel.auiManager
```

**Comment by joshuacwnewton** [comment]
To fix the error, I think the most appropriate solution is to create a new `ViewPanel`, then use the panel's `auiManager`, rather than the frame's `auiManager`:

```diff
+    sct_view_panel = frame.addViewPanel(viewpanel.ViewPanel, 
+                                        title="Spinal Cord Toolbox")

-    aui_manager = frame.auiManager
+    aui_manager = sct_view_panel.auiManager
```

When I do this, FSLeyes behaves as expected. And, as an added bonus, we now have the ability to close the SCT panel without having to close FSLeyes entirely.

![image](https://user-images.githubusercontent.com/16181459/136715491-b64d1fb0-b2ff-4d5e-986b-543e623c21f7.png)
