### ISSUE TITLE
`ValueError: -2 is not in list` for `sub-grenobleOfsep003_T2w.nii.gz`

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3556]
I'm currently testing the 3 vertebral labeling approaches on suitable subjects from `sct-testing-large`. (See also: New updates to [`vertebral-labeling-validation`](https://github.com/sct-pipeline/vertebral-labeling-validation))

While running `sct_label_vertebrae` on `sub-grenobleOfsep003_T2w.nii.gz`, I got the following error traceback:

<details>

```
--
Spinal Cord Toolbox (git-lr/Deep_vertebral_labeling-e623f9f040b402cc69f42a91bcf90dae56f7b292)

sct_label_vertebrae -i sub-grenobleOfsep003_T2w.nii.gz -s /data/vertebral-labeling-validation/prediction_version_deep/data_processed/data/derivatives/labels/sub-grenobleOfsep003/anat/sub-grenobleOfsep003_T2w_seg.nii.gz -c t2 -method TM -ofolder /data/vertebral-labeling-validation/prediction_version_deep/data_processed/data/derivatives/labels/sub-grenobleOfsep003/anat/TM
--

Creating temporary folder (/tmp/sct-20211031190350.226390-label_vertebrae-fcnv414g)

Copying input data to tmp folder...

Straighten spinal cord...
Creating temporary folder (/tmp/sct-20211031190350.551882-straighten_spinalcord-4fipam1o)
Copy files to tmp folder...
Fitting centerline using B-spline approximation
Error on approximation = 50.09 mm
Error on approximation = 30.38 mm
Error on approximation = 17.23 mm
Error on approximation = 7.97 mm
Error on approximation = 6.85 mm
Error on approximation = 6.23 mm
Error on approximation = 5.96 mm
Error on approximation = 5.59 mm
Error on approximation = 5.24 mm
Error on approximation = 4.72 mm
Error on approximation = 3.58 mm
Error on approximation = 3.55 mm
Error on approximation = 2.98 mm
Error on approximation = 3.12 mm
Error on approximation = 2.1 mm
Error on approximation = 1.95 mm
Error on approximation = 2.9 mm
Error on approximation = 2.92 mm
Error on approximation = 3.02 mm
Error on approximation = 1.97 mm
Error on approximation = 1.23 mm
Error on approximation = 0.72 mm
Error on approximation = 0.74 mm
Error on approximation = 0.65 mm
Error on approximation = 0.81 mm
Error on approximation = 0.74 mm
Error on approximation = 0.66 mm
Error on approximation = 0.52 mm
Error on approximation = 0.44 mm
Error on approximation = 0.43 mm
Error on approximation = 0.37 mm
Error on approximation = 0.3 mm
Error on approximation = 0.26 mm
Error on approximation = 0.28 mm
Error on approximation = 0.28 mm
Error on approximation = 0.23 mm
Error on approximation = 0.21 mm
Error on approximation = 0.19 mm
Error on approximation = 0.15 mm
Error on approximation = 0.18 mm
Error on approximation = 0.16 mm
Error on approximation = 0.13 mm
Error on approximation = 0.14 mm
Error on approximation = 0.13 mm
Error on approximation = 0.12 mm
Error on approximation = 0.11 mm
Create the straight space and the safe zone
Length of spinal cord: 326.0360211694336
Size of spinal cord in z direction: 256.6835245553295
Ratio length/size: 1.2701867863714595
Safe zone boundaries (curved space): [-428.30280687050146, -171.61928231517197]
Safe zone boundaries (straight space): [-462.9790551775535, -136.94303400811992]
Pad input volume to account for spinal cord length...
Time to generate centerline: 33.0 ms
Warping field generated: tmp.curve2straight.nii.gz
Warping field generated: tmp.straight2curve.nii.gz
Apply transformation to input image...
/home/joshua/repos/spinalcordtoolbox/bin/isct_antsApplyTransforms -d 3 -i data.nii -o tmp.anat_rigid_warp.nii.gz -t tmp.curve2straight.nii.gz -r tmp.centerline_pad_crop.nii.gz -n 'BSpline[3]' # in /tmp/sct-20211031190350.551882-straighten_spinalcord-4fipam1o
Generate output files...
File created: ./warp_curve2straight.nii.gz
File created: ./warp_straight2curve.nii.gz
cp /tmp/sct-20211031190350.551882-straighten_spinalcord-4fipam1o/tmp.anat_rigid_warp.nii.gz ./straight_ref.nii.gz
File created: ./data_straight.nii
Remove temporary files...
rm -rf /tmp/sct-20211031190350.551882-straighten_spinalcord-4fipam1o

Resample to 0.5mm isotropic...
load data...

Done! To view results, type:
fsleyes data_straightr.nii &


Apply straightening to segmentation...
/home/joshua/repos/spinalcordtoolbox/bin/isct_antsApplyTransforms -d 3 -i segmentation.nii -o segmentation_straight.nii -t warp_curve2straight.nii.gz -r data_straightr.nii -n Linear # in /tmp/sct-20211031190350.226390-label_vertebrae-fcnv414g
[33mFile /tmp/sct-20211031190350.226390-label_vertebrae-fcnv414g/segmentation_straight.nii already exists. Will overwrite it.[0m

Create label to identify disc...
Creating temporary folder...
Creating temporary folder (/tmp/sct-20211031190507.697965-2s9r3oef)
Run C2-C3 detector...
C2-C3 detected...
Remove temporary files...
rm -rf /tmp/sct-20211031190507.697965-2s9r3oef
[33mFile /tmp/sct-20211031190350.226390-label_vertebrae-fcnv414g/labelz.nii.gz already exists. Will overwrite it.[0m

And apply straightening to label...
/home/joshua/repos/spinalcordtoolbox/bin/isct_antsApplyTransforms -d 3 -i labelz.nii.gz -o labelz_straight.nii.gz -t warp_curve2straight.nii.gz -r data_straightr.nii -n NearestNeighbor # in /tmp/sct-20211031190350.226390-label_vertebrae-fcnv414g
load data...

Done! To view results, type:
fsleyes labelz_straight_r.nii.gz &


Get z and disc values from straight label...
.. [363, 0]
Look for template...
Path template: /home/joshua/repos/spinalcordtoolbox/data/PAM50
Open template and vertebral levels...
Disc values from template: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Z-values for each disc: [963, 938, 907, 870, 833, 800, 769, 735, 692, 646, 600, 551, 500, 449, 396, 342, 289, 231, 168, 104, 79]
Distances between discs (in voxel): [25.0, 31.0, 37.0, 37.0, 33.0, 31.0, 34.0, 43.0, 46.0, 46.0, 49.0, 51.0, 51.0, 53.0, 54.0, 53.0, 58.0, 63.0, 64.0, 25.0]
Detect intervertebral discs...
Current disc: -1 (z=363). Direction: superior
.. Peak found: z=-3 (correlation = 0.09684233097172887)
[33mCorrelation is too low. Using adjusted template distance.[0m
Traceback (most recent call last):
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/vertebrae/core.py", line 207, in vertebral_detection
    approx_distance_to_next_disc = list_distance[list_disc_value_template.index(current_disc - 1)]
ValueError: -2 is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 522, in <module>
    main(sys.argv[1:])
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 444, in main
    scale_dist=scale_dist)
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/vertebrae/core.py", line 209, in vertebral_detection
    logger.warning('Disc value not included in template. Using previously-calculated distance: %s', approx_distance_to_next_disc)
UnboundLocalError: local variable 'approx_distance_to_next_disc' referenced before assignment
```

</details>

(Note: I plan on investigating further, I just wanted to report this quickly before I finish working for the day.)

**Comment by joshuacwnewton** [comment]
> hum, that's fishy:
> 
> ```
> Get z and disc values from straight label...
> 
> .. [363, 0]
> ```

Good catch. This value was indeed the problem. The center of mass for this image has value 0.0, rather than 3.0! 

Looking at the image...

![center-of-mass](https://user-images.githubusercontent.com/16181459/139695723-ee3b554e-e1b2-4839-9fe5-f2bfa4e935ae.png)

Oops. It looks like the center of mass is useless, because the corresponding segmentation was warped due to a failed straightening.

Looking at the original data, then:

![original-data-1](https://user-images.githubusercontent.com/16181459/139697635-68f8bc19-3499-49ee-b0bd-bc1c760f6ee1.png)
![original-data-2](https://user-images.githubusercontent.com/16181459/139697636-de5ae0e0-6d15-40c5-b611-94f1134467b6.png)


Ah! I've never seen this before. It looks like two different halves of the subject stacked side-by-side in the same image!

@jcohenadad Do you think there may have been some mistake in the processing of this subject for `sct-testing-large`?

**Comment by joshuacwnewton** [comment]
Ah, this is how all of the `grenobleOfsep` subjects are formatted. 

Oops. I probably should have taken a closer look at the dataset before asking. :sweat_smile:

**Comment by jcohenadad** [comment]
> EDIT: Ah, this is how all of the grenobleOfsep subjects are formatted! Is this some sort of special convention for larger scans, then?

oh gosh! no, this is definitely an error in the image formatting (i don't know who did what to the raw images after their conversion from DICOM to NIfTI). OK, until this is resolved we need to ignore these images.

**Comment by joshuacwnewton** [comment]
Closing this, as this is an issue with the data (not `sct_label_vertebrae`), and https://github.com/neuropoly/data-management/issues/144 has been opened to follow-up.
