### ISSUE TITLE
QC problem ? ValueError: alpha (10) is outside 0-1 range

### ISSUE THREAD

**Issue by alexfoias** [spinalcordtoolbox/spinalcordtoolbox#3560]
Hi,

I had the following error with SCT.

I didn't have this error in the past.

```

--
Spinal Cord Toolbox (git-master-db6785e90d1046611307a616fa1bb236d9cd4f37)

sct_get_centerline -i sub-001DAH_dwi_dwi_mean.nii.gz -c dwi -qc /Users/alex/levin_results_20211102/qc -qc-subject sub-001DAH
--

Creating temporary folder (/var/folders/11/q0s99tk17rj_7jtmj1psydbr0000gn/T/sct-20211102144246.187118-xo5mjj1u)
[33mTo avoid intensity overflow due to convertion to +uint16+, intensity will be rescaled to the maximum quantization scale[0m
Remove temporary files...
rm -rf /var/folders/11/q0s99tk17rj_7jtmj1psydbr0000gn/T/sct-20211102144246.187118-xo5mjj1u

Done! To view results, type:
fsleyes sub-001DAH_dwi_dwi_mean.nii.gz -cm greyscale /Users/alex/levin_results_20211102/data_processed/sub-001DAH/dwi/sub-001DAH_dwi_dwi_mean_centerline.nii.gz -cm red -a 100.0 &


*** Generate Quality Control (QC) html report ***
Resample images to 0.6x0.6 mm
QcImage: layout with Axial slice
Compute center of mass at each slice
/Users/alex/levin_results_20211102/qc/data_processed/sub-001DAH/dwi/sct_get_centerline/2021_11_02_144246.326601/bkg_img.png
/Users/alex/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/site-packages/scipy/ndimage/measurements.py:1407: RuntimeWarning: invalid value encountered in double_scalars
  for dir in range(input.ndim)]
Traceback (most recent call last):
  File "/Users/alex/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_get_centerline.py", line 193, in <module>
    main(sys.argv[1:])
  File "/Users/alex/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_get_centerline.py", line 187, in main
    dataset=qc_dataset, subject=qc_subject, process='sct_get_centerline')
  File "/Users/alex/code/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 878, in generate_qc
    fps=fps
  File "/Users/alex/code/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 718, in add_entry
    layout(qcslice)
  File "/Users/alex/code/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 317, in wrapped_f
    self._make_QC_image_for_3d_volumes(img, mask, slice_orientation=sct_slice.get_name())
  File "/Users/alex/code/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 361, in _make_QC_image_for_3d_volumes
    action(self, mask[i], ax)
  File "/Users/alex/code/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 244, in label_centerline
    aspect=float(self.aspect_mask))
  File "/Users/alex/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/site-packages/matplotlib/__init__.py", line 1361, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/alex/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 5610, in imshow
    im.set_alpha(alpha)
  File "/Users/alex/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/site-packages/matplotlib/image.py", line 280, in set_alpha
    martist.Artist._set_alpha_for_array(self, alpha)
  File "/Users/alex/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/site-packages/matplotlib/artist.py", line 983, in _set_alpha_for_array
    Artist.set_alpha(self, alpha)
  File "/Users/alex/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/site-packages/matplotlib/artist.py", line 965, in set_alpha
    raise ValueError(f'alpha ({alpha}) is outside 0-1 range')
ValueError: alpha (10) is outside 0-1 range

```

**Comment by alexfoias** [comment]
@joshuacwnewton is there anyway I can bypass this error. Or should I use an older release ?

**Comment by joshuacwnewton** [comment]
Sorry. Thanks or the reminder ping. I haven't had a chance to look at this yet. I could prioritise this issue, but it would mean de-prioritising some other tasks. 

Right now I feel a bit unfocused/overwhelmed, and not sure what to prioritise. I plan to bring this up at the next `#sct_dev` meeting. Again, sorry about this.

**Comment by alexfoias** [comment]
sure, no problem. thank you.

**Comment by joshuacwnewton** [comment]
Oh. This is dead simple, just a usage error:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/685ab17ff9bebeb38228d52a55b2507b60b52446/spinalcordtoolbox/reports/qc.py#L243

Assuming we want an opaque centerline, this should read `alpha=1` instead.

Still, the weird thing is:

* The `alpha=10` line has been in SCT since the feature was initially added a year and a half ago in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2784.
* And, the error message has been in `matplotlib` for >4 years now: https://github.com/matplotlib/matplotlib/commit/821617b391df12660c0f60c7650eea60fbe082f1

So, all signs suggest that this issue has always been present, and should have cropped up sooner. (Oh well, probably not worth spending too much time digging into why, since the fix is so straightforward.)
