### ISSUE TITLE
IndentationError in spinalcordtoolbox/deepseg_sc/core.py

### ISSUE THREAD

**Issue by kousu** [spinalcordtoolbox/spinalcordtoolbox#3584]
### Description

`sct_deepseg_sc` is currently failing on `master`??

### Steps to Reproduce

```
git clone -b master --depth 1 https://github.com/spinalcordtoolbox/spinalcordtoolbox/
(cd spinalcordtoolbox && ./install_sct -y) && source ~/.bashrc

curl -JLO https://github.com/spinalcordtoolbox/sct_tutorial_data/archive/refs/tags/SCT-Course-20211116.zip
unzip SCT-Course-20211116.zip
cd sct_tutorial_data-SCT-Course-20211116/single_subject/data/t1

sct_deepseg_sc -i t1.nii.gz -c t1 -ofolder deepseg -qc ~/qc_singleSubj
```

**Expected behavior:**

`sct_deepseg_sc` runs

**Actual behavior:**

```
u108545@joplin:~/sct_tutorial_data-SCT-Course-20211116/single_subject/data/t1$ sct_deepseg_sc -i t1.nii.gz -c t1 -ofolder deepseg -qc ~/qc_singleSubj
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/u108545/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg_sc.py", line 21, in <module>
    from spinalcordtoolbox.deepseg_sc.core import deep_segmentation_spinalcord
  File "/home/GRAMES.POLYMTL.CA/u108545/spinalcordtoolbox/spinalcordtoolbox/deepseg_sc/core.py", line 28
    K.set_session(K.tf.Session(config=conf))
    ^
IndentationError: unexpected indent
```

**Comment by kousu** [comment]
sorry nevermind i was debugging something on this system and got spooked o____o
