### ISSUE TITLE
`-list-labels` crashes when pointing to another non-default atlas location

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3634]
### Description

When listing the labels ID using an atlas that is _not_ located at `label/atlas/`, the command crashes:

<details><summary>Terminal output</summary>

```console
julien-macbook:~ $ sct_extract_metric -list-labels -f ~/code/sct/data/PAM50/atlas/

--
Spinal Cord Toolbox (git-master-7fd2ea718751dd858840c3823c0830a910d9777c*)

sct_extract_metric -list-labels -f /Users/julien/code/sct/data/PAM50/atlas/
--


ERROR: The file label/atlas/info_label.txt does not exist. Exit program.

Traceback (most recent call last):
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_extract_metric.py", line 397, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_extract_metric.py", line 273, in main
    arguments = parser.parse_args(argv)
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.7/argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.7/argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.7/argparse.py", line 1993, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.7/argparse.py", line 1933, in consume_optional
    take_action(action, args, option_string)
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.7/argparse.py", line 1861, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_extract_metric.py", line 53, in __call__
    with open(file_label, 'r') as default_info_label:
FileNotFoundError: [Errno 2] No such file or directory: 'label/atlas/info_label.txt'
```

</details>

It crashes despite pointing to a folder that contains the `info_label.txt` files:

```console
julien-macbook:~ $ ls ~/code/sct/data/PAM50/atlas/info_label.txt 
/Users/julien/code/sct/data/PAM50/atlas/info_label.txt
```

### Solution 

Update the path to the correct atlas folder (ie: account for the flag `-f` if it is used)

**Comment by joshuacwnewton** [comment]
The reason this happens is because of the order of arguments passed:

```
sct_extract_metric -list-labels -f ~/code/sct/data/PAM50/atlas/
```

If we swap the order, then `-f` is parsed first, and `-list-labels` works as expected:

```
sct_extract_metric -f ~/code/sct/data/PAM50/atlas/ -list-labels
```

So, a quick fix would be to ensure that `-list-labels` is always the last argument parsed in the list of arguments.
