### ISSUE TITLE
`sct_run_batch` shell script usage is incompatible with native Windows installations

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3696]
> * **Note:** This issue is the cause of 3 of the 13 remaining test failures described in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3682#issuecomment-1042079185.

## Context

`sct_run_batch` operates by parallel-executing shell scripts containing SCT CLI commands:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f1766ed3f63b4d83fecb7a382b357a2427d8e6c2/spinalcordtoolbox/scripts/sct_run_batch.py#L208-L211

Naturally, shell scripts aren't executable on Windows, so we run into the following error in our test suite:

```
___________________________ test_separate_sessions ____________________________
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\users\joshua\repos\spinalcordtoolbox\spinalcordtoolbox\scripts\sct_run_batch.py", line 211, in run_single
    stderr=subprocess.STDOUT)
  File "C:\Users\Joshua\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Joshua\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Joshua\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application
```

(There are 2 other tests that fail for similar reasons.)

We could skip or rewrite these tests for Windows, of course. But, beyond the tests themselves, we would need to come up with a way to run typical batch-processing-style workflows on Windows. 

## Possible solutions

1.  Using a [bash port for Windows](https://stackoverflow.com/a/26523241) (win-bash, Git Bash, Cygwin):

    > The top Google hit is http://win-bash.sourceforge.net/ but you also need to understand that most Bash scripts expect a Unix-like environment; so just installing Bash is probably unlikely to allow you to run a script you found on the net, unless it was specifically designed for this particular usage scenario. The usual solution to that is https://www.cygwin.com/ but there are many possible alternatives, depending on what exactly it is that you want to accomplish.

2. Alternatively, our users may instead be able to write [batch scripts](https://en.wikipedia.org/wiki/Batch_file) (`.bat`, not `.sh`) to accomplish a similar purpose, but this too would need to be tested.

**Comment by joshuacwnewton** [comment]
> Using a [bash port for Windows](https://stackoverflow.com/a/26523241) (win-bash, Git Bash, Cygwin):

1. `win-bash`: Failure
2. Git Bash: Failure
3. Cygwin: Success

Will update this comment with more details as I go along.

**Comment by joshuacwnewton** [comment]
Even better: I missed the fact that "Git for Windows" has an option in its installer called "Use Git and optional Unix tools from the command line". This accomplishes the same thing as Cygwin, and lets us kill two birds with one stone, so to speak. It turns installing SCT into a 3-step process:

1. Install Python.
2. Install Git for Windows.
3. Run `install_sct.bat`, then add SCT's script directory to the PATH.
