### ISSUE TITLE
Windows-built `isct_AntsSliceReg` binary causes minor failures in registration/moco test results 

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3697]
> * **Note:** This issue is the cause of 3 of the 13 remaining test failures described in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3682#issuecomment-1042079185.

Please refer to the test failures below:

```
___________ test_register_step_ants_slice_regularized_registration ____________
Traceback (most recent call last):
  File "c:\users\joshua\repos\spinalcordtoolbox\testing\api\test_register.py", line 204, in test_register_step_ants_slice_regularized_registration
    assert txty_result == pytest.approx(txty_groundtruth, abs=1e-14)
AssertionError: assert array([[ 1.00210787, -0.14949475],\n       [ 1.04632465, -0.62104767],\n       [ 0.90514801, -0.86235449],\n       [ 0.78459634, -0.89296371],\n       [ 0.89068801, -0.73242383]]) == approx([[1.00439255454324 ± 1.0e-14, -0.151760183772956 ± 1.0e-14], [1.04645709177172 ± 1.0e-14, -0.621178997815087 ± 1.0e-14], [0.904949339396005 ± 1.0e-14, -0.862157494292993 ± 1.0e-14], [0.784728781515325 ± 1.0e-14, -0.893095039021259 ± 1.0e-14], [0.890654902228898 ± 1.0e-14, -0.732390997814474 ± 1.0e-14]])
  comparison failed. Mismatched elements: 10 / 10:
  Max absolute difference: 0.0022846851304498816
  Max relative difference: 0.015153927535905483
  Index  | Obtained           | Expected                    
  (0, 0) | 1.00210786941279   | 1.00439255454324 ± 1.0e-14  
  (0, 1) | -0.149494751147075 | -0.151760183772956 ± 1.0e-14
  (1, 0) | 1.04632464626153   | 1.04645709177172 ± 1.0e-14  
  (1, 1) | -0.621047668302359 | -0.621178997815087 ± 1.0e-14
  (2, 0) | 0.905148007733973  | 0.904949339396005 ± 1.0e-14 
  (2, 1) | -0.862354488358284 | -0.862157494292993 ± 1.0e-14
  (3, 0) | 0.78459633610691   | 0.784728781515325 ± 1.0e-14 
  (3, 1) | -0.892963709549546 | -0.893095039021259 ± 1.0e-14
  (4, 0) | 0.890688013657132  | 0.890654902228898 ± 1.0e-14 
  (4, 1) | -0.732423830110842 | -0.732390997814474 ± 1.0e-14
_______________________ test_sct_dmri_moco_check_params _______________________
Traceback (most recent call last):
  File "c:\users\joshua\repos\spinalcordtoolbox\testing\cli\test_cli_sct_dmri_moco.py", line 21, in test_sct_dmri_moco_check_params
    assert allclose(lresults, lgroundtruth)
AssertionError: assert False
 +  where False = allclose(array([ 4.75290407e-04, -1.19705417e-05, -1.19705417e-05, -1.19705417e-05,\n       -1.29661964e-01, -1.29661964e-01, -1.29661964e-01]), 
                                 [0.00047529041677414337, -1.1970542445283172e-05, -1.1970542445283172e-05, -1.1970542445283172e-05, -0.1296642741802682, -0.1296642741802682, ...])
__________________ test_sct_dmri_moco_with_mask_check_params __________________
Traceback (most recent call last):
  File "c:\users\joshua\repos\spinalcordtoolbox\testing\cli\test_cli_sct_dmri_moco.py", line 44, in test_sct_dmri_moco_with_mask_check_params
    assert allclose(lresults, lgroundtruth)
AssertionError: assert False
 +  where False = allclose(array([ 0.00802774,  0.00394261,  0.00394261,  0.00394261, -0.01531678,\n       -0.01531678, -0.01531678]), 
                                 [0.008032332623754357, 0.0037734940916436697, 0.0037734940916436697, 0.0037734940916436697, -0.01502861167728611, -0.01502861167728611, ...])
```

Notably, however, the majority of the `sct_register_to_template` and `sct_register_multimodal` tests _pass_ on Windows. 😄 

So, given that the failures themselves seem relatively minor (1e-3 to 1e-2 range), we may want to double-check what the expected behavior for these tests should actually be, then accordingly either:

* Loosen the test sensitivity. ([`np.allclose`](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) has default values `rtol=1e-05, atol=1e-08`, which may be overly sensitive.)
* Rework these tests so that they verify expected _behavior_ more generally, rather than simply matching against cached values.

**Comment by joshuacwnewton** [comment]
In our meeting on Tuesday, Julien raised the concern that the versions of ANTs/ITK/etc. used to build the Windows version might be different than the versions used to build the Linux/macOS versions. (And he was absolutely correct. 😅)

Thankfully, @kousu did an excellent job with CI-built binaries, so we know _precisely_ the commit used to build the Linux/macOS binaries based on the state of the [`matrix-build`](https://github.com/kousu/ANTs/commits/matrix-build) branch. In turns out, in fact, that my Windows ANTs build had included an additional 116 commits (!) since July 2020 that were not included in our current binaries. 

So, I'm going to try rebuilding from the same repo state and see if it helps. 

(Also, once I get the Windows build steps sorted, I would love to incorporate Windows into @kousu's ANTs-build GitHub Actions workflow, then follow up on #2815.)

**Comment by joshuacwnewton** [comment]
Good news! I rebuilt the binaries using the exact commit as was done previously, and indeed, the tests above pass as they should. 

Thank you for the suggestion during out meeting, @jcohenadad. I can now close this issue, and I'll follow up in #2815 so this doesn't happen again in the future.
