### ISSUE TITLE
Error when installing native windows SCT

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#3740]
## Description

I followed the commands in 

https://gist.github.com/joshuacwnewton/b0e7ae866a56c78d951fd88e43eefc9b

When running:

~~~
install_sct.bat jn/3682-support-native-windows-installation
~~~

I get : 

~~~
C:\Users\sabeda>install_sct.bat jn/3682-support-native-windows-installation

### Downloading SCT source code to \Users\sabeda\spinalcordtoolbox...
Cloning into 'spinalcordtoolbox'...
remote: Enumerating objects: 1070, done.
remote: Counting objects: 100% (1070/1070), done.
remote: Compressing objects: 100% (741/741), done.
remote: Total 1070 (delta 343), reused 740 (delta 314), pack-reused 0R
Receiving objects: 100% (1070/1070), 3.48 MiB | 7.97 MiB/s, done.
Resolving deltas: 100% (343/343), done.
Updating files: 100% (1040/1040), done.

### Using Python to create virtual environment...
Python n'a pas ÚtÚ trouvÚ; exÚcutez sans arguments pour installer Ó partir du Microsoft Store, ou dÚsactivez ce raccourci dans ParamÞtres > GÚrer les alias d'exÚcution d'application.
'deactivate' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
Failed with error #9009.

C:\Users\sabeda>
~~~

I tried also in my anaconda prompt and got this:

(on this session, I already have spinalcordtoolbox, so this explain why it fails, but there is a depreciation notice)

~~~

(base) PS C:\Users\sb199> .\install_sct.bat jn/3682-support-native-windows-installation

### Downloading SCT source code to \Users\sb199\spinalcordtoolbox...
fatal: destination path 'spinalcordtoolbox' already exists and is not an empty directory.
DeprecationWarning: 'deactivate' is deprecated. Use 'conda deactivate'.
Failed with error #128.
(base) PS C:\Users\sb199>
~~~

**Comment by mguaypaq** [comment]
@sandrinebedard for the first error, that Python is not found, did you follow the step to enable "Add Python 3.7 to PATH" in the Python installer? Regardless, it might be good for the install script to explicitly check for this, and output user-friendly instructions if not found.

For the second error, it looks like it failed because the first installation's Git repository is still there. In the install script, I would hesitate to automatically remove the directory, but again maybe explicitly check for this condition and output instructions to the user to either delete or rename the directory, or run the installer elsewhere.

@joshuacwnewton my own installation on Windows mostly worked, but when running `sct_check_dependencies` I had a single failure, at the `Check ANTs compatibility with OS` step. There was a dialog box saying that `isct_propseg.exe` was not 64-bit compatible, and this was the output at the command prompt:
```
Check ANTs compatibility with OS ...................[FAIL]

--
Spinal Cord Toolbox (dev)

isct_test_ants
--

Creating temporary folder (C:\Users\Mathieu\AppData\Local\Temp\sct-20220322160511.201540-test_ants-6feqaj43)

Estimate rigid transformation between paired landmarks...
'c:\users\mathieu\spinalcordtoolbox\venv_sct\Scripts\isct_antsRegistration' -d 3 -t 'syn[1,3,1]' -m 'MeanSquares[data_dest.nii.gz,data_src.nii.gz,1,3]' -f 2 -s 0 -o '[src2reg,data_src_reg.nii.gz]' -c 5 -v 1 -n NearestNeighbor # in C:\Users\Mathieu\AppData\Local\Temp\sct-20220322160511.201540-test_ants-6feqaj43

Compute DICE coefficient...
sct_dice_coefficient -i data_dest.nii.gz -d data_src_reg.nii.gz -o dice.txt # in C:\Users\Mathieu\AppData\Local\Temp\sct-20220322160511.201540-test_ants-6feqaj43
Traceback (most recent call last):
File "c:\users\mathieu\spinalcordtoolbox\spinalcordtoolbox\scripts\isct_test_ants.py", line 169, in <module>
main()
File "c:\users\mathieu\spinalcordtoolbox\spinalcordtoolbox\scripts\isct_test_ants.py", line 117, in main
"-o", "dice.txt"], verbose)
File "c:\users\mathieu\spinalcordtoolbox\spinalcordtoolbox\utils\sys.py", line 355, in run_proc
raise RuntimeError(output)
RuntimeError: Traceback (most recent call last):
File "c:\users\mathieu\spinalcordtoolbox\spinalcordtoolbox\scripts\sct_dice_coefficient.py", line 20, in <module>
from spinalcordtoolbox.math import binarize
File "c:\users\mathieu\spinalcordtoolbox\spinalcordtoolbox\math.py", line 9, in <module>
from skimage.morphology import erosion, dilation, disk, ball, square, cube
File "c:\users\mathieu\spinalcordtoolbox\venv_sct\lib\site-packages\skimage\morphology\__init__.py", line 9, in <module>
from ._skeletonize import skeletonize, medial_axis, thin, skeletonize_3d
File "c:\users\mathieu\spinalcordtoolbox\venv_sct\lib\site-packages\skimage\morphology\_skeletonize.py", line 13, in <module>
from ._skeletonize_3d_cy import _compute_thin_image
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by sandrinebedard** [comment]
> @sandrinebedard for the first error, that Python is not found, did you follow the step to enable "Add Python 3.7 to PATH" in the Python installer? Regardless, it might be good for the install script to explicitly check for this, and output user-friendly instructions if not found.

Yes I did! and python is there:

```
C:\Users\sabeda>python --version

Python 3.7.9
```

**Comment by joshuacwnewton** [comment]
Sorry for the delay in getting to this! I'll try to address all 3 errors here:

## 1. Python n'a pas été trouvé

> ```
> Python n'a pas ÚtÚ trouvÚ; exÚcutez sans arguments pour installer Ó partir du Microsoft Store, 
> ou dÚsactivez ce raccourci dans ParamÞtres > GÚrer les alias d'exÚcution d'application.
> ```

This first error is the French version of:

```
Python was not found; run without arguments to install from the Microsoft Store, 
or disable this shortcut from Settings > Manage App Execution Aliases.
```

Microsoft includes these ["App Execution Aliases"](https://superuser.com/questions/1437590/typing-python-on-windows-10-version-1903-command-prompt-opens-microsoft-stor) as a way to streamline installing Python, [starting from Version 1903](https://devblogs.microsoft.com/python/python-in-the-windows-10-may-2019-update/) and up. 

Normally, however, checking the "Add Python to PATH" option during installation should place the newly-installed Python _before_ the installer app:

```console
> where python
C:\Users\Joshua\AppData\Local\Programs\Python\Python37\python.exe <--- Newly-installed Python
C:\Users\Joshua\AppData\Local\Microsoft\WindowsApps\python.exe <--- Installer app
C:\Users\Joshua\repos\spinalcordtoolbox\venv_sct\Scripts\python.exe
```

And, given what you showed by running `python --version`, it _does_ seem like your PATH was updated correctly... 🤔 

I'm wondering if maybe what happened was:

1. A terminal window was opened first.
2. Then Python was installed.
3. Then `install_sct.bat` was run without reloading the terminal.
4. Then, later a new terminal window was opened, and `python --version` was run, correctly accessing the right `python.exe`.

Could you try deleting the folder `C:\Users\sb199\spinalcordtoolbox`, then re-running `install_sct.bat` to see if you continue to receive the same error, @sandrinebedard?

**Comment by joshuacwnewton** [comment]
## 2. fatal: destination path 'spinalcordtoolbox' already exists

>```console
>(base) PS C:\Users\sb199> .\install_sct.bat jn/3682-support-native-windows-installation
> 
> ### Downloading SCT source code to \Users\sb199\spinalcordtoolbox...
> fatal: destination path 'spinalcordtoolbox' already exists and is not an empty directory.
>```

I agree with @mguaypaq's suggestions, but I also think this is a combination of three different issues:

1. `%USERPROFILE%` is set as a fixed default installation location, meaning that `install_sct.bat` will repeatedly try to install to the same location when running the script multiple times.
2. We don't gracefully handle the `git clone` step if it's been run once before (i.e. the `spinalcordtoolbox` directory already exists).
3. The SCT virtual environment is created inside the `spinalcordtoolbox` directory containing the `git clone` files. 
    - If the 2 folders were separate, then in theory, we could delete the `git clone` folder safely without needing to worry about touching an existing `venv_sct` installation.
    - But, nesting the folders is required because certain files inside of the _cloned repo_ are needed for SCT to function (`data/`, `contrib/`, etc.). (This is why the `$SCT_DIR` location is the git repo, too.)
    - This also means that our current repo structure isn't compatible with a `pip install` just yet.
    - To me, this suggests that eventually a small reorganization will be needed to make sure that _everything_ needed by the `spinalcordtoolbox` package is available inside the package directory, without needing to rely on the repo. That way, the installation directory (`venv_sct`   can be completely separate from the original `git clone spinalcordtoolbox` directory.
    - But, this is more of a concern for #1526.

I think we can probably leave 3. for now? But, it would definitely be nice to have prompts that cover both 1. and 2. in a graceful way.

One other thing we could consider is removing the `spinalcordtoolbox` directory when an error is encountered? That way, we leave the user's home directory in a clean state if the installation failed somehow.

**Comment by joshuacwnewton** [comment]
## 3. ImportError: DLL load failed: The specified module could not be found.

https://github.com/scikit-image/scikit-image/issues/4780#issuecomment-644214783 suggests:

> Very likely the C++ runtime library is missing. As a workaround, try to install the [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads), or import matplotlib before skimage, or `python -m pip install msvc-runtime`.

Given that last suggestion, my gut reaction was to try adding this to our `requirements.txt`:

```
"msvc-runtime; sys.platform == 'win32'",
```

Notably, the skimage folks thought this too, see: https://github.com/scikit-image/scikit-image/issues/4780#issuecomment-644819671, but there were issues leading the skimage folks to waffle on adopting it as an upstream fix (https://github.com/scikit-image/scikit-image/issues/4780#issuecomment-644953362,, https://github.com/scikit-image/scikit-image/issues/4780#issuecomment-824678872). Still, I'm curious if it might work as a downstream solution on our end.

Could you try the following steps, @mguaypaq?

1. msvc-runtime
   - Type `activate` to activate the SCT venv.
        - Aside: I'm wondering if we should be a little more careful about adding `venv_sct/Scripts` to the PATH. 🤔 
    - Run  `pip install msvc-runtime`
    - Retry `sct_check_dependencies`. 
    - If this doesn't solve your issue, can you try:
2. Microsoft Visual C++ Redistributable
    - Try checking to see if you have currently have "Microsoft Visual C++ Redistributable for Visual Studio" installed? (2015, 2017 or 2019 should all work.) 
    - If you don't, could you try installing the Visual C++ Redistributable from [this link](https://aka.ms/vs/17/release/vc_redist.x64.exe)?

**Comment by joshuacwnewton** [comment]
One quick update: Since #3719 has been merged, there should now be no need to use the `jn/3682-support-native-windows-installation` branch.

You can instead run `install_sct.bat master` to install SCT on Windows. (I'll update the WIP instructions accordingly.)

**Comment by sandrinebedard** [comment]
> Could you try deleting the folder C:\Users\sb199\spinalcordtoolbox, then re-running install_sct.bat to see if you continue to receive the same error, @sandrinebedard?

yes, the installation worked!
I've  downloaded it in another user session to not compromise my current version of SCT, however, I cannot change the variable PATH for that session.. so I cannot really test it out, this is not ideal since many users may not have admin access.

**Comment by joshuacwnewton** [comment]
> however, I cannot change the variable PATH for that session.. so I cannot really test it out, this is not ideal since many users may not have admin access.

Ah! Thank you very much for catching this, @sandrinebedard. My instructions for updating the `PATH` were wrong. 

Instead of searching for "**Edit the system environment variables**" (which requires admin access), you should search for "**Edit environment variables for your account**" (which any user can do), then continue as usual.

I'll be sure to update the instructions ASAP in another PR.

**Comment by mguaypaq** [comment]
Sorry for the late reply. I just tried running `sct_check_dependencies` again, both before and after pip installing `msvc-runtime` in the virtual environment, and that seems to have fixed the problem. Well, it's OK in the sense that the script outputs a bunch of green `OK`s, but there's still a popup error message about `isct_propseg.exe` not being a 64-bit executable. I'm thinking either:

* it's not actually a problem, hence the green `OK` from `sct_check_dependencies`, in which case the error message will definitely be confusing to users; or
* it's an actual problem, and `sct_check_dependencies` is wrong about the `OK`.

And for the record, I do have "Microsoft Visual C++ Redistributable" installed (the 2012 and 2017 versions, both for 32-bit and for 64-bit architectures). I probably didn't have them when I first tried the SCT install, but needed them for something else since then. I can try uninstalling them the next time you want me to try the SCT install instructions, and report on any error messages.

**Comment by joshuacwnewton** [comment]
> Well, it's OK in the sense that the script outputs a bunch of green `OK`s, but there's still a popup error message about `isct_propseg.exe` not being a 64-bit executable. I'm thinking either:

Ah! I missed the fact that it was a dialog box -- I must have skimmed your original post. My apologies.

I just tried re-running `sct_check_dependencies` and I was able to reproduce:

![cmd_p4hd6nVBSH](https://user-images.githubusercontent.com/16181459/161760285-fdaf3d92-289e-4e72-babd-7b2dd60155d2.png)

> * it's not actually a problem, hence the green `OK` from `sct_check_dependencies`, in which case the error message will definitely be confusing to users; or

Definitely this case! `isct_propseg` shouldn't even be touched, so there shouldn't be any warnings here. 🤔 

When I check the terminal output (with the dialog box still open, I see that the script is paused on this step:

```
Check PropSeg compatibility with OS ................
```

🤦 Oh. Of course. I thought I had disabled this check on Windows machines? But, it looks like I hadn't:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/ca31bad6ce6a0c90e86664b5c9ca2b3f71951509/spinalcordtoolbox/scripts/sct_check_dependencies.py#L315-L317

So, this is definitely separate from the `isct_test_ants` error reported earlier.
