### ISSUE TITLE
Intermittent `AssertionError: assert 'sub-01' in ''` test failures for `sct_run_batch` on WSL CI runs

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3784]
* Failure started yesterday
    * Has occurred across the past 2 scheduled CI runs (2022-04-28, 2022-04-29)
    * NB: The 04-28 run failed in the same way for WSL Ubuntu 2018 and 2020, but the 04-29 run failed for only WSL Ubuntu 2018?
* Installed packages are identical between those runs and the 2022-04-27 passing run (https://www.diffchecker.com/36LFqdnE)
* Commit is different, though (Passing: e6f90f9d18c24e682f20d0491a1db1a3ea8311b7, Failing: 0bfc2da2eb4c2b93fa70b3b2f24d589b1932489c)
    * But, the newer commits don't touch `sct_run_batch` at all.
* There's also a difference between the GitHub Actions number? "GitHub Actions 14 (hosted)" vs "GitHub Actions 12"

Tracebacks:

```python
=================================== FAILURES ===================================
_______________________________ test_no_sessions _______________________________
Traceback (most recent call last):
  File "/root/spinalcordtoolbox/testing/cli/test_sct_run_batch.py", line 127, in test_no_sessions
    assert f'sub-{sub}' in open(file_log, "r").read()
AssertionError: assert 'sub-01' in ''
 +  where '' = <built-in method read of _io.TextIOWrapper object at 0x7f6c6e382e50>()
 +    where <built-in method read of _io.TextIOWrapper object at 0x7f6c6e382e50> = <_io.TextIOWrapper name='/tmp/pytest-of-root/pytest-0/test_no_sessions0/out/log/err.dummy_script_sub-01.log' mode='r' encoding='UTF-8'>.read
 +      where <_io.TextIOWrapper name='/tmp/pytest-of-root/pytest-0/test_no_sessions0/out/log/err.dummy_script_sub-01.log' mode='r' encoding='UTF-8'> = open('/tmp/pytest-of-root/pytest-0/test_no_sessions0/out/log/err.dummy_script_sub-01.log', 'r')
____________________________ test_separate_sessions ____________________________
Traceback (most recent call last):
  File "/root/spinalcordtoolbox/testing/cli/test_sct_run_batch.py", line 144, in test_separate_sessions
    assert os.path.join(f'sub-{sub}', f'ses-{ses}') in open(file_log, "r").read()
AssertionError: assert 'sub-01/ses-01' in ''
 +  where 'sub-01/ses-01' = <function join at 0x7f6d69bb6ef0>('sub-01', 'ses-01')
 +    where <function join at 0x7f6d69bb6ef0> = <module 'posixpath' from '/root/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/posixpath.py'>.join
 +      where <module 'posixpath' from '/root/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/posixpath.py'> = os.path
 +  and   '' = <built-in method read of _io.TextIOWrapper object at 0x7f6c6e382f30>()
 +    where <built-in method read of _io.TextIOWrapper object at 0x7f6c6e382f30> = <_io.TextIOWrapper name='/tmp/pytest-of-root/pytest-0/test_separate_sessions0/out/log/err.dummy_script_sub-01_ses-01.log' mode='r' encoding='UTF-8'>.read
 +      where <_io.TextIOWrapper name='/tmp/pytest-of-root/pytest-0/test_separate_sessions0/out/log/err.dummy_script_sub-01_ses-01.log' mode='r' encoding='UTF-8'> = open('/tmp/pytest-of-root/pytest-0/test_separate_sessions0/out/log/err.dummy_script_sub-01_ses-01.log', 'r')
```

I don't think _this_ should affect our 5.6 release? But, I still wanted to opening this issue for documentation purposes. (I've restarted the CI run and will check in later.)

**Comment by joshuacwnewton** [comment]
Restarting the run made the issue disappear, so perhaps this was a fluke.

**Comment by joshuacwnewton** [comment]
I'm re-opening because it looks like this happened again in https://github.com/spinalcordtoolbox/spinalcordtoolbox/runs/6257402272?check_suite_focus=true.

**Comment by joshuacwnewton** [comment]
I dug into this for quite some time, but was unable to ever identify the root cause. 

It's been >11 days since my investigation, with recurring cron jobs running daily. It used to trigger semi-daily, but as of >7 days ago, it hasn't triggered once.

So, I'm going to hazard a guess that this had to do with some sort of upstream dependency issue that has now been fixed. Once again, I'm going to close this until it appears again.
