### ISSUE TITLE
ModuleNotFoundError for `msvc_runtime` when running `sct_check_dependencies`

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3794]
Forum thread: https://forum.spinalcordmri.org/t/windows-os-specific-sct-installation/878?u=joshuacwnewton

Full traceback:

```python
Check if msvc-runtime is installed..................[FAIL]
An error occured while importing module msvc-runtime -> No module named 'msvc_runtime'
Full traceback: Traceback (most recent call last):
  File "c:\users\chauc\spinalcordtoolbox\spinalcordtoolbox\scripts\sct_check_dependencies.py", line 271, in main
    module = module_import(module_name, suppress_stderr)
  File "c:\users\chauc\spinalcordtoolbox\spinalcordtoolbox\scripts\sct_check_dependencies.py", line 103, in module_import
    module = importlib.import_module(module_name)
  File "C:\Users\chauc\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'msvc_runtime'
```

I can reproduce this issue with my own local installation of SCT on my Windows development machine.

My initial hunch is that this is an issue with `sct_check_dependencies`, and not an actual installation issue. (In other words, the underlying installation is okay.) I think this might be specifically due to a mismatch between the names `msvc_runtime` and `msvc-runtime`.

**Comment by joshuacwnewton** [comment]
Ah! The issue here is in our release procedure.

As per `requirements.txt`, `msvc_runtime` only gets installed on `win32` platforms:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/20d2f599c6bccffbcc0a852ad6acd3b71d509457/requirements.txt#L13

But, when we generate our `requirements-freeze.txt` file, we use a UNIX-based GitHub actions runner:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/20d2f599c6bccffbcc0a852ad6acd3b71d509457/.github/workflows/create-release.yml#L33

So, the line pertaining to `msvc_runtime` doesn't get copied over to the `requirements-freeze.txt` file.

This is similar to what would usually happen for our `pytorch` lines:

That's why we manually copy over any torch-specific lines:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/20d2f599c6bccffbcc0a852ad6acd3b71d509457/.github/workflows/create-release.yml#L61

But what we should _actually_ be doing is copying over any lines in `requirements.txt` that contain `sys.platform`. That way, it would act as a catch-all for both the `torch` lines _and_ the `msvc-runtime` lines.
