### ISSUE TITLE
`ValueError: Don't know what metric to use! Got unsupported: mi` when calling `sct_maths -mi`

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3844]
Reported by @naga-karthik on the #sct_dev Slack channel:

> Hello! I am trying to compute the mutual information b/w 2 images using sct_maths and I used this command based on the docs [here](https://spinalcordtoolbox.com/user_section/command-line.html#sct-maths):
> 
> ```
> sct_maths -i sub-026/ses-02/anat/sub-026_ses-02_FLAIR.nii.gz -mi sub-026/ses-01/anat/sub-026_ses-01_FLAIR.nii.gz -o sub-026/ses-02/anat/sub-026_ses-02_FLAIR_mi.nii.gz
> ```
> 
> However, it throws an error saying that “mi” is unsupported. Here’s the full error trace:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/nagakarthik/sct_5.5/spinalcordtoolbox/scripts/sct_maths.py", line 509, in <module>
>     main(sys.argv[1:])
>   File "/Users/nagakarthik/sct_5.5/spinalcordtoolbox/scripts/sct_maths.py", line 382, in main
>     compute_similarity(im, im_2, fname_out, metric='mi', metric_full='Mutual information', verbose=verbose)
>   File "/Users/nagakarthik/sct_5.5/spinalcordtoolbox/scripts/sct_maths.py", line 486, in compute_similarity
>     res, data1_1d, data2_1d = sct_math.compute_similarity(img1.data, img2.data, metric=metric)
>   File "/Users/nagakarthik/sct_5.5/spinalcordtoolbox/math.py", line 222, in compute_similarity
>     raise ValueError(f"Don't know what metric to use! Got unsupported: {metric}")
> ValueError: Don't know what metric to use! Got unsupported: mi
> ```
> 
> I don’t understand the issue because the docs say that we have to use both -i and -mi. Am I missing something here?

I'll investigate shortly. :)

**Comment by joshuacwnewton** [comment]
The bug here is very simple:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/75494b70486968a4d04b289509465e0f541e321e/spinalcordtoolbox/math.py#L212-L220

The 2nd and 3rd `if:` statements need to be `elifs`. As it stands, the `else:` case will always be triggered unless `metric="corr"`.
