### ISSUE TITLE
`isct_stitching` binary throws `version 'GLIBC_2.27' not found` on both Debian 9 and CentOS 7

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3937]
In #3865, we added a new feature to `sct_image` called `-stitch`, which is based off of built C++ binaries of the [`stitching`](https://github.com/biomedia-mira/stitching) package.

The binary  is built using the [`build_biomedia_stitching`](https://github.com/spinalcordtoolbox/build_biomedia_stitching) repository, which used GitHub's available CI runners at the time, the oldest of which was `ubuntu-2018`.

The binary built using `ubuntu-2018` worked on the small subset of OSs that we test in our PR suite. However, now that the PR has been merged to master, both [Debian 9 and CentOS 7](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/3421400664/jobs/5697497135) runners are failing with the errors:

<details>
<summary> Debian 9 </summary>

```
 Traceback (most recent call last):
  File "/__w/spinalcordtoolbox/spinalcordtoolbox/testing/cli/test_cli_sct_image.py", line 103, in test_sct_image_stitch
    sct_image.main(argv=['-i', fname_roi1, fname_roi2, '-o', fname_out, '-stitch', '-qc', str(tmp_path)])
  File "/__w/spinalcordtoolbox/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_image.py", line 344, in main
    im_out = [stitch_images(im_in_list)]
  File "/__w/spinalcordtoolbox/spinalcordtoolbox/spinalcordtoolbox/image.py", line 1752, in stitch_images
    status, output = run_proc(cmd, verbose=verbose, is_sct_binary=True)
  File "/__w/spinalcordtoolbox/spinalcordtoolbox/spinalcordtoolbox/utils/sys.py", line 411, in run_proc
    raise RuntimeError(output)
RuntimeError: /__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching)
/__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching)
```
</details>

<details>
<summary> CentOS 7 </summary>

```
Traceback (most recent call last):
  File "/__w/spinalcordtoolbox/spinalcordtoolbox/testing/cli/test_cli_sct_image.py", line 103, in test_sct_image_stitch
    sct_image.main(argv=['-i', fname_roi1, fname_roi2, '-o', fname_out, '-stitch', '-qc', str(tmp_path)])
  File "/__w/spinalcordtoolbox/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_image.py", line 344, in main
    im_out = [stitch_images(im_in_list)]
  File "/__w/spinalcordtoolbox/spinalcordtoolbox/spinalcordtoolbox/image.py", line 1752, in stitch_images
    status, output = run_proc(cmd, verbose=verbose, is_sct_binary=True)
  File "/__w/spinalcordtoolbox/spinalcordtoolbox/spinalcordtoolbox/utils/sys.py", line 411, in run_proc
    raise RuntimeError(output)
RuntimeError: /__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching)
/__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching)
/__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching)
/__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching)
/__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching: /lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching)
/__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching)
/__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /__w/spinalcordtoolbox/spinalcordtoolbox/bin/isct_stitching)
```
</details>

We should possibly consider rebuilding the `stitching` binaries for an even older version of Linux (with a lesser `GLIBC` requirement), using e.g. docker containers (rather than relying on GitHub's built-in runners, which are too new).

**Comment by joshuacwnewton** [comment]
I have a working fix in https://github.com/spinalcordtoolbox/build_biomedia_stitching/pull/1, tested via https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/3430587612. 

I'll merge things shortly and open a PR in this repo.
