### ISSUE TITLE
Can not use "~" in config file for path_output arg in `sct_run_batch`

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#3957]
### Description

When using the config file in `sct_run_batch`, with the parameter `path_output`, using "~" in the desired path results in : *No such file or directory*, even if the path should be created if it doesn't exist. It works when using it for `path_data`. If we specify the entire path for `path_output`, we don't have this error.

### Steps to Reproduce

With the following config file:

```python
(base) sebeda@joplin:~/dcm_metric_normalization$ cat etc/config_process_data_bug.json
{
  "path_data"   : "~/data_nvme_sebeda/data-multi-subject",
  "path_output" : "~/data_nvme_sebeda/dcm/preprocess_sg_20221122",
  "script"      : "./bin/process_data.sh",
  "jobs"        : 1
}
```

We get that the output path doesn't exist, which is right, but is should just be created instead.

```python
(base) sebeda@joplin:~/dcm_metric_normalization$ sct_run_batch -c etc/config_process_data_bug.json

--
Spinal Cord Toolbox (git-master-c57b43f715cb85dad87a33623c7caf0ed47543ca)

sct_run_batch -c etc/config_process_data_bug.json
--

configuring
INFO SYSTEM
-----------
OS: linux (Linux-5.15.0-53-generic-x86_64-with-debian-bookworm-sid)
CPU cores: Available: 128 | Threads used by ITK Programs: 1
RAM: Total 257591 MB | Available 204485 MB | Used 36371 MB

INPUT ARGUMENTS
---------------
batch_log: sct_run_batch_log.txt
config: etc/config_process_data_bug.json
continue_on_error: 1
email_from: null
email_host: smtp.gmail.com:587
email_to: null
exclude: null
exclude_list: null
ignore_ses: false
include: null
include_list: null
itk_threads: 1
jobs: 1
path_data: ~/data_nvme_sebeda/data-multi-subject
path_output: ~/data_nvme_sebeda/dcm/preprocess_sg_20221122
path_segmanual: .
script: ./bin/process_data.sh
script_args: ''
subject_prefix: sub-
v: 1
zip: false

SCRIPT
------
git commit: 90ee556288943e029c48a49b23d0604f900d3623*
git origin: https://github.com/sct-pipeline/dcm_metric_normalization.git
Copying script to output folder...
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/sebeda/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_run_batch.py", line 598, in <module>
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/sebeda/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_run_batch.py", line 482, in main
    script_copy = os.path.abspath(shutil.copy(script, arguments.path_output))
  File "/home/GRAMES.POLYMTL.CA/sebeda/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/GRAMES.POLYMTL.CA/sebeda/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '~/data_nvme_sebeda/dcm/preprocess_sg_20221122'
```

**Comment by mguaypaq** [comment]
That's strange, because the following lines look like they handle "~" (by calling `os.path.expanduser`) and create any missing directories already:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c57b43f715cb85dad87a33623c7caf0ed47543ca/spinalcordtoolbox/scripts/sct_run_batch.py#L407-L418

Ah! But the problem is that the following line uses the raw value of `arguments.path_output`, rather than the expanded value of `path_output`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c57b43f715cb85dad87a33623c7caf0ed47543ca/spinalcordtoolbox/scripts/sct_run_batch.py#L482

This should be an easy fix.
