### ISSUE TITLE
Consider automatically copying the qform to sform, rather than throwing errors about mismatches

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3992]
> ### Description
>
> For some subjects from the `INSPIRED` dataset, I'm getting the error that `sform does not match qform`, when running `sct_label_vertebrae`:
> 
> ```console
> $ sct_label_vertebrae -i sub-zurichDCM022_acq-cspineAxial_T2w.nii.gz -s sub-zurichDCM022_acq-cspineAxial_T2w_label-SC_mask.nii.gz -c t2
> 
> --
> Spinal Cord Toolbox (git-master-a15070f635264ad05aae41db83ce31160600e930*)
> 
> sct_label_vertebrae -i sub-zurichDCM022_acq-cspineAxial_T2w.nii.gz -s sub-zurichDCM022_acq-cspineAxial_T2w_label-SC_mask.nii.gz -c t2
> --
> 
> Creating temporary folder (/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20230110141935.504038-label_vertebrae-84xzd5nn)
> 
> Copying input data to tmp folder...
> 
> Straighten spinal cord...
> Creating temporary folder (/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20230110141935.609335-straighten_spinalcord-qv13i4nd)
> Copy files to tmp folder...
> Image /private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20230110141935.504038-label_vertebrae-84xzd5nn/data.nii has different qform and sform matrices. This can produce incorrect results. Please use 'sct_image -i /private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20230110141935.504038-label_vertebrae-84xzd5nn/data.nii -header' to check that both affine matrices are valid. Then, consider running either 'sct_image -set-sform-to-qform' or 'sct_image -set-qform-to-sform' to fix any discrepancies you may find.
> Traceback (most recent call last):
>   File "/usr/local/lib/sct_latest/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 498, in <module>
>     main(sys.argv[1:])
>   File "/usr/local/lib/sct_latest/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 328, in main
>     sct_straighten_spinalcord.main(argv=[
>   File "/usr/local/lib/sct_latest/spinalcordtoolbox/scripts/sct_straighten_spinalcord.py", line 263, in main
>     fname_straight = sc_straight.straighten()
>   File "/usr/local/lib/sct_latest/spinalcordtoolbox/straightening.py", line 106, in straighten
>     Image(fname_anat, check_sform=True).save(os.path.join(path_tmp, "data.nii"))
>   File "/usr/local/lib/sct_latest/spinalcordtoolbox/image.py", line 325, in __init__
>     raise ValueError("Image sform does not match qform")
> ValueError: Image sform does not match qform   
> ```
>
> ### Steps to Reproduce
> 
> 1. Download the attached data
> 2. Run:
> ```console
> sct_label_vertebrae -i sub-zurichDCM022_acq-cspineAxial_T2w.nii.gz -s sub-zurichDCM022_acq-cspineAxial_T2w_label-SC_mask.nii.gz -c t2 
> ```
> 
> [sub-zurichDCM022.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/10386110/sub-zurichDCM022.zip)

_Originally posted by @valosekj  in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3991#issue-1527887273_

> @valosekj thank you for reporting this (these) issue.
> - labeling crashing if qform/sform are not the same --> also an SCT issue. We could potentially provide a fix to it by adding a "copy qform to sform" before doing the labeling. I _think_ we already do that for our segmentation functions

_Originally posted by @jcohenadad in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3991#issuecomment-1378765661_

**Comment by valosekj** [comment]
The same sform and qform mismatch also occurred in `sub-10` and `sub-16` from the `dcm-zurich-lesions` dataset.

I used the following fix:

```
sct_image -i sub-10_acq-ax_T2w.nii.gz -set-qform-to-sform
sct_image -i sub-16_acq-ax_T2w.nii.gz -set-qform-to-sform
```

**Comment by joshuacwnewton** [comment]
Some reflections on the current behavior:

- I believe we originally chose this error as a way of being explicit and giving users agency. If an error occurs, then they would have to explicitly choose to "opt-in" and modify their own files in order to resolve any discrepancies. (In contrast, if we were to automatically take care of mismatches, then it becomes much more "implicit". The user might blindly produce incorrect results due to the wrong xform being prioritized.)
- However, I agree that having to manually edit each and every file is really annoying when processing large batches of subjects during research. So, it would be helpful to have a way to bypass the error for people who know what they are doing. 
- That said, there are lots of different ways to resolve xform mismatches (see https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3283), and there are lots of subtle consequences that could come about by imposing new global behavior, so I feel cautious. I think this area requires a lot of thought and care.

As a "middle ground", though, we could provide some sort of internal way to bypass the error. That way, we could let internal SCT folks more easily do their research, without necessarily having to make a big decision on behalf of our users right away. For example:

- Check for the environment variables `$SCT_PRIORITIZE_QFORM` and/or `$SCT_PRIORITIZE_SFORM`. If one of these variables is set, then we would automatically copy the qform/sform and log the action, rather than throwing an error.
- Alternatively, we could store this config in some sort of file in the project repo (though this is potentially more dangerous as it would be easy to "set and forget" it, and it may also interfere with git development).
