### ISSUE TITLE
Updated version of `setuptools` rejects the `version.txt` ("dev") from `master`

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3998]
The following error is currently affecting open PRs:

```
Installing spinalcordtoolbox...

Obtaining file:///home/runner/work/spinalcordtoolbox/spinalcordtoolbox
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      running egg_info
      /home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/setuptools/dist.py:543: UserWarning: The version specified ('dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/setup.py", line 16, in <module>
          setup(
        File "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 219, in finalize_options
          parsed_version = parse_version(self.egg_version)
        File "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: 'dev'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Failed running pip install: 1


Installation failed!

Please find the file "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/install_sct_log.txt",
then upload it as a .txt attachment in a new topic on SCT's forum:
--> http://forum.spinalcordmri.org/c/sct

Error: Process completed with exit code 1.
```

Our `version.txt` on master is the following:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1b5c49c3904dffe63546adbadc47759a53fbc8ca/spinalcordtoolbox/version.txt#L1

Investigation to come -- just quickly opening up an issue.

**Comment by joshuacwnewton** [comment]
Comparing scheduled runs on master:

* 2023-01-15 (Pass): https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/3923114567 
    * (`setuptools-65.7.0-py3-none-any.whl`)
* 2023-01-16 (Fail): https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/3929760767 
    * (`setuptools-66.0.0-py3-none-any.whl`)

See: https://github.com/pypa/setuptools/issues/3772#issuecomment-1384342813

> This issue is by design (https://github.com/pypa/setuptools/issues/2497). Non-conformant versions have been discouraged since ~2014, deprecated in packaging since late 2020 and deprecated in Setuptools since Oct 2021.

**Comment by joshuacwnewton** [comment]
[`PEP 440`](https://peps.python.org/pep-0440/) specifies the following versioning scheme:

> Public version identifiers are separated into up to five segments:
> 
> * Epoch segment: `N!`
> * Release segment: `N(.N)*`
> * Pre-release segment: `{a|b|rc}N`
> * Post-release segment: `.postN`
> *  Development release segment: `.devN`

`master` isn't exactly a "[development release](https://peps.python.org/pep-0440/#developmental-releases)", but I think using `.dev` would be preferable to a dummy value such as `0.0`. 

So, it looks like might we want something like `5.8.dev0` or `6.0.dev0` for our development branch.

**Comment by joshuacwnewton** [comment]
> So, it looks like might we want something like `5.8.dev0` or `6.0.dev0` for our development branch.

If we adopt this scheme, we would probably also want to adapt one of our release-centric workflow files (e.g. `create-release.yml`) to increment `version.txt` on release.

In other words, when we release `6.0`, we would want `version.txt` to become `6.1.dev0` in anticipation of the next release.

**Comment by mguaypaq** [comment]
> If we adopt this scheme, we would probably also want to adapt one of our release-centric workflow files (e.g. `create-release.yml`) to increment `version.txt` on release.

I guess we'll need to make sure that the next version number is decided, and maybe already open as a GitHub milestone? Or maybe just passed as another parameter to the workflow.

**Comment by mguaypaq** [comment]
Re-opening for the follow-up work on our release workflow.

**Comment by abravalheri** [comment]
> If we adopt this scheme, we would probably also want to adapt one of our release-centric workflow files (e.g. `create-release.yml`) to increment `version.txt` on release.
> 
> In other words, when we release `6.0`, we would want `version.txt` to become `6.1.dev0` in anticipation of the next release.

Have you considered using [`setuptools-scm`](https://github.com/pypa/setuptools_scm)?
It uses the git tags to dynamically determine the package version.
It is also capable of automatically generating `version.txt` and has a few handy options like `guess-next-dev`, `no-guess-dev`, etc...

**Comment by joshuacwnewton** [comment]
Ah! @kousu has experimented with `setuptols-scm` in the context of #2669, but I hadn't made the connection that it could be used here as well.

Thank you for the suggestion, @abravalheri! :heart:

**Comment by joshuacwnewton** [comment]
I've tried out `setuptools_scm`, but I think it's a little more complex than what we need right now:

```console
master|joshua@tadpole:~/repos/spinalcordtoolbox$ python -m setuptools_scm
0.1.dev8276+g9f4d05a
master|joshua@tadpole:~/repos/spinalcordtoolbox$ git checkout 5.8
HEAD is now at c0e7c07c Update version.txt for 5.8
HEAD-detached-at-5.8|joshua@tadpole:~/repos/spinalcordtoolbox$ python -m setuptools_scm
5.8
HEAD-detached-at-5.8|joshua@tadpole:~/repos/spinalcordtoolbox$ git commit --allow-empty -m "Test 1"
[detached HEAD c05c51d6] Test 1
HEAD-detached-from-5.8|joshua@tadpole:~/repos/spinalcordtoolbox$ python -m setuptools_scm
5.9.dev1+gc05c51d6
HEAD-detached-from-5.8|joshua@tadpole:~/repos/spinalcordtoolbox$ git commit --allow-empty -m "Test 2"
[detached HEAD cbbb639d] Test 2
HEAD-detached-from-5.8|joshua@tadpole:~/repos/spinalcordtoolbox$ python -m setuptools_scm
5.9.dev2+gcbbb639d
```

* Our stable release versions (e.g. `5.8`) branch off from the `master` branch, so `setuptools_scm` can't detect the previous tag when on `master` (and thus defaults to `0.1`).
* Additionally, even if we managed to get it to recognize the last tag, it treats `.dev` as `n_commits_since_last_tag`, which isn't really what we're going for? We just want a placeholder value for the entire release cycle.
* The addition of `+g` to identify the git commit is quite nifty, though.

Since our usecase is much simpler, without the need for [granular representations of `distance`](https://github.com/pypa/setuptools_scm#default-versioning-scheme), I think it might just be best to manually construct the simple placeholder `<next_ver>.dev0` version tag for now?

(But, if we were to ever adopt a more complex versioning scheme, `setuptools_scm` seems like a fully-featured tool for this.)

**Comment by kousu** [comment]
`setuptools_scm` is really meant to force you into releasing from tags on `master`, as a best practice. In your demo, you're missing running `git tag ...` at some point. We would have to tweak our release process to either release off `master`, or make tags on `release`. The point is that if you play nice with it will simplify your life.

**Comment by joshuacwnewton** [comment]
I can create a new issue that details what is necessary to adopt `setuptools_scm`.

(The reason I didn't want to open the can of worms for `setuptools_scm` in the short term is because the scope of this particular issue is very small -- it only really concerns a dummy placeholder `version.txt` value that we've used on master without much issue for years. I didn't want to overhaul everything just to fix a small issue.)

**Comment by benjamindeleener** [comment]
This issue seems to cause an installation failure on recent versions of macOS, as documented in #4035. Maybe it changes the scope of this issue?

**Comment by joshuacwnewton** [comment]
I've reopened this issue because @sandrinebedard and I have both individually run into the `Invalid version: 'dev'` error again.

* Our `master` branches have been updated to contain the changes from [#4001](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4001). (In other words, `cat spinalcordtoolbox/version.txt` returns `6.0.dev0`.)
* Our `PYTHONPATH` environment variables are _not_ set, meaning that this isn't [#4035](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4035) either.

Because this issue has disappeared in our CI, where we start from scratch each time my hunch is that maybe some sort of state from a past SCT installation is being preserved. (Maybe this has something to do with `pip`'s cache, or the fact that we install SCT in editable (`-e`) mode?)

I've tried adding `--no-cache-dir` to the `pip` commands in `install_sct`, but no dice. Still digging.

**Comment by joshuacwnewton** [comment]
I've identified the issue, I think.

Old editable installations leave behind an [`.egg-info`](https://peps.python.org/pep-0376/) metadata folder. `setuptools` will pick up on the metadata from this folder during re-installs, even if the metadata is outdated. Delete this folder before reinstalling SCT, and it will complete successfully.

We may want to update `install_sct` to delete `spinalcordtoolbox.egg-info` on install, in much the same way we delete the existing conda envs on install.
