### ISSUE TITLE
`sct_deepseg_sc` outputs segmentation with different `pixdim` than input image

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4025]
### Description

When running:

```
sct_deepseg_sc -i sub-001_T1w.nii.gz -c t1
```

The output SC seg has a different `pixdim` that the input image:

```
$ sct_image -i sub-001_T1w.nii.gz -header | grep pixdim
pixdim		[-1.0, 0.351562, 0.351562, 2.5, 0.889114, 0.0, 0.0, 0.0]
```

```
$ sct_image -i sub-001_T1w_seg.nii.gz -header | grep pixdim
pixdim		[-1.0, 0.351562, 0.351563, 2.499999, 1.0, 1.0, 1.0, 1.0]
```

Notice the difference `2.5, 0.889114, 0.0, 0.0, 0.0` vs `2.499999, 1.0, 1.0, 1.0, 1.0`.

This difference is consequently raising errors ([here](https://github.com/MIC-DKFZ/nnUNet/blob/d1431c223407c3a66222409cb67c19ae87b2ce6a/nnunet/preprocessing/sanity_checks.py#L150-L152) and [here](https://github.com/MIC-DKFZ/nnUNet/blob/d1431c223407c3a66222409cb67c19ae87b2ce6a/nnunet/preprocessing/sanity_checks.py#L62-L63)) when using [`nnU-Net`](https://github.com/MIC-DKFZ/nnUNet) package.

Example data availbele here.

**Comment by joshuacwnewton** [comment]
I can reproduce this issue using testing data, too: 

```console
master|joshua@tadpole:~/repos/spinalcordtoolbox$ cd data/sct_example_data/t1
master|joshua@tadpole:~/repos/spinalcordtoolbox/data/sct_example_data/t1$ sct_deepseg_sc -i t1.nii.gz -c t1

--
Spinal Cord Toolbox (git-master-9f4d05ad2ce9bd48fd5a396310597fb5db645253)

sct_deepseg_sc -i t1.nii.gz -c t1
--

[...] 

Done! To view results, type:
fsleyes /home/joshua/repos/spinalcordtoolbox/data/sct_example_data/t1/t1.nii.gz -cm greyscale /home/joshua/repos/spinalcordtoolbox/data/sct_example_data/t1/t1_seg.nii.gz -cm red -a 70.0 &

master|joshua@tadpole:~/repos/spinalcordtoolbox/data/sct_example_data/t1$ sct_image -i t1.nii.gz -header | grep pixdim
pixdim		[1.0, 0.999996, 1.0, 1.0, 2.0, 0.0, 0.0, 0.0]
master|joshua@tadpole:~/repos/spinalcordtoolbox/data/sct_example_data/t1$ sct_image -i t1_seg.nii.gz -header | grep pixdim
pixdim		[1.0, 0.999996, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
```

I'll dig into the cause next.

**Comment by joshuacwnewton** [comment]
This behavior comes from `nibabel`:

- The `pixdim` field has 8 values.
- However, only some of those values are relevant:
   - `pixdim[0]` is [reserved](https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/pixdim.html#ref0) to specify scalar/vector data for 4D images.
   - 3D images use `pixdim[1:3]`,  4D images use `pixdim[1:4]`, etc. for 5D, 6D, up to 7D.
   - The remaining values of pixdim seem to be unused.  (e.g. `[4:7]`, `[5:7]`, etc. depending on the image dimensions) 
- When loading an image, Nibabel only keeps the relevant `pixdim` values. 
- So, when saving an image, it doesn't know about the "unused" pixdim values, therefore it sets them to `1.0`.
- See also: https://github.com/nipy/nibabel/issues/1034

**Comment by joshuacwnewton** [comment]
Your input image is 3D, meaning that only the values `pixdim[0:3]` should be relevant; `pixdim[4:7]` should be "unused".

So, my question is: Why does the `nnU-Net` software care about the "unused" pixdim fields? This seems overly sensitive to me. Especially given https://github.com/nipy/nibabel/issues/1034#issuecomment-888455701:

> The standard provides no interpretation for dimensions beyond `dim[0]` or guidance on what they should be, so there is no correct/incorrect setting. They should not be considered to have any impact on the interpretation of the data at all.

**Comment by joshuacwnewton** [comment]
To fix this on SCT's end, we would have to store the original values of `pixdim[4:7]` ourselves. (But, I'm not sure if `nibabel` even provides access to the other `pixdim` values?)

Unfortunately, however, even if we are able to access the old `pixdim` values, we run into another issue: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2462#issuecomment-1396266576. Right now, SCT's `Image` objects mishandle `dim[4:7]` and `pixdim[4:7]`, so we would have to rewrite that part of `Image`. :sweat:

**Comment by valosekj** [comment]
After deeper digging, it seems that the problem is not caused by `pixdim` how I initially thought:

> Notice the difference `2.5, 0.889114, 0.0, 0.0, 0.0` vs `2.499999, 1.0, 1.0, 1.0, 1.0`.
> This difference is consequently raising errors ([here](https://github.com/MIC-DKFZ/nnUNet/blob/d1431c223407c3a66222409cb67c19ae87b2ce6a/nnunet/preprocessing/sanity_checks.py#L150-L152) and [here](https://github.com/MIC-DKFZ/nnUNet/blob/d1431c223407c3a66222409cb67c19ae87b2ce6a/nnunet/preprocessing/sanity_checks.py#L62-L63)) when using [`nnU-Net`](https://github.com/MIC-DKFZ/nnUNet) package.

It also seems that the problem is not related to `nibabel` but to [SimpleITK](https://simpleitk.org).
The issue comes from[ `SimpleITK.Image::GetDirection()`](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1Image.html#a7bd35f108a2df5c966285405af409548) method, which is [used by nnU-Net](https://github.com/MIC-DKFZ/nnUNet/blob/d1431c223407c3a66222409cb67c19ae87b2ce6a/nnunet/preprocessing/sanity_checks.py#L45) to verify geometry between image and segmentation.

See the difference in ITK `direction` between `sub-001_T1w.nii.gz` and `sub-001_T1w_seg.nii.gz` (data available [here](https://www.dropbox.com/sh/piwt2050fjbljqg/AADhZH9BnQFWcVlQFoEhBZb7a?dl=0)) using [read_itk.py](https://gist.github.com/valosekj/a03195d9060b0e164faff95102129feb#file-read_itk-py):

```console
$ python ./read_itk.py sub-001_T1w.nii.gz sub-001_T1w_seg.nii.gz
origin:
(-90.7466812133789, 103.52926635742188, -57.17771911621094)
(-90.7466812133789, 103.52926635742188, -57.17771911621094)
spacing:
(0.3515625, 0.3515625, 2.5)
(0.3515625, 0.3515625298023224, 2.4999990463256836)
direction:
(0.9999999977894414, -6.478192795954982e-09, 6.649148620669932e-05, 2.0651083342197973e-05, -0.9505162149977084, -0.3106749763676334, -6.320324401990454e-05, -0.31067495075469176, 0.950516204300512)
(0.9999999999453735, 1.0322302829269651e-05, 1.6441191221002595e-06, 1.032230276040639e-05, -0.9505162024305571, -0.31067497705397884, 1.6441191998447065e-06, -0.31067498903265794, 0.9505162064003994)
size:
(512, 512, 42)
(512, 512, 42)
```

A possible fix is to set the direction from `sub-001_T1w.nii.gz` to `sub-001_T1w_seg.nii.gz` using [change_itk_direction.py](https://gist.github.com/valosekj/a03195d9060b0e164faff95102129feb#file-change_itk_direction-py):

```console
python ./change_itk_direction.py sub-001_T1w.nii.gz sub-001_T1w_seg.nii.gz
```

Then the direction is (almost) the same, and `nnU-Net` is satisfied:

```console
$ python ./read_itk.py sub-001_T1w.nii.gz sub-001_T1w_seg_updated_dir.nii.gz
origin:
(-90.7466812133789, 103.52926635742188, -57.17771911621094)
(-90.7466812133789, 103.52926635742188, -57.17771911621094)
spacing:
(0.3515625, 0.3515625, 2.5)
(0.3515625, 0.3515625298023224, 2.4999990463256836)
direction:
(0.9999999977894414, -6.478192795954982e-09, 6.649148620669932e-05, 2.0651083342197973e-05, -0.9505162149977084, -0.3106749763676334, -6.320324401990454e-05, -0.31067495075469176, 0.950516204300512)
(0.9999999977894414, -6.4774766359226164e-09, 6.649148620669932e-05, 2.0651080755190826e-05, -0.9505162169214625, -0.3106749763676334, -6.320324401990454e-05, -0.31067494486892744, 0.950516204300512)
size:
(512, 512, 42)
(512, 512, 42)
```

Further reading: [Simple ITK Fundamental Concepts](https://simpleitk.readthedocs.io/en/master/fundamentalConcepts.html)

Thanks to my colleague @KaterinaKrejci231054 for help with debugging!

**Comment by valosekj** [comment]
> I have some follow-up questions:

Good questions! I don't have the answers right now. We will continue with further digging.

**Comment by valosekj** [comment]
Might be remotely related to https://github.com/ivadomed/model_seg_sci/issues/21. It seems that `torchIO` also uses `SimpleITK`.

**Comment by valosekj** [comment]
Just for a record, I encountered the same ITK direction error also for `sci-zurich` dataset after using `sct_crop_image` and `sct_resample` (used preprocessing script available [here](https://github.com/ivadomed/model_seg_sci/blob/3a8403004586c5c98bf4c62fb9e2e190cff1fb2f/preprocessing/preprocess_data_sci-zurich.sh)).

Again, I fixed the issue using [change_itk_direction.py](https://gist.github.com/valosekj/a03195d9060b0e164faff95102129feb#file-change_itk_direction-py):
```
for sub in sub*;do cd $sub; for ses in ses*;do cd $ses/anat; python ~/code/change_itk_direction.py ${sub}_${ses}_acq-sag_T2w.nii.gz ../../../derivatives/labels/${sub}/${ses}/anat/${sub}_${ses}_acq-sag_T2w_lesion-manual.nii.gz; cd ../..; done; cd ..;echo $sub done;done
```

The script raised an error for `sub-zh21`, though:

```
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p118175/code/change_itk_direction.py", line 15, in <module>
    image1  = sitk.ReadImage(sys.argv[1])
  File "/home/GRAMES.POLYMTL.CA/p118175/code/model_seg_sci/venv/lib/python3.10/site-packages/SimpleITK/extra.py", line 355, in ReadImage
    return reader.Execute()
  File "/home/GRAMES.POLYMTL.CA/p118175/code/model_seg_sci/venv/lib/python3.10/site-packages/SimpleITK/SimpleITK.py", line 8438, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK-build/ITK/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx:2016:
ITK ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!
```

Thus, I removed the `sub-zh21` subject entirely from the training dataset. Now `nnUNetv2_plan_and_preprocess  --verify_dataset_integrity` is happy.

Tagging @naga-karthik to let him know.

**Comment by rickymwalsh** [comment]
Hi all, 

I came across similar problems with discrepancies in direction matrices throwing errors when training with torchio, and also solved by using the method .SetDirection(). I dug a bit into what might cause it on SITK side and so here's my take on your questions above. I'm no expert in SITK nor C++, so take with a grain of salt :)
 
>     * What does the `direction` matrix represent? And, how is it computed? (In other words, how is it different than the various NIfTI1 image properties such as qform/sform matrices?)

It seems the direction matrix will be taken from either the qform or sform matrix based on the logic [here](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx#L1904). If sform and qform are "sufficiently" similar, then sform is used for direction matrix. Otherwise, if sform is orthonormal and sform_code==NIFTI_XFORM_SCANNER_ANAT, again sform is used. And then there are several other conditions to decide whether to use sform or qform.

Another difference is that the spacing/zooms are incorporated into the sform/qform matrices but seem not to be taken into account for the SITK direction matrix.

>     * What is causing the differences in the `direction` matrix between anat/seg images?

My _guess_ is that it's because the anat image has sform_code==NIFTI_XFORM_SCANNER_ANAT and so sform will be used to get the direction matrix whereas the seg image has sform_code==NIFTI_XFORM_ALIGNED_ANAT and so the qform may be used. Besides these differences, nearly every other piece of metadata is the same in both images. 

`import SimpleITK as sitk

im_anat = sitk.ReadImage('sub-001_T1w.nii.gz')
im_seg = sitk.ReadImage('sub-001_T1w_seg.nii.gz')

# Print out all metadata for both images side by side
for key in im_anat.GetMetaDataKeys():
    print(f'{key}: Anat: {im_anat.GetMetaData(key)}\t\tSeg: {im_seg.GetMetaData(key)}')`

**Comment by joshuacwnewton** [comment]
Just to clean up this issue a little (since this issue's title focuses on the dim/pixdim `1.0` values), I've summarized the conclusions in a separate issue:

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4132

And I've hidden the SITK-specific discussion as "off-topic", just so that we have one problem per issue.

Again, thank you so much @rickymwalsh! :hearts:
