### ISSUE TITLE
`sct_compute_compression` fails when processing several subjects in parallel 

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4185]
When running `sct_compute_compression -normalize-hc 1 -o compression_metrics.csv` (see lines [here](https://github.com/sct-pipeline/dcm-metric-normalization/blob/d985ac0ca24d6253bfe717310f4c6a3529243b60/scripts/process_data_dcm-zurich.sh#L198-L206)) across multiple-subjects at once using the `sct_run_batch -jobs 32` wrapper on a cluster, the `sct_compute_compression` fails for some subjects. For example, see `err.process_data_dcm-zurich_sub-804109.log`:

```
Compression at level 5
area_ratio = 2.621303869309921
area_ratio_PAM50 = 6.489769026214853
area_ratio_PAM50_normalized = 11.731383660558114
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_compute_compression.py", line 663, in <module>
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_compute_compression.py", line 657, in main
    save_df_to_csv(df_metric_ratios, fname_out)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_compute_compression.py", line 506, in save_df_to_csv
    dataframe_old = pd.read_csv(fname_out, index_col=INDEX_COLUMNS)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 678, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 932, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1234, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 75, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 551, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

When I tested the function locally for a single subject, it worked fine.

Might the reason be that I am trying to write metrics from several subjects into the same CSV file (specified by `-o compression_metrics.csv`) at once?

**Comment by valosekj** [comment]
Interestingly, when running `sct_compute_compression` without the latest changes proposed in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4176 using: 

```console
$ cd $SCT_DIR
$ git checkout fd76016
```

`sct_compute_compression` fails only for 7 subjects:

```console
$ p118175@joplin:~/extrassd1/janvalosek/dcm-zurich_2023-08-09_persex/log$ ls err* | wc -l
7
```

And for example, `sub-804109` from the [first comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4185#issue-1842026140) finished without any error.


The error message for the 7 subjects is the same as in  the [first comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4185#issue-1842026140); see, for example, `err.process_data_dcm-zurich_sub-534449.log`:

```
Compression at level 5
solidity_ratio = 1.9054939812408023
solidity_ratio_PAM50 = 1.7492890839982067
solidity_ratio_PAM50_normalized = 1.4783958596472635
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_compute_compression.py", line 662, in <module>
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_compute_compression.py", line 656, in main
    save_df_to_csv(df_metric_ratios, fname_out)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_compute_compression.py", line 503, in save_df_to_csv
    dataframe_old = pd.read_csv(fname_out)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 678, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 932, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1234, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 75, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 551, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by valosekj** [comment]
Notes from the SCT dev meeting on 2023-08-10:
- Possible solution: output several individual files (one for each subject and each metric), then merge them
- Check also `sct_process_segmentation`, which also supports appending metrics into a single CSV file

**Comment by valosekj** [comment]
I also tested running the processing (see [here](https://github.com/sct-pipeline/dcm-metric-normalization/blob/d985ac0ca24d6253bfe717310f4c6a3529243b60/scripts/process_data_dcm-zurich.sh#L198-L206)) on `dcm-zurich`  using `sct_run_batch -jobs 1` (i.e., not in parallel) and the processing finished without any errors. But it took 08h03m19s.

**Comment by joshuacwnewton** [comment]
Sorry for the late reply, just taking a look at this now! I notice in your batch script that you're outputting the results for all subjects to the same CSV file: `${PATH_RESULTS}/compression_metrics.csv`. This is _defintely_ the cause. Even with appending behavior, since we don't have any sort of file locking, the parallel subject processing would definitely result in multiple accesses to the same file. (That would explain why `-jobs 1` also fixes the problem.)

> Possible solution: output several individual files (one for each subject and each metric), then merge them

You shouldn't need to output one file per metric -- it should be fine to just have one file per subject? e.g. using the output path `${PATH_RESULTS}/${SUBJECT}_compression_metrics.csv` instead.
