### ISSUE TITLE
`sct_deepseg_sc` fails with unintuitive error when no segmentation is detected

### ISSUE THREAD

**Issue by 4rnaudB** [spinalcordtoolbox/spinalcordtoolbox#4197]
### Description

Ran the following command with this file: [sub-example_unshimmed_e1.nii.gz](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/12370499/sub-example_unshimmed_e1.nii.gz). `sct_propseg` worked fine with the same file. 

```~/Downloads/tmep » sct_deepseg_sc -i /Users/arnaud/Documents/MSC/sim_outputs/rt_shim_nifti_with_seg/acdc_149/run_1/rt_shim_nifti/sub-example/anat/sub-example_unshimmed_e1.nii.gz -c t1 -qc .                                  arnaud@Arnauds-MacBook-Pro

--
Spinal Cord Toolbox (6.0)

sct_deepseg_sc -i /Users/arnaud/Documents/MSC/sim_outputs/rt_shim_nifti_with_seg/acdc_149/run_1/rt_shim_nifti/sub-example/anat/sub-example_unshimmed_e1.nii.gz -c t1 -qc .
--

Config deepseg_sc:
  Centerline algorithm: svm
  Brain in image: True
  Kernel dimension: 2d
  Contrast: t1
  Threshold: 0.15
Creating temporary folder (/var/folders/74/2213n8nd7m72kd61t3z47rf40000gn/T/sct_2023-08-16_11-57-51_deepseg-sc_2qp4ueq5)
Reorient the image to RPI, if necessary...
Finding the spinal cord centerline...
Creating temporary folder (/var/folders/74/2213n8nd7m72kd61t3z47rf40000gn/T/sct_2023-08-16_11-57-52_optic-detect-centerline_igh5766q)
Remove temporary files...
rm -rf /var/folders/74/2213n8nd7m72kd61t3z47rf40000gn/T/sct_2023-08-16_11-57-52_optic-detect-centerline_igh5766q
Cropping the image around the spinal cord...
Normalizing the intensity...
Segmenting the spinal cord using deep learning on 2D patches...
Reassembling the image...
Resampling the segmentation to the native image resolution using linear interpolation...
Binarizing the resampled segmentation...
Image header specifies datatype 'float32', but array is of type 'uint8'. Header metadata will be overwritten to use 'uint8'.
Traceback (most recent call last):
  File "/Users/arnaud/sct_6.0/spinalcordtoolbox/scripts/sct_deepseg_sc.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/arnaud/sct_6.0/spinalcordtoolbox/scripts/sct_deepseg_sc.py", line 188, in main
    deep_segmentation_spinalcord(im_image.copy(), contrast_type, ctr_algo=ctr_algo,
  File "/Users/arnaud/sct_6.0/spinalcordtoolbox/deepseg_/sc.py", line 530, in deep_segmentation_spinalcord
    im_seg_r_postproc = post_processing_volume_wise(im_seg_r)
  File "/Users/arnaud/sct_6.0/spinalcordtoolbox/deepseg_/postprocessing.py", line 146, in post_processing_volume_wise
    im_seg = _remove_isolated_voxels_on_the_edge(im_seg)
  File "/Users/arnaud/sct_6.0/spinalcordtoolbox/deepseg_/postprocessing.py", line 112, in _remove_isolated_voxels_on_the_edge
    metrics, _ = compute_shape(im_seg, angle_correction=False)
  File "/Users/arnaud/sct_6.0/spinalcordtoolbox/process_seg.py", line 63, in compute_shape
    min_z_index, max_z_index = min(Z), max(Z)
ValueError: min() arg is an empty sequence
```

**Comment by joshuacwnewton** [comment]
It looks the segmentation itself failed -- an empty segmentation was produced by the internal `deep_segmentation_spinalcord` function:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/809196e0-7f93-4b3a-ba2e-18ec1371c92b)

We should definitely have a better error in cases such as this, rather than letting the processing continue until it fails in an unclear way.
