### ISSUE TITLE
`ValueError: could not broadcast array (7) into shape (12)` during `-method restore`

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4209]
### Description

`sct_dmri_compute_dti -method restore` fails with the following error:

```console
$ cd $SCT_DIR/data/course_london20/single_subject/data/dmri
$ sct_dmri_compute_dti -i dmri.nii.gz -bval bvals.txt -bvec bvecs.txt -method restore 

--
Spinal Cord Toolbox (git-master-76c27e16f13974de3ff8f81e25c92abe8f6d80ec)

sct_dmri_compute_dti -i dmri.nii.gz -bval bvals.txt -bvec bvecs.txt -method restore
--

data.shape (96, 36, 15, 35)
Computing tensor using "restore" method...
Traceback (most recent call last):
  File "/Users/valosek/code/sct_latest/spinalcordtoolbox/scripts/sct_dmri_compute_dti.py", line 183, in <module>
    main(sys.argv[1:])
  File "/Users/valosek/code/sct_latest/spinalcordtoolbox/scripts/sct_dmri_compute_dti.py", line 100, in main
    if not compute_dti(fname_in, fname_bvals, fname_bvecs, prefix, method, evecs, file_mask, verbose):
  File "/Users/valosek/code/sct_latest/spinalcordtoolbox/scripts/sct_dmri_compute_dti.py", line 150, in compute_dti
    tenfit = dti_restore.fit(data)
  File "/Users/valosek/code/sct_latest/python/envs/venv_sct/lib/python3.8/site-packages/dipy/reconst/dti.py", line 813, in fit
    params_in_mask = self.fit_method(
  File "/Users/valosek/code/sct_latest/python/envs/venv_sct/lib/python3.8/site-packages/dipy/reconst/dti.py", line 1859, in restore_fit_tensor
    D = ols_fit_tensor(design_matrix, flat_data, return_lower_triangular=True)
  File "/Users/valosek/code/sct_latest/python/envs/venv_sct/lib/python3.8/site-packages/dipy/reconst/dti.py", line 1327, in wrapped_fit_tensor
    dtiparams[i:i + step] = fit_tensor(design_matrix,
ValueError: could not broadcast input array from shape (10000,7) into shape (10000,12)
```

### Steps to Reproduce

```console
$ cd $SCT_DIR/data/course_london20/single_subject/data/dmri
$ sct_dmri_compute_dti -i dmri.nii.gz -bval bvals.txt -bvec bvecs.txt -method restore 
```

**Comment by joshuacwnewton** [comment]
I can reproduce on `sct_example_data`, but the script passes without failure for `sct_testing_data`, which would probably explain how this hasn't come up before.

I found this old issue on the dipy repo: https://github.com/dipy/dipy/issues/439. Even though the code has probably changed a _lot_ since 2015, the context + error message look very similar:

```
  File "/usr/local/lib/python2.7/dist-packages/dipy/reconst/dti.py", line 1544, in restore_fit_tensor
    dti_params[vox, :] = start_params
ValueError: could not broadcast input array from shape (7) into shape (12)
```

(Both errors occur in `dipy/reconst/dti.py :: restore_fit_tensor()`, both are assigning to `dti_params`, both reference `7` and `12`.)

Oddly enough, the issue was closed without much of a resolution. The best insight it provides is:

> Thanks for reporting this. Note that this probably means that RESTORE has actually failed to fit on this voxel, and the algorithm is falling back on the OLS solution. 

Maybe we could report this issue back upstream?
