### ISSUE TITLE
Non-fatal `KeyError: 'fsleyes_pink'` during FSLeyes script testing

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4277]
When running the SCT FSLeyes script, the following non-fatal traceback appears in the terminal window:

<details>
<summary> Full traceback </summary>

```
 WARNING         callqueue.py  226: __call          - Function PropertyValue_overlays_OverlayDisplayToolBar_139692548474336 (OverlayList.overlays) raised exception: 'fsleyes_pink'
Traceback (most recent call last):
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes/colourmaps.py", line 1262, in _caseInsensitiveLookup
    idx = lKeys.index(k.lower())
          ^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'fsleyes_pink' is not in list
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes_props/callqueue.py", line 222, in __call
    call.func(*call.args, **call.kwargs)
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes/controls/overlaydisplaytoolbar.py", line 240, in __selectedOverlayChanged
    self.__showTools(overlay)
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes/controls/overlaydisplaytoolbar.py", line 181, in __showTools
    optsTools, optsNav = makeFunc(opts)
                         ^^^^^^^^^^^^^^
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes/controls/overlaydisplaytoolbar.py", line 351, in __makeVolumeOptsTools
    cmapWidget       = props.buildGUI(cmapPanel, opts, cmapSpec)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes_props/build.py", line 1018, in buildGUI
    mainPanel = _create(parentObj, view, hasProps, propGui)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes_props/build.py", line 780, in _create
    guiObject = createFunc(parent, viewItem, hasProps, propGui)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes_props/build.py", line 474, in _createWidget
    widget = widgets.makeWidget(    parent,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes_props/widgets.py", line 782, in makeWidget
    return makeFunc(parent, hasProps, propObj, propVal, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes_props/widgets.py", line 664, in _ColourMap
    cmapsChanged()
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes_props/widgets.py", line 636, in cmapsChanged
    name = labels(cmap.name)
           ^^^^^^^^^^^^^^^^^
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes/colourmaps.py", line 745, in getColourMapLabel
    return _caseInsensitiveLookup(_cmaps, key).name
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes/colourmaps.py", line 1265, in _caseInsensitiveLookup
    else:                   raise  KeyError(k)
                            ^^^^^^^^^^^^^^^^^^
KeyError: 'fsleyes_pink'
  File "/home/joshua/repos/fsleyes/bin/fsleyes", line 10, in <module>
    sys.exit(main())
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes/filtermain.py", line 218, in main
    result = fm.main(args)
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes/main.py", line 465, in main
    app.MainLoop()
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/wx/core.py", line 2262, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "/home/joshua/repos/spinalcordtoolbox/contrib/fsl_integration/sct_fsleyes_script.py", line 681, in on_button_run
    overlayList.append(image)
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes/overlay.py", line 306, in append
    self.insert(len(self), item, **initProps)
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes/overlay.py", line 296, in insert
    with props.suppress(self, 'overlays', notify=True):
  File "/home/joshua/repos/fsleyes/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes_props/suppress.py", line 61, in suppress
    hasProps.propNotify(propName)
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes_props/properties.py", line 910, in propNotify
    self.getPropVal(propName).propNotify()
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes_props/properties_value.py", line 861, in propNotify
    bindable.syncAndNotify(self)
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes_props/bindable.py", line 286, in syncAndNotify
    _callAllListeners([self] + allBpvs, False)
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes_props/bindable.py", line 943, in _callAllListeners
    q.callAll(queued + held)
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes_props/callqueue.py", line 170, in callAll
    self.__call()
  File "/home/joshua/repos/fsleyes/lib/python3.11/site-packages/fsleyes_props/callqueue.py", line 228, in __call
    traceback.print_stack()
```
</details>

The line mentioned in the traceback is here:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/012487bbf379f6cd11c3f761502548d5d8217966/contrib/fsl_integration/sct_fsleyes_script.py#L681

However, nowhere in the SCT FSLeyes script do we actually mention `pink` as a colormap. So, I think this might be an upstream bug with FSLeyes. Still, I thought I'd mention it here just in case.

**Comment by joshuacwnewton** [comment]
Indeed, this is an upstream error: https://github.com/pauldmccarthy/fsleyes/issues/120#issuecomment-1730988902

Closing this issue, as it will be naturally resolved by an upstream FSLeyes update.
