### ISSUE TITLE
RTD build failing

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4340]
https://readthedocs.org/projects/spinalcordtoolbox/builds/23109940

Error message:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/spinalcordtoolbox/envs/4302/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/spinalcordtoolbox/envs/4302/lib/python3.9/site-packages/sphinx/application.py", line 233, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/spinalcordtoolbox/envs/4302/lib/python3.9/site-packages/sphinx/application.py", line 393, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/spinalcordtoolbox/envs/4302/lib/python3.9/site-packages/sphinx/registry.py", line 445, in load_extension
    raise VersionRequirementError(
sphinx.errors.VersionRequirementError: The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.

Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
```

**Comment by joshuacwnewton** [comment]
The error message complains about not having `sphinx==5.x`. It looks like we pin:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/35f98892825b6d84a934bfe62471f0a7aad04ec1/setup.py#L52

Unpinning should resolve this error.

>[!NOTE]
> For context, it looks like we began pinning Sphinx in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3489, specifically https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/7c10fe3749f932a3e924f2283a4ba40f5df217ad.
> 
> The commit description says "update sphinx", yet pinning to a patch version does the opposite by holding `sphinx` back. Plus, prior to the commit we left `sphinx` unpinned. I wasn't involved in reviewing this PR, but in hindsight, I don't know if I agree that we should have ever pinned sphinx in the first place.
