### ISSUE TITLE
`OSError: [Errno 5] Input/output error` when splitting dMRI file during `sct_run_batch -jobs 1` experiment

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4431]
### Description

Context: https://github.com/sct-pipeline/spine-park/issues/15

Issue: [err.batch_processing_sub-LD214.log](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/14933819/err.batch_processing_sub-LD214.log)

Traceback:

```python
--
Spinal Cord Toolbox (git-master-365651dbd7d31b909b7ec85844b0e6492a4649ca)

sct_dmri_moco -i sub-LD214_chunk-2_DWI.nii.gz -bvec sub-LD214_chunk-2_DWI.bvec -x spline
--


Input parameters:
  Input file ............ sub-LD214_chunk-2_DWI.nii.gz
  Group size ............ 3

# [...] (moco processing logs)

Creating temporary folder (/dagher/dagher11/lydia11/RESULTS_second_part_09042024/data_processed/sub-LD214/dwi/sct_2024-04-09_18-12-37_dmri-separate-b0-and-dwi_brf4wkgk)

Traceback (most recent call last):
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_dmri_moco.py", line 223, in <module>
    main(sys.argv[1:])
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_dmri_moco.py", line 208, in main
    fname_output_image = moco_wrapper(param)
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/moco.py", line 391, in moco_wrapper
    fname_b0, fname_b0_mean, fname_dwi, fname_dwi_mean = sct_dmri_separate_b0_and_dwi.main(argv=args)
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_dmri_separate_b0_and_dwi.py", line 176, in main
    im_d.save()
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/image.py", line 547, in save
    self.copy().save(path, dtype, verbose, mutable=True)
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/image.py", line 542, in save
    nib.save(nib.nifti1.Nifti1Image(dataobj, affine, header), self.absolutepath)
  File "/export02/data/lydiac/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/nibabel/loadsave.py", line 99, in save
    img.to_filename(filename)
  File "/export02/data/lydiac/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/nibabel/filebasedimages.py", line 333, in to_filename
    self.to_file_map()
  File "/export02/data/lydiac/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/nibabel/analyze.py", line 1045, in to_file_map
    hdrf.close_if_mine()
  File "/export02/data/lydiac/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/nibabel/openers.py", line 183, in close_if_mine
    self.close()
  File "/export02/data/lydiac/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/nibabel/openers.py", line 174, in close
    return self.fobj.close(*args, **kwargs)
OSError: [Errno 5] Input/output error
```

### Steps to Reproduce

Will ask for data

**Comment by joshuacwnewton** [comment]
Thanks for the report! (I added the traceback to the issue description.)

I notice that the error occurs when saving the image here:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/83c1d2766e2ce69e15d1831deaa2ac4ed5646064/spinalcordtoolbox/scripts/sct_dmri_separate_b0_and_dwi.py#L172-L176

Tracing the relevant bits of code, I can't see anything that might result in a conflict? The tmpdir is unique, and each T-dim file should have a unique name (thanks to the logic in `split_img_data`).

The one thing that is somewhat suspicious to me is the folder paths?

- SCT install dir: `/export02/data/lydiac/spinalcordtoolbox/`
- Data dir: `/dagher/dagher11/lydia11/RESULTS_second_part_09042024`
- Tmpdir: `/dagher/dagher11/lydia11/RESULTS_second_part_09042024/data_processed/sub-LD214/dwi/sct_2024-04-09_18-12-37_dmri-separate-b0-and-dwi_brf4wkgk`

Some thoughts:

- It seems like both the install directory _and_ the data directory might be mounted? 
- Also, curiously, the tempdir was not created in `tmp/`, implying that there is no `tmp/` folder? Tempdir creation is handled by `tempfile.mkdtemp`. From the `tempfile` docs:
   > Python searches a standard list of directories to find one which the calling user can create files in. The list is:
   > 
   > 1. The directory named by the TMPDIR environment variable.
   > 2. The directory named by the TEMP environment variable.
   > 3. The directory named by the TMP environment variable.
   > 4. A platform-specific location:
   >     * On Windows, the directories C:\TEMP, C:\TMP, \TEMP, and \TMP, in that order.
   >     * On all other platforms, the directories /tmp, /var/tmp, and /usr/tmp, in that order.
   > 5. As a last resort, the current working directory.

  It looks like we're hitting the "last resort" tempdir, which may hint at the nonstandard filesystem setup in this situation.

----

Despite this, I don't really have a smoking gun for why we're encountering this issue, besides the possibility of disk issues (as mentioned in https://github.com/sct-pipeline/spine-park/issues/15#issuecomment-2047828874).

**Comment by joshuacwnewton** [comment]
I _think_ the conclusion we came to is that these were disk space errors. So, I'm going to close this as completed for now, and if further issues come up in the future, we can revisit. :)
