### ISSUE TITLE
`portalocker` error when running `sct_qc` with a large number of jobs in parallel

### ISSUE THREAD

**Issue by naga-karthik** [spinalcordtoolbox/spinalcordtoolbox#4501]
I ran into a `portalocker.exceptions.AlreadyLocked` error when I running `sct_qc` in a [`sct_run_batch` script](https://github.com/jqmcginnis/miccai_amai_lesions_spine/blob/main/dataset-conversion/generate_qc_datasets_gt.sh) with a large number of jobs in parallel (`-jobs 32`). @mguaypaq suggested to use lesser number of jobs (ideally 1 to never run into this) but I was able to run the script successfully with `-jobs 8`. The full error trace is shown below.

<details>
<summary> Error trace </summary>

```
*** Generate Quality Control (QC) html report ***
Resampling image "sub-m018732_ses-20180107_acq-ax_T2w_desc-straightened.nii.gz" to 0.6x0.6 mm
Resampling image "sub-m018732_ses-20180107_acq-ax_T2w_seg-manual_desc-straightened.nii.gz" to 0.6x0.6 mm
[33mConverting image from type 'uint8' to type 'float64' for linear interpolation[0m
[33mImage header specifies datatype 'float64', but array is of type 'int64'. Header metadata will be overwritten to use 'int64'.[0m
QcImage: layout with Axial slice
Compute center of mass at each slice
/home/GRAMES.POLYMTL.CA/u114716/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/scipy/ndimage/_measurements.py:1542: RuntimeWarning: invalid value encountered in scalar divide
  results = [sum(input * grids[dir].astype(float), labels, index) / normalizer
/home/GRAMES.POLYMTL.CA/u114716/tum-poly/qc_straight_stitched/qc/sub-m018732/sub-m018732/ses-20180107/anat/sct_deepseg_sc/2024_05_30_130243.408480/background_img.png
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/u114716/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_qc.py", line 121, in <module>
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/u114716/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_qc.py", line 104, in main
    generate_qc(fname_in1=arguments.i,
  File "/home/GRAMES.POLYMTL.CA/u114716/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 771, in generate_qc
    QcImage(
  File "/home/GRAMES.POLYMTL.CA/u114716/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 296, in layout
    self._make_QC_image_for_3d_volumes(img, mask, plane=self.qc_report.plane)
  File "/home/GRAMES.POLYMTL.CA/u114716/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 341, in _make_QC_image_for_3d_volumes
    self.qc_report.update_description_file()
  File "/home/GRAMES.POLYMTL.CA/u114716/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 588, in update_description_file
    with mutex(f"sct_qc-{os.path.basename(path_qc)}-{md5(self.path_qc.encode('utf-8')).hexdigest()}"):
  File "/home/GRAMES.POLYMTL.CA/u114716/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/GRAMES.POLYMTL.CA/u114716/spinalcordtoolbox/spinalcordtoolbox/utils/fs.py", line 281, in mutex
    semaphore.acquire()
  File "/home/GRAMES.POLYMTL.CA/u114716/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/portalocker/utils.py", line 493, in acquire
    raise exceptions.AlreadyLocked()
portalocker.exceptions.AlreadyLocked

```

</details>

Command used:

```
sct_run_batch -path-data ~/tum-poly/straightened_sc_stitch_linear_bin_full/data_processed_clean -path-output ~/tum-poly/qc_straight_stitched_2 -jobs 32 -script ~/tum-poly/miccai_amai_lesions_spine/dataset-conversion/generate_qc_datasets_gt.sh -script-args "stitched"
```

**Comment by joshuacwnewton** [comment]
I'm surprised by this! The `mutex` we added should have a timeout, so that if we happen to create multiple QCs at the same time, each process should wait its turn until the QC report has freed up resources.

I'm going to double-check whether this timeout is properly set...

**Comment by joshuacwnewton** [comment]
Could you please try a test for me, @naga-karthik?

On the machine with ~32 cores, could you run the following commands?

```bash
cd $SCT_DIR
git checkout jn/4501-ensure-mutex-uses-timeout
sct_testing -o log_cli=true testing/api/test_qc_parallel.py::test_many_qc
```

You should see some new `DEBUG` messages in the output that show the locking behavior in more detail. Hopefully, it will trigger the failure, or at least display some text such as `(attempt 0)` `(attempt 1)` etc.

**Comment by naga-karthik** [comment]
I do see some `DEBUG` messages! 

<details>
<summary> Full trace </summary>

```
u114716@rosenberg ~/data_nvme_u114716/spinalcordtoolbox$ sct_testing -o log_cli=true testing/api/test_qc_parallel.py::test_many_qc
================================================================ test session starts ================================================================
platform linux -- Python 3.9.19, pytest-8.1.1, pluggy-1.5.0 -- /home/GRAMES.POLYMTL.CA/u114716/data_nvme_u114716/spinalcordtoolbox/python/envs/venv_sct/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/GRAMES.POLYMTL.CA/u114716/data_nvme_u114716/spinalcordtoolbox
configfile: setup.cfg
plugins: cov-5.0.0, console-scripts-1.4.1
collected 1 item                                                                                                                                    

testing/api/test_qc_parallel.py::test_many_qc 
------------------------------------------------------------------- live log call -------------------------------------------------------------------
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'int16' to type 'float64' for spline interpolation


------------------------------------------------------------------- live log call -------------------------------------------------------------------
------------------------------------------------------------------- live log call -------------------------------------------------------------------
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'int16' to type 'float64' for spline interpolation
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'int16' to type 'float64' for spline interpolation

------------------------------------------------------------------- live log call -------------------------------------------------------------------
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'int16' to type 'float64' for spline interpolation

------------------------------------------------------------------- live log call -------------------------------------------------------------------
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'int16' to type 'float64' for spline interpolation

------------------------------------------------------------------- live log call -------------------------------------------------------------------

------------------------------------------------------------------- live log call -------------------------------------------------------------------
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'int16' to type 'float64' for spline interpolation
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'int16' to type 'float64' for spline interpolation

------------------------------------------------------------------- live log call -------------------------------------------------------------------

------------------------------------------------------------------- live log call -------------------------------------------------------------------
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'int16' to type 'float64' for spline interpolation
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'int16' to type 'float64' for spline interpolation

------------------------------------------------------------------- live log call -------------------------------------------------------------------
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'int16' to type 'float64' for spline interpolation
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'uint8' to type 'float64' for linear interpolation
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'uint8' to type 'float64' for linear interpolation
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'uint8' to type 'float64' for linear interpolation
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'uint8' to type 'float64' for linear interpolation
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'uint8' to type 'float64' for linear interpolation
WARNING  spinalcordtoolbox.image:image.py:415 Image header specifies datatype 'float64', but array is of type 'int64'. Header metadata will be overwritten to use 'int64'.
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'uint8' to type 'float64' for linear interpolation
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'uint8' to type 'float64' for linear interpolation
WARNING  spinalcordtoolbox.image:image.py:415 Image header specifies datatype 'float64', but array is of type 'int64'. Header metadata will be overwritten to use 'int64'.
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'uint8' to type 'float64' for linear interpolation
WARNING  spinalcordtoolbox.image:image.py:415 Image header specifies datatype 'float64', but array is of type 'int64'. Header metadata will be overwritten to use 'int64'.
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'uint8' to type 'float64' for linear interpolation
WARNING  spinalcordtoolbox.image:image.py:415 Image header specifies datatype 'float64', but array is of type 'int64'. Header metadata will be overwritten to use 'int64'.
WARNING  spinalcordtoolbox.image:image.py:415 Image header specifies datatype 'float64', but array is of type 'int64'. Header metadata will be overwritten to use 'int64'.
WARNING  spinalcordtoolbox.image:image.py:415 Image header specifies datatype 'float64', but array is of type 'int64'. Header metadata will be overwritten to use 'int64'.
WARNING  spinalcordtoolbox.resampling:resampling.py:64 Converting image from type 'uint8' to type 'float64' for linear interpolation
WARNING  spinalcordtoolbox.image:image.py:415 Image header specifies datatype 'float64', but array is of type 'int64'. Header metadata will be overwritten to use 'int64'.
WARNING  spinalcordtoolbox.image:image.py:415 Image header specifies datatype 'float64', but array is of type 'int64'. Header metadata will be overwritten to use 'int64'.
WARNING  spinalcordtoolbox.image:image.py:415 Image header specifies datatype 'float64', but array is of type 'int64'. Header metadata will be overwritten to use 'int64'.
WARNING  spinalcordtoolbox.image:image.py:415 Image header specifies datatype 'float64', but array is of type 'int64'. Header metadata will be overwritten to use 'int64'.
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 0) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:507 locked PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 0) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:507 locked PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 0) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:507 locked PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 0) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 1) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 0) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:507 locked PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 0) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 0) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:507 locked PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 1) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 0) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 0) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:507 locked PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 1) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 0) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 1) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 2) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:507 locked PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 2) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:507 locked PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 2) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:507 locked PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 2) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:484 trying lock (attempt 3) [PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')]
DEBUG    portalocker.utils:utils.py:500 trying lock for PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
DEBUG    portalocker.utils:utils.py:507 locked PosixPath('/tmp/sct_qc-sct-qc-qq6e14z3-8d1c49ba57250f79069646f9da4ed20a.00.lock')
PASSED                                                                                          [100%]

================================================================= 1 passed in 1.95s ===========================================================
```

</details>

**Comment by joshuacwnewton** [comment]
Awesome! Yes, it looks like things get a bit backed up with 32 jobs, but not *too* severely. I'm hopeful that increasing the timeout above 5 seconds will fix this. I'll open up a PR with my fix. :)

**Comment by naga-karthik** [comment]
Ah okay! I usually use 8 or 16 jobs and they work alright. But this time I pushed it and I guess it didn't like that 😅

**Comment by mguaypaq** [comment]
How about a 1 minute timeout? That _should_ allow Naga to run many concurrent jobs, but still error out in a reasonable amount of time in case there's something weird going on with the lock.

**Comment by joshuacwnewton** [comment]
That's exactly the value I chose for the PR I'm about to open! :tada:
