### ISSUE TITLE
FileNotFoundError: when using type=im with algo=centermassrot

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4516]
### Description

While working on a [forum issue](https://forum.spinalcordmri.org/t/anatomical-registration-between-sessions/957/6?u=jcohenadad), I tried using centermassrot with `type=im` and got the following error:

<details><summary>Terminal output</summary>

```console
sct_register_multimodal -i sub-CTS05_ses-SPpost_T2w_crop_08iso.nii.gz -iseg sub-CTS05_ses-SPpost_T2w_deepseg_08iso.nii.gz -ilabel sub-CTS05_ses-SPpost_T2w_deepseg_labeled_commonverts_prepost.nii.gz -d sub-CTS05_ses-SPpre_T2w_crop_08iso.nii.gz -dseg sub-CTS05_ses-SPpre_T2w_deepseg_08iso.nii.gz -dlabel  sub-CTS05_ses-SPpre_T2w_deepseg_labeled_commonverts_prepost.nii.gz -param step=0,type=label,doi=Tx_Ty_Tz_Rx_Ry_Rz:step=1,type=seg,algo=slicereg:step=2,type=im,algo=centermassrot,rot_method=hog -qc qc

--
Spinal Cord Toolbox (git-master-bb479d82ea1e2076dd50343177056a61bd17e260)

sct_register_multimodal -i sub-CTS05_ses-SPpost_T2w_crop_08iso.nii.gz -iseg sub-CTS05_ses-SPpost_T2w_deepseg_08iso.nii.gz -ilabel sub-CTS05_ses-SPpost_T2w_deepseg_labeled_commonverts_prepost.nii.gz -d sub-CTS05_ses-SPpre_T2w_crop_08iso.nii.gz -dseg sub-CTS05_ses-SPpre_T2w_deepseg_08iso.nii.gz -dlabel sub-CTS05_ses-SPpre_T2w_deepseg_labeled_commonverts_prepost.nii.gz -param step=0,type=label,doi=Tx_Ty_Tz_Rx_Ry_Rz:step=1,type=seg,algo=slicereg:step=2,type=im,algo=centermassrot,rot_method=hog -qc qc
--


Input parameters:
  Source .............. sub-CTS05_ses-SPpost_T2w_crop_08iso.nii.gz (64, 100, 312)
  Destination ......... sub-CTS05_ses-SPpre_T2w_crop_08iso.nii.gz (64, 100, 312)
  Init transfo ........ 
  Mask ................ 
  Output name ......... 
  Remove temp files ... 1
  Verbose ............. 1

Check if input data are 3D...
Creating temporary folder (/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-06-06_13-29-56_register-wrapper_vfwn953n)

Copying input data to tmp folder and convert to nii...

--
ESTIMATE TRANSFORMATION FOR STEP #0
Registration parameters:
  type ........... label
  algo ........... syn
  slicewise ...... 0
  metric ......... MI
  samplStrategy .. None
  samplPercent ... 0.2
  iter ........... 0
  smooth ......... 0
  laplacian ...... 0
  shrink ......... 1
  gradStep ....... 0.5
  deformation .... 1x1x0
  init ........... 
  poly ........... 5
  filter_size .... 5
  dof ............ Tx_Ty_Tz_Rx_Ry_Rz
  smoothWarpXY ... 2
  rot_method ..... pca
Parameter 'algo=syn' has no effect for 'type=label' registration.
Labels src: [[-7.966402230031825, 59.93169631759489, 176.48641069746466], [-8.403401711260939, 58.73165216821087, 149.39930328451166], [-8.875245088321048, 58.07548792261792, 120.90972290686693], [-9.257079798208089, 58.580769886200514, 93.38368006923125], [-10.420240139172309, 59.038282086700036, 68.32420383123466]]
Labels dest: [[3.6173591607260462, 58.42120023959955, 170.14416251350983], [4.087160265236648, 57.07592168047108, 144.1335613152678], [4.65473995392361, 56.246088381435555, 115.19674302593363], [5.218838084230111, 56.28877643622198, 86.9965859858534], [3.8603236536501484, 57.23257520752302, 62.01379146129931]]
Degrees of freedom (dof): Tx_Ty_Tz_Rx_Ry_Rz
Optimization terminated successfully.
         Current function value: 1.567041
         Iterations: 11
         Function evaluations: 1282
Matrix:
 [[ 0.98492039  0.17117563  0.0251143 ]
 [-0.17108972  0.98523984 -0.00554673]
 [-0.02569307  0.00116629  0.9996692 ]]
Center:
 [  4.28768422  57.05291239 115.69696886]
Translation:
 [[-13.27215802   1.81866529   6.00369529]]

--
ESTIMATE TRANSFORMATION FOR STEP #1

Apply transformation from previous step
/Users/julien/code/spinalcordtoolbox/bin/isct_antsApplyTransforms -d 3 -i src_seg.nii -o src_seg_reg.nii -t warp_forward_0.txt -r dest_seg_RPI.nii -n NearestNeighbor # in /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-06-06_13-29-56_register-wrapper_vfwn953n
Registration parameters:
  type ........... seg
  algo ........... slicereg
  slicewise ...... 0
  metric ......... MeanSquares
  samplStrategy .. None
  samplPercent ... 0.2
  iter ........... 10
  smooth ......... 0
  laplacian ...... 0
  shrink ......... 1
  gradStep ....... 0.5
  deformation .... 1x1x0
  init ........... 
  poly ........... 5
  filter_size .... 5
  dof ............ Tx_Ty_Tz_Rx_Ry_Rz
  smoothWarpXY ... 2
  rot_method ..... pca
/Users/julien/code/spinalcordtoolbox/bin/isct_antsSliceRegularizedRegistration -t 'Translation[0.5]' -m 'MeanSquares[dest_seg_RPI_crop.nii,src_seg_reg_crop.nii,1,4,None,0.2]' -p 5 -i 10 -f 1 -s 0 -v 1 -o '[step1,src_seg_reg_crop_regStep1.nii]' # in /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-06-06_13-29-56_register-wrapper_vfwn953n

--
ESTIMATE TRANSFORMATION FOR STEP #2

Apply transformation from previous step
/Users/julien/code/spinalcordtoolbox/bin/isct_antsApplyTransforms -d 3 -i src.nii -o src_reg.nii -t warp_forward_1.nii.gz warp_forward_0.txt -r dest_RPI.nii -n 'BSpline[3]' # in /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-06-06_13-29-56_register-wrapper_vfwn953n
Registration parameters:
  type ........... im
  algo ........... centermassrot
  slicewise ...... 0
  metric ......... MeanSquares
  samplStrategy .. None
  samplPercent ... 0.2
  iter ........... 10
  smooth ......... 0
  laplacian ...... 0
  shrink ......... 1
  gradStep ....... 0.5
  deformation .... 1x1x0
  init ........... 
  poly ........... 5
  filter_size .... 5
  dof ............ Tx_Ty_Tz_Rx_Ry_Rz
  smoothWarpXY ... 2
  rot_method ..... hog
Creating temporary folder (/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-06-06_13-30-13_register-slicewise_6j1z22b3)

Copy input data to temp folder...

Get image dimensions of destination image...
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/nibabel/loadsave.py", line 100, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-06-06_13-30-13_register-slicewise_6j1z22b3/dest_seg.nii'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_register_multimodal.py", line 443, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_register_multimodal.py", line 412, in main
    register_wrapper(fname_src, fname_dest, param, paramregmulti, fname_src_seg=fname_src_seg,
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/registration/core.py", line 182, in register_wrapper
    warp_forward_out, warp_inverse_out = register(src=src, dest=dest, step=step, param=param)
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/registration/core.py", line 392, in register
    warp_forward_out, warp_inverse_out = algorithms.register_step_slicewise(
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/registration/algorithms.py", line 314, in register_step_slicewise
    register_slicewise(
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/registration/algorithms.py", line 616, in register_slicewise
    register2d_centermassrot(
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/registration/algorithms.py", line 694, in register2d_centermassrot
    nx, ny, nz, nt, px, py, pz, pt = image.Image(fname_dest[0]).dim
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/image.py", line 285, in __init__
    raise e
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/image.py", line 280, in __init__
    self.loadFromPath(param, mmap, verbose)
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/image.py", line 428, in loadFromPath
    im_file = nib.load(self.absolutepath, mmap=mmap)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/nibabel/loadsave.py", line 102, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '/private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-06-06_13-30-13_register-slicewise_6j1z22b3/dest_seg.nii'
```

</details>

I think the issue is that centermassrot _should_ take a segmentation as input, but the error is not "user friendly" and we should probably add a check that `type=seg` or `type=imseg` when used with `algo=centermassrot`. Unless the issue is elsewhere...

### Steps to Reproduce

SCT version: bb479d82ea1e2076dd50343177056a61bd17e260

Get data: 👉 [here](https://filesender.renater.fr/?s=download&token=070e26cb-318e-455b-aac5-795278fba97b)

Run:
```console
sct_register_multimodal -i sub-CTS05_ses-SPpost_T2w_crop_08iso.nii.gz -iseg sub-CTS05_ses-SPpost_T2w_deepseg_08iso.nii.gz -ilabel sub-CTS05_ses-SPpost_T2w_deepseg_labeled_commonverts_prepost.nii.gz -d sub-CTS05_ses-SPpre_T2w_crop_08iso.nii.gz -dseg sub-CTS05_ses-SPpre_T2w_deepseg_08iso.nii.gz -dlabel  sub-CTS05_ses-SPpre_T2w_deepseg_labeled_commonverts_prepost.nii.gz -param step=0,type=label,doi=Tx_Ty_Tz_Rx_Ry_Rz:step=1,type=seg,algo=slicereg:step=2,type=im,algo=centermassrot,rot_method=hog -qc qc
```

**Comment by joshuacwnewton** [comment]
> I think the issue is that centermassrot should take a segmentation as input, but the error is not "user friendly" and we should probably add a check that type=seg or type=imseg when used with algo=centermassrot. Unless the issue is elsewhere...

The error occurs in `register2d_centermassrot` on this line:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/fbd8f2de066767627d861ff98037f58db1181d8c/spinalcordtoolbox/registration/algorithms.py#L692-L694

`fname_dest` here refers to the `_seg` image, despite `type=seg`. Why?

Tracing the code up one level, we see that `fname_dest` is set here:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/fbd8f2de066767627d861ff98037f58db1181d8c/spinalcordtoolbox/registration/algorithms.py#L604-L615

Ah! It seems to be dependent on the `rot_method` -- for `type=im`, it seems like `rot_method` cannot be any of the HOG-based methods, leaving only `'pca'`.

So, I think if you replace `rot_method=hog` with `rot_method=pca`, it should work without error? But I agree that we should include a much clearer error message about this.

**Comment by jcohenadad** [comment]
right, but I _think_ the PCA method is designed to work only on binary segmentation (not image), so if that's the case we should probably add some checks for this as well

**Comment by joshuacwnewton** [comment]
> right, but I think the PCA method is designed to work only on binary segmentation (not image),

Ah! If that's the case, then the `else:` case (as shown above) should definitely be amended.

**Comment by jcohenadad** [comment]
> for type=im, it seems like rot_method cannot be any of the HOG-based methods.

that's also an inconsistency, I think, as the HOG method is supposed to be applied to the image, not the segmentation (needs to be verified)

**Comment by joshuacwnewton** [comment]
The code suggests that `hog` requires `type=imseg`? :thinking: 

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/fbd8f2de066767627d861ff98037f58db1181d8c/spinalcordtoolbox/registration/algorithms.py#L77

**Comment by jcohenadad** [comment]
right-- actually the main part of the method does rely on the image to find the symmetry, but it does indeed require the segmenter to get the centermass:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/fbd8f2de066767627d861ff98037f58db1181d8c/spinalcordtoolbox/registration/algorithms.py#L1484
