### ISSUE TITLE
`ValueError`: `module://matplotlib_inline.backend_inline is not a valid value` when running SCT scripts in Jupyter notbooks

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4523]
### Description

Using SCT within a Jupyter notebook I'm getting this error:

```console
👉 PROCESSING: sub-MGH

--
Spinal Cord Toolbox (git-master-bb479d82ea1e2076dd50343177056a61bd17e260)

sct_label_utils -i sub-MGH_acq-famp_TB1TFL.nii.gz -create 61,98,26,1 -o sub-MGH_acq-famp_TB1TFL_label.nii.gz
--

Generating output files...
File sub-MGH_acq-famp_TB1TFL_label.nii.gz already exists. Will overwrite it.

Done! To view results, type:
fsleyes sub-MGH_acq-famp_TB1TFL.nii.gz sub-MGH_acq-famp_TB1TFL_label.nii.gz &

Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_register_multimodal.py", line 34, in <module>
    from spinalcordtoolbox.reports import qc2
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/reports/qc2.py", line 389, in <module>
    def add_orientation_labels(ax: mpl_axes.Axes):
  File "/Users/julien/code/spinalcordtoolbox/contrib/tensorflow/lazy_loader.py", line 81, in __getattr__
    module = self._load()
  File "/Users/julien/code/spinalcordtoolbox/contrib/tensorflow/lazy_loader.py", line 64, in _load
    module = importlib.import_module(self.__name__)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/__init__.py", line 1270, in <module>
    rcParams['backend'] = os.environ.get('MPLBACKEND')
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/__init__.py", line 738, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
```

### Steps to Reproduce

Run [this notebook](https://github.com/spinal-cord-7t/coil-qc-code/pull/73/commits/be4cb3030d6fa9041263c4322c97ac0756790be2) with SCT bb479d82ea1e2076dd50343177056a61bd17e260

### Possible cause

It seems to be related to the LazyLoader. 

Next test: try the same notebook, with SCT _before_ the implementation of the LazyLoader.

Crossref: https://github.com/spinal-cord-7t/coil-qc-code/issues/74

**Comment by jcohenadad** [comment]
I tried to checkout an older version of SCT (I wanted to specifically checkout 6.3, but ran into #4524, so I ended up randomly picking 8f2b0e0eb956cbd12d1cabdfbee34e1ca8d99c34, which was _before_ the introduction of LazyImport):

I still observe an error, so in the end this issue is likely not related to the LazyImports:

<details><summary>Terminal output</summary>

```console
👉 PROCESSING: sub-MGH
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_label_utils.py", line 24, in <module>
    from spinalcordtoolbox.reports.qc import generate_qc
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 22, in <module>
    from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/__init__.py", line 1270, in <module>
    rcParams['backend'] = os.environ.get('MPLBACKEND')
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/__init__.py", line 738, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_register_multimodal.py", line 34, in <module>
    from spinalcordtoolbox.reports import qc2
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/reports/qc2.py", line 20, in <module>
    from matplotlib.axes import Axes
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/__init__.py", line 1270, in <module>
    rcParams['backend'] = os.environ.get('MPLBACKEND')
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/__init__.py", line 738, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
```

</details>

Next suspicion: the declaration of `%matplotlib inline` in the notebook.

**Comment by jcohenadad** [comment]
I removed the declaration `%matplotlib inline`, but I still get the same error.

**Comment by jcohenadad** [comment]
When I comment out this line, the notebook runs without error:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/86d5f8d5a473e5e034d365726a548d96776da755/spinalcordtoolbox/scripts/sct_register_multimodal.py#L34

Which suggests that one solution (probably not the best...) would consist in not running this line if QC report is not asked for.

**Comment by jcohenadad** [comment]
What I find strange, however, is how come we're only seeing this issue now... we've been using notebooks in other projects lately, and it included `sct_register_multimodal`, example [here](https://github.com/shimming-toolbox/rf-shimming-7t/blob/main/content/index.ipynb)

**Comment by jcohenadad** [comment]
Hum, it's getting weirder-- if I run another `sct_register_multimodal` syntax (with other data and parameters), there is no crash:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/7a154ef7-7d7a-45ec-a9b6-c196ee0eac39)

**Comment by jcohenadad** [comment]
re-starting the notebook, re-running the cells, now it works without crash... i don't understand.

**Comment by jcohenadad** [comment]
ok, crash is consistent:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/5e06d773-bd85-4761-b697-e92384a442b3)

**Comment by jcohenadad** [comment]
also consistent when running it in ANOTHER notebook (the rf-shimming one):

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/04e888bb-2345-454d-a223-7ef30d49a11e)

**Comment by joshuacwnewton** [comment]
Thank you for the detailed investigation! Taking a look now. :)

**Comment by joshuacwnewton** [comment]
Briefly looking at issues in other repos, I see a few things:

- `module://matplotlib_inline.backend_inline` [_should_ be a valid backend](https://github.com/holoviz/holoviews/issues/6226#issuecomment-2102609454).
- However, 2 other people are reporting this same error ([1](https://github.com/bmaltais/kohya_ss/issues/2521), [2](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/15866)), and their reports are relatively recent (18-19 days ago). This seems to suggest that this error may be due a recent change in `matplotlib`/`jupyter`/etc. (Though, it could just be a coincidence, too.)

----

I was able to reproduce the issue depending on the state of the SCT repo:

- If `matplotlib-inline` is installed in SCT's environment, there is no error.
- If `matplotlib-inline` is uninstalled, then the error is thrown:

```
Traceback (most recent call last):
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_register_multimodal.py", line 34, in <module>
    from spinalcordtoolbox.reports import qc2
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/reports/qc2.py", line 30, in <module>
    import matplotlib
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/__init__.py", line 1270, in <module>
    rcParams['backend'] = os.environ.get('MPLBACKEND')
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/__init__.py", line 738, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
```

I'm not 100% sure why you only encountered this error sporadically. Perhaps the "sporadic" part was due to the LazyLoading? But, nonetheless, we should be able to fix this by adding `matplotlib-inline` to SCT's `requirements.txt`.
