### ISSUE TITLE
Unexpected behaviours when using `append 1` depending on the existence of the file

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4552]
### Description

While working on https://github.com/sct-pipeline/spine-park/issues/44, I noticed that running `sct_extract_metric` on a particular dataset produced an error when the file does not exist, regardless the state of `-append`, and it outputs a file that is empty: [DWI_FA_32-33_bla5.csv](https://github.com/user-attachments/files/16073341/DWI_FA_32-33_bla5.csv)

However, when the flag `-append 1` and the CSV already exists, the function does not produce any error, but nothing is appended to the CSV file. 

<details><summary>Example of commands ran</summary>

```console
(base) p101317@joplin:~/lydia/results_20240702_140359/data_processed/sub-LD214/dwi$ sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33.csv -append 1

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33.csv -append 1
--


Load metric image...
Estimation for label: 32,33

Done! To view results, type:
xdg-open /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33.csv

(base) p101317@joplin:~/lydia/results_20240702_140359/data_processed/sub-LD214/dwi$ sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla.csv -append 1

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla.csv -append 1
--


Load metric image...
Estimation for label: 32,33
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_extract_metric.py", line 400, in <module>
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_extract_metric.py", line 393, in main
    save_as_csv(agg_metric, fname_output, fname_in=fname_data, append=append_csv)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/aggregate_slicewise.py", line 570, in save_as_csv
    agg_metric_key = [v for i, (k, v) in enumerate(agg_metric.items())][0]
IndexError: list index out of range
(base) p101317@joplin:~/lydia/results_20240702_140359/data_processed/sub-LD214/dwi$ sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33.csv -append 1

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33.csv -append 1
--


Load metric image...
Estimation for label: 32,33

Done! To view results, type:
xdg-open /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33.csv

(base) p101317@joplin:~/lydia/results_20240702_140359/data_processed/sub-LD214/dwi$ sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33.csv -append 1

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33.csv -append 1
--


Load metric image...
Estimation for label: 32,33

Done! To view results, type:
xdg-open /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33.csv

(base) p101317@joplin:~/lydia/results_20240702_140359/data_processed/sub-LD214/dwi$ sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla.csv -append 1

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla.csv -append 1
--


Load metric image...
Estimation for label: 32,33

Done! To view results, type:
xdg-open /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla.csv

(base) p101317@joplin:~/lydia/results_20240702_140359/data_processed/sub-LD214/dwi$ sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla2.csv -append 1

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla2.csv -append 1
--


Load metric image...
Estimation for label: 32,33
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_extract_metric.py", line 400, in <module>
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_extract_metric.py", line 393, in main
    save_as_csv(agg_metric, fname_output, fname_in=fname_data, append=append_csv)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/aggregate_slicewise.py", line 570, in save_as_csv
    agg_metric_key = [v for i, (k, v) in enumerate(agg_metric.items())][0]
IndexError: list index out of range
(base) p101317@joplin:~/lydia/results_20240702_140359/data_processed/sub-LD214/dwi$ sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla2.csv -append 1

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla2.csv -append 1
--


Load metric image...
Estimation for label: 32,33

Done! To view results, type:
xdg-open /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla2.csv

(base) p101317@joplin:~/lydia/results_20240702_140359/data_processed/sub-LD214/dwi$ sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla2.csv -append 1

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla2.csv -append 1
--


Load metric image...
Estimation for label: 32,33

Done! To view results, type:
xdg-open /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla2.csv

(base) p101317@joplin:~/lydia/results_20240702_140359/data_processed/sub-LD214/dwi$ sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla2.csv -append 1

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla2.csv -append 1
--


Load metric image...
Estimation for label: 32,33

Done! To view results, type:
xdg-open /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla2.csv

(base) p101317@joplin:~/lydia/results_20240702_140359/data_processed/sub-LD214/dwi$ sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla2.csv -append 1

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla2.csv -append 1
--


Load metric image...
Estimation for label: 32,33

Done! To view results, type:
xdg-open /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla2.csv

(base) p101317@joplin:~/lydia/results_20240702_140359/data_processed/sub-LD214/dwi$ sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla3.csv -append 1

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla3.csv -append 1
--


Load metric image...
Estimation for label: 32,33
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_extract_metric.py", line 400, in <module>
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_extract_metric.py", line 393, in main
    save_as_csv(agg_metric, fname_output, fname_in=fname_data, append=append_csv)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/aggregate_slicewise.py", line 570, in save_as_csv
    agg_metric_key = [v for i, (k, v) in enumerate(agg_metric.items())][0]
IndexError: list index out of range
(base) p101317@joplin:~/lydia/results_20240702_140359/data_processed/sub-LD214/dwi$ sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla3.csv -append 1

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla3.csv -append 1
--


Load metric image...
Estimation for label: 32,33

Done! To view results, type:
xdg-open /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla3.csv

(base) p101317@joplin:~/lydia/results_20240702_140359/data_processed/sub-LD214/dwi$ sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla4.csv -append 0

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla4.csv -append 0
--


Load metric image...
Estimation for label: 32,33
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_extract_metric.py", line 400, in <module>
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_extract_metric.py", line 393, in main
    save_as_csv(agg_metric, fname_output, fname_in=fname_data, append=append_csv)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/aggregate_slicewise.py", line 570, in save_as_csv
    agg_metric_key = [v for i, (k, v) in enumerate(agg_metric.items())][0]
IndexError: list index out of range
(base) p101317@joplin:~/lydia/results_20240702_140359/data_processed/sub-LD214/dwi$ sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla5.csv -append 0

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33_bla5.csv -append 0
--


Load metric image...
Estimation for label: 32,33
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_extract_metric.py", line 400, in <module>
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_extract_metric.py", line 393, in main
    save_as_csv(agg_metric, fname_output, fname_in=fname_data, append=append_csv)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/aggregate_slicewise.py", line 570, in save_as_csv
    agg_metric_key = [v for i, (k, v) in enumerate(agg_metric.items())][0]
IndexError: list index out of range
(base) p101317@joplin:~/lydia/results_20240702_140359/data_processed/sub-LD214/dwi$ sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33.csv -append 1

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_extract_metric -i sub-LD214_chunk-1_DWI_moco_FA.nii.gz -f label_sub-LD214_chunk-1_DWI_moco/atlas -l 32,33 -combine 1 -vert 2:12 -vertfile label_sub-LD214_chunk-1_DWI_moco/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33.csv -append 1
--


Load metric image...
Estimation for label: 32,33

Done! To view results, type:
xdg-open /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240702_140359/results/DWI_FA_32-33.csv
```

</details>

### Steps to Reproduce

CSV file to append results on: [DWI_FA_32-33.csv](https://github.com/user-attachments/files/16073364/DWI_FA_32-33.csv)

Data: [data_issueSCT.zip](https://github.com/user-attachments/files/16073454/data_issueSCT.zip)

**Comment by joshuacwnewton** [comment]
I am able to reproduce the behavior described above.

For the error that occurs with a new .csv file:

```
Traceback (most recent call last):
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/aggregate_slicewise.py", line 570, in save_as_csv
    agg_metric_key = [v for i, (k, v) in enumerate(agg_metric.items())][0]
IndexError: list index out of range
```

This occurs here:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a7a3f8dd021b6b7f8d2b9fa2680002ed4b1c5f2c/spinalcordtoolbox/aggregate_slicewise.py#L564-L570

Setting a breakpoint shows that `agg_metric` is actually completely empty, meaning that when we try to access `[0]` we get an `IndexError`.

The reason that `agg_metric` is empty in the first place is because the `PAM50_levels.nii.gz` and `PAM50_atlas` files are all empty. (Perhaps the registration failed for this subject?)

We should definitely improve the error message when no metrics can be extracted.
