### ISSUE TITLE
model c2c3_disc_models/t2_model.yml does not exist

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4569]
### Description

I ran a processing involving `sct_label_vertebrae`, and ended up with the following bug, because of a model that is not installed:

```console
Spinal Cord Toolbox (git-master-3a8c0a7bccf27e486512aa85e6d3fd3c7dbe4d75*)

sct_label_vertebrae -i sub-DEV208Sujet11_T2.nii.gz -s sub-DEV208Sujet11_T2_seg.nii.gz -c t2 -qc /Users/julien/temp/Lydia/results_20240722_124744/qc -qc-subject sub-DEV208Sujet11
--

Creating temporary folder (/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-07-22_12-48-47_label-vertebrae_yf91fltc)

Copying input data to tmp folder...

Straighten spinal cord...
Creating temporary folder (/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-07-22_12-48-47_straighten-spinalcord_ddyjdtbm)
Copy files to tmp folder...
Fitting centerline using B-spline approximation
Error on approximation = 4.51 mm
Error on approximation = 2.74 mm
Error on approximation = 1.58 mm
Error on approximation = 0.92 mm
Error on approximation = 0.49 mm
Error on approximation = 0.26 mm
Error on approximation = 0.18 mm
Error on approximation = 0.13 mm
Error on approximation = 0.1 mm
Error on approximation = 0.07 mm
Error on approximation = 0.06 mm
Error on approximation = 0.05 mm
Error on approximation = 0.04 mm
Error on approximation = 0.04 mm
Create the straight space and the safe zone
Length of spinal cord: 184.0646676421619
Size of spinal cord in z direction: 176.4558308574841
Ratio length/size: 1.0431203477249962
Safe zone boundaries (curved space): [-98.02005958236063, 78.43577127512347]
Safe zone boundaries (straight space): [-101.82447797469955, 82.24018966746239]
Pad input volume to account for spinal cord length...
Time to generate centerline: 16.0 ms
[33mImage header specifies datatype 'float32', but array is of type 'float64'. Header metadata will be overwritten to use 'float64'.[0m
Warping field generated: tmp.curve2straight.nii.gz
[33mImage header specifies datatype 'float32', but array is of type 'float64'. Header metadata will be overwritten to use 'float64'.[0m
Warping field generated: tmp.straight2curve.nii.gz
Apply transformation to input image...
/Users/julien/code/spinalcordtoolbox/bin/isct_antsApplyTransforms -d 3 -i data.nii -o tmp.anat_rigid_warp.nii.gz -t tmp.curve2straight.nii.gz -r tmp.centerline_pad_crop.nii.gz -n 'BSpline[3]' # in /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-07-22_12-48-47_straighten-spinalcord_ddyjdtbm
Generate output files...
mv /var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-07-22_12-48-47_straighten-spinalcord_ddyjdtbm/tmp.curve2straight.nii.gz ./warp_curve2straight.nii.gz
File created: ./warp_curve2straight.nii.gz
mv /var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-07-22_12-48-47_straighten-spinalcord_ddyjdtbm/tmp.straight2curve.nii.gz ./warp_straight2curve.nii.gz
File created: ./warp_straight2curve.nii.gz
cp /var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-07-22_12-48-47_straighten-spinalcord_ddyjdtbm/tmp.anat_rigid_warp.nii.gz ./straight_ref.nii.gz
File created: ./data_straight.nii
Remove temporary files...
rm -rf /var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-07-22_12-48-47_straighten-spinalcord_ddyjdtbm

Resample to 0.5mm isotropic...
load data...

Apply straightening to segmentation...
/Users/julien/code/spinalcordtoolbox/bin/isct_antsApplyTransforms -d 3 -i segmentation.nii -o segmentation_straight.nii -t warp_curve2straight.nii.gz -r data_straightr.nii -n Linear # in /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-07-22_12-48-47_label-vertebrae_yf91fltc
[33mFile /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-07-22_12-48-47_label-vertebrae_yf91fltc/segmentation_straight.nii already exists. Will overwrite it.[0m

Create label to identify disc...
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 501, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 384, in main
    im_label_c2c3 = detect_c2c3(im_data, im_seg, contrast, verbose=verbose_detect_c2c3)
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/vertebrae/detect_c2c3.py", line 52, in detect_c2c3
    raise FileNotFoundError(
FileNotFoundError: The model file /Users/julien/code/spinalcordtoolbox/data/c2c3_disc_models/t2_model.yml does not exist. Please download it using sct_download_data
```

weirdly, the model is not available:
```
sct_download_data 
--

usage: sct_download_data -d <dataset> [-h] [-o <folder>] [-k] [-v <int>]

Download binaries from the web.

MANDATORY ARGUMENTS:
  -d <dataset>  Name of the dataset, as listed in the table below. If 'default' is specified, then all default datasets will be re-downloaded. (Default datasets
                are critical datasets downloaded during installation.)

OPTIONAL ARGUMENTS:
  -h, --help    Show this help message and exit.
  -o <folder>   Path to a directory to save the downloaded data.
                (If not provided, the dataset will be downloaded to the SCT installation directory by default. Directory will be created if it does not exist.
                Warning: existing data in the directory will be erased unless -k is provided.)
  -k            Keep existing data in destination directory. (default: False)
  -v <int>      Verbosity. 0: Display only errors/warnings, 1: Errors/warnings + info messages, 2: Debug mode (default: 1)

DATASET NAME                  TYPE
--------------------------------------------------
binaries_linux                Binaries
binaries_osx                  Binaries
binaries_win                  Binaries
sct_example_data              Datasets
sct_testing_data              Datasets
deepreg_models                Models
deepseg_gm_models             Models
deepseg_lesion_models         Models
deepseg_sc_models             Models
manual-correction             SCT Course Files
sct_course_data               SCT Course Files
MNI-Poly-AMU                  Templates
PAM50                         Templates
PAM50_normalized_metrics      Templates
exvivo_template               Templates

Legend: installed | not installed (in the $SCT_DIR/data folder)
```

and indeed, not listed [here](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/9cd5700c7e05baf7ebd5fd56e74e8779029f528f/spinalcordtoolbox/download.py) either

I suspect this issue came up because I probably did some weird stuff to my SCT install (I will do a fresh reinstall to see if it solves it), but in any case, there are some inconsistencies here (ie: asking to install a model that does not exist)

**Comment by jcohenadad** [comment]
Just tracing back stuff. The model is used here:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/9cd5700c7e05baf7ebd5fd56e74e8779029f528f/spinalcordtoolbox/vertebrae/detect_c2c3.py#L49C46-L49C62

**Comment by jcohenadad** [comment]
Not an issue, so we can close this
