### ISSUE TITLE
Clarify steps for installing SCT onto ComputeCanada Graham (`requirements.txt` conflicts)

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#4593]
### Description

I am trying to install sct v6.3 on compute canada graham. I had install in the past v5.1 without any trouble, by I am now running into problems with the python packages, I attached the log file.

[install_sct_log.txt](https://github.com/user-attachments/files/16512585/install_sct_log.txt)

**Comment by mguaypaq** [comment]
I see a warning message about the `PYTHONPATH` environment variable. Possibly related, it looks like `pip` is searching for dependencies in the following custom paths, rather than from PyPI:
```
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo2023/x86-64-v3, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo2023/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
```

It looks like Conda (which we use in the installation script) is explicitly forbidden by Compute Canada: https://docs.alliancecan.ca/wiki/Anaconda/en

There may be information about how to correctly install a virtual environment with the necessary dependencies here: https://docs.alliancecan.ca/wiki/Python

(Since I don't have a Yubikey and MFA is now required for Compute Canada, I can't test myself, sorry.)

**Comment by sandrinebedard** [comment]
Update on the installation:

Here are the packages that are not available:
<details>
  <summary>`(venv_sct) [sabeda@gra-login1 ~]$ avail_wheels -r sct_6.3/requirements.txt --not-available`</summary>

~~~

name                    version    python    arch
----------------------  ---------  --------  -------
dipy                    1.5.0      cp39      generic
ivadomed                2.9.8      py3       generic
matplotlib              3.7.2      cp39      avx2
monai                   1.3.0      py3       generic
msvc_runtime
nibabel                 5.2.1      py3       generic
nilearn                 0.10.1     py3       generic
nnunetv2                2.1        py3       generic
numpy                   1.25.2     cp39      generic
onnxruntime             1.14.1     cp39      generic
pandas                  2.1.0      cp39      avx2
portalocker             2.10.1     py3       generic
psutil                  5.9.8      cp39      generic
pyqt5
pyqt5_sip
pystrum
pytest                  8.2.2      py3       generic
pytest_console_scripts  1.3.1      py3       generic
pytest_cov              5.0.0      py3       generic
PyYAML                  6.0.1      cp39      avx2
requests                2.31.0     py3       generic
requirements_parser     0.5.0      py3       generic
scikit_image            0.22.0     cp39      avx2
scikit_learn            1.3.0      cp39      generic
scipy                   1.11.2     cp39      generic
tqdm                    4.66.5     py3       generic
transforms3d            0.3.1      py3       generic
urllib3                 2.1.0      py3       generic
voxelmorph              0.2        py3       generic
wquantiles              0.6        py3       generic
XlsxWriter              3.2.0      py3       generic
xlwt                    1.3.0      py2,py3   generic
~~~
</details>

When running `pip install --no-index -r sct_6.3/requirements.txt`
~~~
ERROR: Cannot install -r sct_6.3/requirements_cc.txt (line 10) and -r sct_6.3/requirements_cc.txt (line 23) because these package versions have conflicting dependencies.

The conflict is caused by:
    nnunetv2 2.1+computecanada depends on torch>1.12
    ivadomed 2.9.8+computecanada depends on torch<=1.11.0 and >=1.8.1
~~~

I commented out `ivadomed `since I will only be using `monai `model for my project.

Installation of requirements is now completed.

I ran manually the rest of sct installation steps.

I now have a problem with the `transforms3d `library and `numpy`:

~~~
(venv_sct) [sabeda@gra-login1 ~]$ sct_deepseg
Traceback (most recent call last):
  File "/home/sabeda/sct_6.3/spinalcordtoolbox/scripts/sct_deepseg.py", line 22, in <module>
    from spinalcordtoolbox.reports import qc2
  File "/home/sabeda/sct_6.3/spinalcordtoolbox/reports/qc2.py", line 27, in <module>
    from spinalcordtoolbox.image import Image
  File "/home/sabeda/sct_6.3/spinalcordtoolbox/image.py", line 25, in <module>
    import transforms3d.affines as affines
  File "/home/sabeda/venv_sct/lib/python3.9/site-packages/transforms3d/__init__.py", line 10, in <module>
    from . import quaternions
  File "/home/sabeda/venv_sct/lib/python3.9/site-packages/transforms3d/quaternions.py", line 26, in <module>
    _MAX_FLOAT = np.maximum_sctype(np.float)
  File "/home/sabeda/venv_sct/lib/python3.9/site-packages/numpy/__init__.py", line 319, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
 ~~~
 
 
 This is my numpy version:
~~~
(venv_sct) [sabeda@gra-login1 ~]$ pip list | grep numpy
numpy                         1.25.2+computecanada
~~~
This is my transforms3d version
~~~
(venv_sct) [sabeda@gra-login1 ~]$ pip list | grep transforms3d
transforms3d                  0.3.1+computecanada
~~~

However, in requirements-freeze.txt, the version is :

~~~
transforms3d==0.4.1
~~~

I am not sure how to fix this

**Comment by sandrinebedard** [comment]
Next steps, install packages from the web since not available on compute canada:

~~~
pip install transforms3d==0.4.1
pip install pystrum==0.4
~~~

**Comment by joshuacwnewton** [comment]
> I am not sure how to fix this

Given that the error is just a mismatch with `transforms3d`'s call to the numpy Python API, I assume resolving the error should be somewhat straightforward (downgrading numpy or upgrading transforms3d)?

Perhaps we can reach out to CC about the fact that they have an outdated version of `transforms3d` that is incompatible with newer versions of `numpy`... :thinking:

**Comment by mguaypaq** [comment]
Update: after some in-person debugging yesterday afternoon, Sandrine was able to install enough of the dependencies to run the SCT commands she needs on Compute Canada. But it was a struggle!

If we expect that people will regularly want to use SCT on Compute Canada, we may want to invest some time in making a custom installer and/or activation script for that case. This might even require changes to SCT itself. But if it's not a priority, at least we have this issue as documentation for a starting point.

**Comment by joshuacwnewton** [comment]
I've updated the title of this issue just to indicate that this is more of a documentation issue than a bug?

Also, just to try to summarize the core of the issue, my understanding here is that:

- Stable releases (e.g. SCT v6.3) specify an extremely strict set of requirements (`requirements-freeze.txt`)
- However, the available Python wheels built specifically for ComputeCanada's infrastructure are much more limited (and sometimes not available at all), and so a more open set of requirements are needed.
- However, by opening the requirements, we open ourselves up to untested, potentially buggy combinations of requirements (especially since frozen stable releases of SCT are only tested with dependencies that were available at the time of release).

If this is accurate, then even with a dedicated install script targeted at CC, we would still have to regularly test our dependencies against the versions available from CC (and reconcile any version conflicts). In other words, this seems more like something we'd have to change with our development processes first and foremost? :thinking:

**Comment by mguaypaq** [comment]
> * However, the available Python wheels built specifically for ComputeCanada's infrastructure are much more limited (and sometimes not available at all), and so a more open set of requirements are needed.

It's mostly the Python packages which contain binaries or link against external C libraries (or similar) that are the problem. (I'll call these "compiled packages" for short.) I think we don't currently differentiate between them in SCT, but it would be helpful to differentiate between (and document):
- Which dependencies are compiled packages. (For these, we pretty much have to hope that Compute Canada provides them, or submit a support request, including the specific version.)
- Which dependencies ultimately depend on compiled packages. (For these, we have to make sure Compute Canada provides any compiled packages in their dependency tree, like the previous point.)
- Which dependencies are pure Python packages. (For these, we can install them directly from PyPI, no problem.)

> * However, by opening the requirements, we open ourselves up to untested, potentially buggy combinations of requirements (especially since frozen stable releases of SCT are only tested with dependencies that were available at the time of release).
>   * This is exacerbated by the fact that we rely on medical imaging Python packages that don't necessarily keep up with upstream deprecations as fast as we'd prefer. So, numpy/matplotlib/etc. may update faster than nnuntv2/transforms3d/etc. can keep up with, leading to further conflicts stemming from untested dependency combinations.

Yes. In particular, `numpy` is pretty fast at deprecating and then completely removing various things that get commonly imported. Thankfully, Compute Canada seems to provide several versions of `numpy` to choose from. (In Sandrine's case, I think selectively upgrading _other_ dependencies from Compute Canada's old provided version to something closer to SCT's requested version was the solution.)

> If this is accurate, then even with a dedicated install script targeted at CC, we would still have to regularly test our dependencies against the versions available from CC (and reconcile any version conflicts). In other words, this seems more like something we'd have to change with our development processes first and foremost? 🤔

Yes. Possibly such a custom install script targeted at CC would live in Neuropoly's lab documentation, instead of in the SCT repo. I don't think SCT has any hope of doing automated testing of this environment.

But this might require other deep changes:
- Our default installation scripts really rely on `conda` for providing a specific Python version, but that's not really allowed on CC. If this step was somehow more modular, it would be easier to run the other steps on CC.
- We might want to split `requirements.txt` into a few files for different categories of dependencies (which ones have more flexible versions, which are compiled packages, etc.) so that it's easier to run `pip install` with only a subset of them.
- It's not clear to me where the `isct_*` compiled binaries that we distribute actually come from. In the case of ANTs, CC actually provides binaries, so the ideal thing to do on CC would be to replace those four `isct_*` binaries with symlinks to the system-provided ones. But for the other binaries, I don't even know how to check whether CC provides a version.
- In Sandrine's case, she only needed to run a specific MONAI model, so it was OK that we couldn't install `ivadomed` (seems hard) and `nnunetv2` (seems provided by CC, but still didn't seem to work easily). But that means she had to manually comment out some import lines in the SCT source code. It might take some reorganization, but it would have been nice if some of these trickier dependencies were really optional.

All of this might be a lot of work for not much payoff. But for some of these, it might nudge us towards a cleaner architecture for SCT, or a better separation of concerns in our packaging.

**Comment by jcohenadad** [comment]
how about using singularity containers with SCT installed?

**Comment by mguaypaq** [comment]
I think using containers wouldn't really help, here. The reason Compute Canada doesn't want us to install Conda, and the reason they provide some custom-compiled Python packages, is that they've optimized some of the widely-used C libraries for their specific CPU+GPU architecture. Installing standard pre-compiled things inside a container would have the same result as installing them outside a container: we'd be wasting a lot of space and running inefficient code on the Compute Canada clusters.

**Comment by mguaypaq** [comment]
But, if we want a more standard environment, with GPUs, inside Compute Canada, would could probably use their [cloud GPUs](https://docs.alliancecan.ca/wiki/Using_cloud_GPUs): instead of running our code on one of CC's existing HPC clusters, we'd be running it on a freshly installed VM in CC's cloud environment, where we can install whatever software we want. We might have to expand or re-balance our allocation under def-jcohen first.

**Comment by SomeoneInParticular** [comment]
Necro-posting a bit to discuss this:

> I think using containers wouldn't really help, here. The reason Compute Canada doesn't want us to install Conda, and the reason they provide some custom-compiled Python packages, is that they've optimized some of the widely-used C libraries for their specific CPU+GPU architecture. Installing standard pre-compiled things inside a container would have the same result as installing them outside a container: we'd be wasting a lot of space and running inefficient code on the Compute Canada clusters.

I 100% agree; however, it seems ~~Compute Canada~~ Alliance Canada are hypocrites in this regard, and explicitly support containerized code. They have even provided [documentation on how to do it](https://docs.alliancecan.ca/wiki/Apptainer). 

So, until they have decided on a consistent stance on the matter, I'm going to argue we just do what works best for us outside of Compute Canada, and work around whatever they decide will work this month as it comes up. If nothing else, evaluating how well SCT runs in a container is probably worth investigating anyways as some users may want to do that for their own purposes.

**Comment by jcohenadad** [comment]
@sandrinebedard just to follow up on this issue: in the end, were you able to properly install (and use) SCT?

**Comment by sandrinebedard** [comment]
> [@sandrinebedard](https://github.com/sandrinebedard) just to follow up on this issue: in the end, were you able to properly install (and use) SCT?

I was partially able, but by removing some dependencies  and manually selecting some packages as detailed in the issue before, I was using SCTv6.3, here is my `sct_check_dependencies`:


<details>

<summary>sct_check_dependencies</summary>
```

[sabeda@gra-login2 ~]$ sct_check_dependencies

--
Spinal Cord Toolbox (6.3)

sct_check_dependencies 
--


SYSTEM INFORMATION
------------------
SCT info:
- version: 6.3
- path: /home/sabeda/sct_6.3
OS: linux (Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-Intel-R-_Xeon-R-_CPU_E5-2667_v4_@_3.20GHz-with-glibc2.30)
CPU cores: Available: 32, Used by ITK functions: 32
RAM: Total: 515611MB, Used: 21883MB, Available: 468669MB

OPTIONAL DEPENDENCIES
---------------------
Check FSLeyes version...............................[  ]
   (127, '/bin/sh: fsleyes : commande introuvable')
Check if CUDA is available in PyTorch...............[FAIL] (torch.cuda.is_available() returned False)

MANDATORY DEPENDENCIES
----------------------
Check Python executable.............................[WARNING]
  Using system python which is unsupported: /home/sabeda/venv_sct/bin/python
Check if data are installed.........................[OK]
Check if dipy is installed..........................[OK] (1.7.0)
Check if ivadomed is installed......................[FAIL]
An error occured while importing module ivadomed -> No module named 'ivadomed'
Full traceback: Traceback (most recent call last):
  File "/home/sabeda/sct_6.3/spinalcordtoolbox/scripts/sct_check_dependencies.py", line 362, in main
    module = module_import(module_name, suppress_stderr)
  File "/home/sabeda/sct_6.3/spinalcordtoolbox/scripts/sct_check_dependencies.py", line 102, in module_import
    module = importlib.import_module(module_name)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.9.6/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ivadomed'

Check if matplotlib is installed....................[OK] (3.7.2)
Check if monai is installed.........................[OK] (1.3.0)
Check if nibabel is installed.......................[OK] (5.2.1)
Check if nilearn is installed.......................[OK] (0.10.1)
Check if nnunetv2 is installed......................[OK]
Check if numpy is installed.........................[OK] (1.25.2)
Check if onnxruntime is installed...................[OK] (1.14.1)
Check if pandas is installed........................[OK] (2.1.0)
Check if portalocker is installed...................[OK] (2.10.1)
Check if psutil is installed........................[OK] (5.9.8)
Check if pyqt5 (5.12.3) is installed................[WARNING] (5.15.1 != 5.12.3 mandated version))
Check if pyqt5-sip is installed.....................[OK]
Check if pystrum is installed.......................[OK] (0.4)
Check if pytest is installed........................[OK] (8.2.2)
Check if pytest-cov is installed....................[OK] (5.0.0)
Check if requests is installed......................[OK] (2.31.0)
Check if requirements-parser is installed...........[OK]
Check if scipy is installed.........................[OK] (1.11.2)
Check if scikit-image is installed..................[OK] (0.22.0)
Check if scikit-learn is installed..................[OK] (1.3.0)
Check if xlwt is installed..........................[OK] (1.3.0)
Check if tqdm is installed..........................[OK] (4.66.5)
Check if transforms3d is installed..................[OK] (0.4.1)
Check if urllib3 is installed.......................[OK] (2.1.0)
Check if pytest_console_scripts is installed........[OK]
Check if pyyaml is installed........................[OK] (6.0.1)
Check if voxelmorph is installed....................[OK] (0.2)
Check if wquantiles is installed....................[OK] (0.4)
Check if xlsxwriter is installed....................[OK] (3.2.0)
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if figure can be opened with PyQt.............[FAIL] ($DISPLAY not set on X11-supporting system)
Check if figure can be opened with matplotlib.......[FAIL] (Using non-GUI backend 'agg')
```
</details>

**Comment by SomeoneInParticular** [comment]
PR #4857 has a draft implementation of this now; I tested and confirmed it works on Calgary's HPC, just waiting to get 2FA set up for Alliance Canada to confirm it works there too.
