### ISSUE TITLE
`sct_deepseg seg_sc_contrast_agnostic` fails when using `SCT_USE_GPU=1`

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4633]
## Description

When running the contrast-agnostic model as part of SCT v6.4 on GPU using `CUDA_VISIBLE_DEVICES=1 SCT_USE_GPU=1` (see our [wiki](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Contributing%3A-Installing-SCT-for-GPU)) on `romane`:

```
CUDA_VISIBLE_DEVICES=1 SCT_USE_GPU=1 sct_deepseg -i ${file_t2}.nii.gz -task seg_sc_contrast_agnostic -qc ${PATH_QC} -qc-subject ${SUBJECT}
```

I get `monai.utils.module.OptionalImportError: import cupy (No module named 'cupy').` error.

<details><summary>full error output</summary>

```
+ CUDA_VISIBLE_DEVICES=1
+ SCT_USE_GPU=1
+ sct_deepseg -i sub-zh02_ses-01_acq-sag_T2w.nii.gz -task seg_sc_contrast_agnostic -qc /home/GRAMES.POLYMTL.CA/p118175/results/sci-zurich_midsagittal_measures_2024-09-20/qc -qc-subject sub-zh02/ses-01

--
Spinal Cord Toolbox (git-master-197ef3494a1c73d8b8acb14fcd809f31e16b5265)

sct_deepseg -i sub-zh02_ses-01_acq-sag_T2w.nii.gz -task seg_sc_contrast_agnostic -qc /home/GRAMES.POLYMTL.CA/p118175/results/sci-zurich_midsagittal_measures_2024-09-20/qc -qc-subject sub-zh02/ses-01
--

Model 'model_seg_sc_contrast_agnostic_softseg_monai' is up to date (Source: https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/download/v2.4/model_soft_bin_20240425-170840.zip)
/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/deepseg/monai.py:119: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(chkp_path, map_location=torch.device(device))["state_dict"]
Creating temporary folder (/tmp/sct_2024-09-20_11-38-38_sct_deepseg_k2zjti0c)
Copied sub-zh02_ses-01_acq-sag_T2w.nii.gz to /tmp/sct_2024-09-20_11-38-38_sct_deepseg_k2zjti0c/sub-zh02_ses-01_acq-sag_T2w.nii.gz
Starting inference...
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/spatial/dictionary.py", line 527, in inverse
    d[key] = self.spacing_transform.inverse(cast(torch.Tensor, d[key]))
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/spatial/array.py", line 543, in inverse
    return self.sp_resample.inverse(data)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/spatial/array.py", line 248, in inverse
    out: torch.Tensor = SpatialResample.__call__(self, data, **kw_args)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/spatial/array.py", line 223, in __call__
    return spatial_resample(
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/spatial/functional.py", line 172, in spatial_resample
    img = affine_xform(img, mode=mode, padding_mode=padding_mode)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/spatial/array.py", line 2265, in __call__
    return affine_func(  # type: ignore
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/spatial/functional.py", line 607, in affine_func
    out = resampler(img=img, grid=grid, mode=mode, padding_mode=padding_mode)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/spatial/array.py", line 2091, in __call__
    img_np = (convert_to_cupy if is_cuda else convert_to_numpy)(img_t, wrap_sequence=True)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/utils/type_conversion.py", line 246, in convert_to_cupy
    data = cp.asarray(data, dtype)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/utils/module.py", line 441, in __getattr__
    raise self._exception
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/utils/module.py", line 399, in optional_import
    pkg = __import__(module)  # top level module
monai.utils.module.OptionalImportError: import cupy (No module named 'cupy').

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/post/dictionary.py", line 715, in __call__
    inverted = self.transform.inverse(input_dict)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/compose.py", line 364, in inverse
    data = apply_transform(
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <bound method Spacingd.inverse of <monai.transforms.spatial.dictionary.Spacingd object at 0x7a725c52a7f0>>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 396, in <module>
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 305, in main
    im_lst, target_lst = inference.segment_non_ivadomed(path_model, model_type, input_filenames, thr,
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/deepseg/inference.py", line 127, in segment_non_ivadomed
    fnames_out, targets = inference(path_img=fname_in, tmpdir=tmpdir, predictor=net, device=device)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/deepseg/inference.py", line 187, in segment_monai
    pred = ds_monai.postprocessing(batch, test_post_pred)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/deepseg/monai.py", line 193, in postprocessing
    post_test_out = [test_post_pred(i) for i in decollate_batch(batch)]
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/deepseg/monai.py", line 193, in <listcomp>
    post_test_out = [test_post_pred(i) for i in decollate_batch(batch)]
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/compose.py", line 335, in __call__
    result = execute_compose(
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/compose.py", line 111, in execute_compose
    data = apply_transform(
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.post.dictionary.Invertd object at 0x7a725c52a580>
```

</details>

Just for contest, SCIsegV2 nnUNet model works fine (compare [L94](https://github.com/ivadomed/model_seg_sci/blob/02e93215cfdfc6450bfa709e9a5c1cc2451f5996/midsagittal_measures/01_compute_midsagittal_lesion_length_and_width.sh#L94) vs [L121](https://github.com/ivadomed/model_seg_sci/blob/02e93215cfdfc6450bfa709e9a5c1cc2451f5996/midsagittal_measures/01_compute_midsagittal_lesion_length_and_width.sh#L121C1-L121C139)).

**Comment by joshuacwnewton** [comment]
Thank you for reporting this! I'll take a look asap :)

**Comment by valosekj** [comment]
> Just as a quick test though, could you try pip install cupy?

Sure, tried but finished with the `ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cupy)` error.
 
<details><summary>full error</summary>

```console
$source ${SCT_DIR}/python/etc/profile.d/conda.sh
$ conda activate venv_sct
$ pip install cupy
Collecting cupy
  Downloading cupy-13.3.0.tar.gz (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 117.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy<2.3,>=1.22 in /home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages (from cupy) (1.26.4)
Collecting fastrlock>=0.5 (from cupy)
  Downloading fastrlock-0.8.2-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_28_x86_64.whl.metadata (9.3 kB)
Downloading fastrlock-0.8.2-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_28_x86_64.whl (52 kB)
Building wheels for collected packages: cupy
  Building wheel for cupy (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [107 lines of output]
      Generating cache key from header files...
      Cache key (1610 files matching /tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/cupy/_core/include/**): 64f57b4d98ad6db4a9b8163e38feec0d69e83795
      Clearing directory: /tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/cupy/.data

      -------- Configuring Module: cuda --------

      -------- Configuring Module: cusolver --------

      -------- Configuring Module: cudnn --------

      -------- Configuring Module: nccl --------
      /tmp/tmpnrq3fc7h/a.cpp:1:10: fatal error: nccl.h: No such file or directory
          1 | #include <nccl.h>
            |          ^~~~~~~~
      compilation terminated.
      command '/usr/bin/gcc' failed with exit code 1

      -------- Configuring Module: nvtx --------

      -------- Configuring Module: cutensor --------
      /tmp/tmpstuzc3n1/a.cpp:1:10: fatal error: cutensor.h: No such file or directory
          1 | #include <cutensor.h>
            |          ^~~~~~~~~~~~
      compilation terminated.
      command '/usr/bin/gcc' failed with exit code 1

      -------- Configuring Module: cub --------

      -------- Configuring Module: jitify --------
      **************************************************
      *** WARNING: Cannot determine Jitify version
      [Errno 2] No such file or directory: '/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/third_party/jitify'
      **************************************************

      -------- Configuring Module: random --------

      -------- Configuring Module: thrust --------

      -------- Configuring Module: cusparselt --------
      /tmp/tmpgfbzclpp/a.cpp:1:10: fatal error: cusparseLt.h: No such file or directory
          1 | #include <cusparseLt.h>
            |          ^~~~~~~~~~~~~~
      compilation terminated.
      command '/usr/bin/gcc' failed with exit code 1

      -------- Configuring Module: dlpack --------

      ************************************************************
      * CuPy Configuration Summary                               *
      ************************************************************

      Build Environment:
        Include directories: ['/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/cupy/_core/include/cupy/_cccl/libcudacxx', '/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/cupy/_core/include/cupy/_cccl/thrust', '/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/cupy/_core/include/cupy/_cccl/cub', '/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/cupy/_core/include', '/usr/include']
        Library directories: ['/usr/lib64', '/usr/lib']
        nvcc command       : ['/usr/bin/nvcc']
        hipcc command      : (not found)

      Environment Variables:
        CFLAGS          : (none)
        LDFLAGS         : (none)
        LIBRARY_PATH    : (none)
        CUDA_PATH       : (none)
        NVCC            : (none)
        HIPCC           : (none)
        ROCM_HOME       : (none)

      Modules:
        cuda      : Yes (version 12000)
        cusolver  : Yes
        cudnn     : Yes (version 8902)
        nccl      : No
          -> Include files not found: ['nccl.h']
          -> Check your CFLAGS environment variable.
        nvtx      : Yes
        cutensor  : No
          -> Include files not found: ['cutensor.h']
          -> Check your CFLAGS environment variable.
        cub       : Yes (version 200600)
        jitify    : Yes (version <unknown>)
        random    : Yes
        thrust    : Yes (version 200600)
        cusparselt: No
          -> Include files not found: ['cusparseLt.h']
          -> Check your CFLAGS environment variable.
        dlpack    : Yes

      WARNING: Some modules could not be configured.
      CuPy will be installed without these modules.
      Please refer to the Installation Guide for details:
      https://docs.cupy.dev/en/stable/install.html

      ************************************************************

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/setup.py", line 95, in <module>
          ext_modules = cupy_setup_build.get_ext_modules(True, ctx)
        File "/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/install/cupy_builder/cupy_setup_build.py", line 514, in get_ext_modules
          extensions = make_extensions(ctx, compiler, use_cython)
        File "/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/install/cupy_builder/cupy_setup_build.py", line 378, in make_extensions
          s['extra_objects'] = [
        File "/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/install/cupy_builder/cupy_setup_build.py", line 379, in <listcomp>
          _find_static_library(name) for name in module.static_libraries
        File "/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/install/cupy_builder/cupy_setup_build.py", line 289, in _find_static_library
          raise Exception(f'Could not find {filename}: {path} does not exist')
      Exception: Could not find libcudart_static.a: /usr/lib/libcudart_static.a does not exist
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cupy
  Running setup.py clean for cupy
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [107 lines of output]
      Generating cache key from header files...
      Cache key (1610 files matching /tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/cupy/_core/include/**): 64f57b4d98ad6db4a9b8163e38feec0d69e83795
      Clearing directory: /tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/cupy/.data

      -------- Configuring Module: cuda --------

      -------- Configuring Module: cusolver --------

      -------- Configuring Module: cudnn --------

      -------- Configuring Module: nccl --------
      /tmp/tmpppe1q6r6/a.cpp:1:10: fatal error: nccl.h: No such file or directory
          1 | #include <nccl.h>
            |          ^~~~~~~~
      compilation terminated.
      command '/usr/bin/gcc' failed with exit code 1

      -------- Configuring Module: nvtx --------

      -------- Configuring Module: cutensor --------
      /tmp/tmpld9haxlc/a.cpp:1:10: fatal error: cutensor.h: No such file or directory
          1 | #include <cutensor.h>
            |          ^~~~~~~~~~~~
      compilation terminated.
      command '/usr/bin/gcc' failed with exit code 1

      -------- Configuring Module: cub --------

      -------- Configuring Module: jitify --------
      **************************************************
      *** WARNING: Cannot determine Jitify version
      [Errno 2] No such file or directory: '/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/third_party/jitify'
      **************************************************

      -------- Configuring Module: random --------

      -------- Configuring Module: thrust --------

      -------- Configuring Module: cusparselt --------
      /tmp/tmppdblfmym/a.cpp:1:10: fatal error: cusparseLt.h: No such file or directory
          1 | #include <cusparseLt.h>
            |          ^~~~~~~~~~~~~~
      compilation terminated.
      command '/usr/bin/gcc' failed with exit code 1

      -------- Configuring Module: dlpack --------

      ************************************************************
      * CuPy Configuration Summary                               *
      ************************************************************

      Build Environment:
        Include directories: ['/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/cupy/_core/include/cupy/_cccl/libcudacxx', '/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/cupy/_core/include/cupy/_cccl/thrust', '/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/cupy/_core/include/cupy/_cccl/cub', '/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/cupy/_core/include', '/usr/include']
        Library directories: ['/usr/lib64', '/usr/lib']
        nvcc command       : ['/usr/bin/nvcc']
        hipcc command      : (not found)

      Environment Variables:
        CFLAGS          : (none)
        LDFLAGS         : (none)
        LIBRARY_PATH    : (none)
        CUDA_PATH       : (none)
        NVCC            : (none)
        HIPCC           : (none)
        ROCM_HOME       : (none)

      Modules:
        cuda      : Yes (version 12000)
        cusolver  : Yes
        cudnn     : Yes (version 8902)
        nccl      : No
          -> Include files not found: ['nccl.h']
          -> Check your CFLAGS environment variable.
        nvtx      : Yes
        cutensor  : No
          -> Include files not found: ['cutensor.h']
          -> Check your CFLAGS environment variable.
        cub       : Yes (version 200600)
        jitify    : Yes (version <unknown>)
        random    : Yes
        thrust    : Yes (version 200600)
        cusparselt: No
          -> Include files not found: ['cusparseLt.h']
          -> Check your CFLAGS environment variable.
        dlpack    : Yes

      WARNING: Some modules could not be configured.
      CuPy will be installed without these modules.
      Please refer to the Installation Guide for details:
      https://docs.cupy.dev/en/stable/install.html

      ************************************************************

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/setup.py", line 95, in <module>
          ext_modules = cupy_setup_build.get_ext_modules(True, ctx)
        File "/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/install/cupy_builder/cupy_setup_build.py", line 514, in get_ext_modules
          extensions = make_extensions(ctx, compiler, use_cython)
        File "/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/install/cupy_builder/cupy_setup_build.py", line 378, in make_extensions
          s['extra_objects'] = [
        File "/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/install/cupy_builder/cupy_setup_build.py", line 379, in <listcomp>
          _find_static_library(name) for name in module.static_libraries
        File "/tmp/pip-install-1k24ymkf/cupy_95301aea4ff14244bf6add7fbaf22073/install/cupy_builder/cupy_setup_build.py", line 289, in _find_static_library
          raise Exception(f'Could not find {filename}: {path} does not exist')
      Exception: Could not find libcudart_static.a: /usr/lib/libcudart_static.a does not exist
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for cupy
Failed to build cupy
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cupy)
```

</details>

**Comment by joshuacwnewton** [comment]
Ah, I was mistaken, sorry! `pip install cupy` doesn't work, and taking a closer look at the monai docs, the proper command is `pip install monai[all]`. When I do that, I see:

```
Downloading cupy_cuda12x-13.3.0-cp39-cp39-manylinux2014_x86_64.whl (91.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.4/91.4 MB 2.1 MB/s eta 0:00:00
```

Implying that the package is actually called `cupy_cuda12x`. 

Could you try the `pip install monai[all]` command and see what happens?

**Comment by valosekj** [comment]
> Could you try the `pip install monai[all]` command and see what happens?

Yes, `pip install monai[all]` works! Thank you, Joshua!

**Comment by joshuacwnewton** [comment]
Thank you for the quick test! 

I dug deeper into this issue, and opened the following issue:

- https://github.com/Project-MONAI/MONAI/issues/8106

It seems like the `monai[all]` is not actually required, but maybe only `monai[cucim]` is required? And, potentially this is only an issue for Python 3.9 + Linux specifically.
