### ISSUE TITLE
`sct_analyze_lesion` QC fails if the lesion mask is empty

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4642]
### Description

`sct_analyze_lesion` fails when generating QC if the lesion mask is empty.

For some context, I run `sct_analyze_lesion` in a pipeline on lesion masks segmented by SCIseg (code [here](https://github.com/ivadomed/model_seg_sci/blob/79fd81370ff420e2a8227c851f3ee5ad9dfe44d8/midsagittal_measures/01_compute_midsagittal_lesion_length_and_width.sh#L141-L153)). If SCIseg segments no lesion, the subsequent `sct_analyze_lesion` crashes; see the error log below.

<details><summary>error log</summary>

```console
+ sct_analyze_lesion -m sub-zh73_ses-01_acq-sag_T2w_lesion_seg.nii.gz -s sub-zh73_ses-01_acq-sag_T2w_sc_seg_SCIsegV2.nii.gz -qc /home/GRAMES.POLYMTL.CA/p118175/results/sci-zurich_midsagittal_measures_2024-10-02_ma>

--
Spinal Cord Toolbox (git-master-197ef3494a1c73d8b8acb14fcd809f31e16b5265)

sct_analyze_lesion -m sub-zh73_ses-01_acq-sag_T2w_lesion_seg.nii.gz -s sub-zh73_ses-01_acq-sag_T2w_sc_seg_SCIsegV2.nii.gz -qc /home/GRAMES.POLYMTL.CA/p118175/results/sci-zurich_midsagittal_measures_2024-10-02_mast>
--

WARNING: Empty masked image
Creating temporary folder (/tmp/sct_2024-10-02_16-05-59_analyze-lesion_5_uznkys)
cp sub-zh73_ses-01_acq-sag_T2w_lesion_seg.nii.gz /tmp/sct_2024-10-02_16-05-59_analyze-lesion_5_uznkys
cp sub-zh73_ses-01_acq-sag_T2w_sc_seg_SCIsegV2.nii.gz /tmp/sct_2024-10-02_16-05-59_analyze-lesion_5_uznkys

Orient input image(s) to RPI orientation...
^[[33mFile sub-zh73_ses-01_acq-sag_T2w_lesion_seg.nii.gz already exists. Will overwrite it.^[[0m
^[[33mFile sub-zh73_ses-01_acq-sag_T2w_sc_seg_SCIsegV2.nii.gz already exists. Will overwrite it.^[[0m

Label connected regions of the masked image...
^[[33mImage header specifies datatype 'uint8', but array is of type 'int64'. Header metadata will be overwritten to use 'int64'.^[[0m
Lesion count = 0
Midsagittal slice of the spinal cord: 10
WARNING: No lesion found in sub-zh73_ses-01_acq-sag_T2w_lesion_seg_label.nii.gz.

Orient output image to initial orientation...
^[[33mFile sub-zh73_ses-01_acq-sag_T2w_lesion_seg_label.nii.gz already exists. Will overwrite it.^[[0m


Averaged measures across all lesions...
  volume [mm3] = nan +/- nan
  length [mm] = nan +/- nan
  max_equivalent_diameter [mm] = nan +/- nan
  max_axial_damage_ratio [] = nan +/- nan
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_analyze_lesion.py", line 1085, in <module>
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_analyze_lesion.py", line 1043, in main
    lesion_obj.analyze()
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_analyze_lesion.py", line 236, in analyze
    self.show_total_results()
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_analyze_lesion.py", line 326, in show_total_results
    min_dorsal_bridge = np.nanmin(midsagittal_dorsal_bridges)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/numpy/lib/nanfunctions.py", line 350, in nanmin
    res = np.amin(a, axis=axis, out=out, **kwargs)
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2970, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/home/GRAMES.POLYMTL.CA/p118175/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
```

</details>

I think a simple fix could be to skip the QC entirely if the lesion mask is empty (because if there is no lesion, we have nothing to show in the QC report). Still, it is valuable to output the XLSX file with metrics (which are equal to zero) for potential further stat analysis.

**Comment by valosekj** [comment]
> Wouldn't it be better to output a very clear "no lesion" row in the QC report? I imagine that this would be relevant information if someone was running a pipeline on many subjects.

This is a good idea!
