### ISSUE TITLE
ModuleNotFoundError: No module named 'IPython' when running within jupyter notebook

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4674]
When running SCT via a jupyter notebook, the QC report sometimes fail, throwing an "IPython missing" message:

<details><summary>Terminal output</summary>

```console
--
Spinal Cord Toolbox (git-master-a458fa37fd22179dd2a6c13d33b7d191552abee7)

sct_qc -i sub-CRMBM1_UNIT1.nii.gz -s sub-CRMBM1_UNIT1_seg_labeled.nii.gz -p sct_label_vertebrae -qc /Users/julien/code/coil-qc-code/data-human/qc -qc-subject sub-CRMBM1
--


*** Generating Quality Control (QC) html report ***
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_qc.py", line 125, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_qc.py", line 108, in main
    generate_qc(fname_in1=arguments.i,
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 632, in generate_qc
    qc_image._make_QC_image_for_3d_volumes(img, mask, plane, imgs_to_generate)
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 228, in _make_QC_image_for_3d_volumes
    fig = mpl_plt.figure()
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/pyplot.py", line 1027, in figure
    manager = new_figure_manager(
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/pyplot.py", line 549, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/pyplot.py", line 526, in _warn_if_gui_out_of_main_thread
    canvas_class = cast(type[FigureCanvasBase], _get_backend_mod().FigureCanvas)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/pyplot.py", line 358, in _get_backend_mod
    switch_backend(rcParams._get("backend"))
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/pyplot.py", line 415, in switch_backend
    module = backend_registry.load_backend_module(newbackend)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/backends/registry.py", line 323, in load_backend_module
    return importlib.import_module(module_name)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib_inline/__init__.py", line 1, in <module>
    from . import backend_inline, config  # noqa
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib_inline/backend_inline.py", line 13, in <module>
    from IPython.core.interactiveshell import InteractiveShell
ModuleNotFoundError: No module named 'IPython'
```

</details>

What is strange however is that within the _same_ notebook and kernel run, QC report can succeed, eg here:

<details><summary>Terminal output</summary>

```console
sct_deepseg -i sub-CRMBM1_UNIT1.nii.gz -task seg_sc_contrast_agnostic -thr 0 -qc /Users/julien/code/coil-qc-code/data-human/qc
--

Model 'model_seg_sc_contrast_agnostic_softseg_monai' is up to date (Source: https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/download/v2.5/model_contrast-agnostic_20240930-1002.zip)
Creating temporary folder (/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-11-02_13-41-55_sct_deepseg_qj8h1ljh)
Copied sub-CRMBM1_UNIT1.nii.gz to /var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-11-02_13-41-55_sct_deepseg_qj8h1ljh/sub-CRMBM1_UNIT1.nii.gz
Starting inference...
Inference done.
Total inference time: 0 minute(s) 12 seconds
Saving results to: /var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-11-02_13-41-55_sct_deepseg_qj8h1ljh/sub-CRMBM1_UNIT1_seg.nii.gz

*** Generating Quality Control (QC) html report ***
Resample images to 0.600000x0.600000 vox
Converting image from type 'int16' to type 'float64' for spline interpolation
Find the center of each slice
/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/scipy/ndimage/_measurements.py:1542: RuntimeWarning: invalid value encountered in scalar divide
  results = [sum(input * grids[dir].astype(float), labels, index) / normalizer
Successfully generated the QC results in /Users/julien/code/coil-qc-code/data-human/qc/_json/qc_2024_11_02_134226.534224.json
```

</details>

One difference I see, is that the error happens when calling `sct_qc`, but not when the QC report is called from within a function (eg `sct_deepseg` as in the example above).

Would there be a reason for the crash to occur with `sct_qc` specifically?

**Comment by jcohenadad** [comment]
Another relevant information: the issue is not specific to the `sct_label_vertebrae` QC module, because it also fails for `sct_deepseg_sc`:

<details><summary>Terminal output</summary>

```console

--
Spinal Cord Toolbox (git-master-a458fa37fd22179dd2a6c13d33b7d191552abee7)

sct_qc -i sub-MPI2_UNIT1.nii.gz -s sub-MPI2_UNIT1_seg.nii.gz -p sct_deepseg_sc -qc /Users/julien/code/coil-qc-code/data-human/qc -qc-subject sub-MPI2
--

Resampling image "sub-MPI2_UNIT1.nii.gz" to 0.6x0.6 mm
Converting image from type 'int16' to type 'float64' for spline interpolation
Resampling image "sub-MPI2_UNIT1_seg.nii.gz" to 0.6x0.6 mm
Converting image from type 'uint8' to type 'float64' for linear interpolation
Image header specifies datatype 'float64', but array is of type 'int64'. Header metadata will be overwritten to use 'int64'.
Compute center of mass at each slice
/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/scipy/ndimage/_measurements.py:1542: RuntimeWarning: invalid value encountered in scalar divide
  results = [sum(input * grids[dir].astype(float), labels, index) / normalizer

*** Generating Quality Control (QC) html report ***
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_qc.py", line 125, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_qc.py", line 108, in main
    generate_qc(fname_in1=arguments.i,
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 632, in generate_qc
    qc_image._make_QC_image_for_3d_volumes(img, mask, plane, imgs_to_generate)
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 228, in _make_QC_image_for_3d_volumes
    fig = mpl_plt.figure()
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/pyplot.py", line 1027, in figure
    manager = new_figure_manager(
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/pyplot.py", line 549, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/pyplot.py", line 526, in _warn_if_gui_out_of_main_thread
    canvas_class = cast(type[FigureCanvasBase], _get_backend_mod().FigureCanvas)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/pyplot.py", line 358, in _get_backend_mod
    switch_backend(rcParams._get("backend"))
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/pyplot.py", line 415, in switch_backend
    module = backend_registry.load_backend_module(newbackend)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/backends/registry.py", line 323, in load_backend_module
    return importlib.import_module(module_name)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib_inline/__init__.py", line 1, in <module>
    from . import backend_inline, config  # noqa
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib_inline/backend_inline.py", line 13, in <module>
    from IPython.core.interactiveshell import InteractiveShell
ModuleNotFoundError: No module named 'IPython'
```

</details>

Which adds evidence about the problem being related to the direct call to `sct_qc`

**Comment by jcohenadad** [comment]
Maybe a clue: `sct_qc` relies on API's `qc`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a458fa37fd22179dd2a6c13d33b7d191552abee7/spinalcordtoolbox/scripts/sct_qc.py#L108-L120

While the QC calls from within functions (eg `sct_deepseg`) relies on `qc2`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a458fa37fd22179dd2a6c13d33b7d191552abee7/spinalcordtoolbox/scripts/sct_deepseg.py#L380-L389

**Comment by jcohenadad** [comment]
Going through the error exception, the culprit from within SCT code seems to be coming from:
~~~
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 228, in _make_QC_image_for_3d_volumes
    fig = mpl_plt.figure()
~~~

However, this variable is equally defined in qc and qc2:

  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 228, in _make_QC_image_for_3d_volumes
    fig = mpl_plt.figure()

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a458fa37fd22179dd2a6c13d33b7d191552abee7/spinalcordtoolbox/reports/qc2.py#L34

**Comment by jcohenadad** [comment]
Hum, but it seems like `qc2.deepseg` never calls `mpl_plt`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a458fa37fd22179dd2a6c13d33b7d191552abee7/spinalcordtoolbox/reports/qc2.py#L282-L373

So maybe that's a clue to the actual cause for the bug: the call to `mpl_plt`

**Comment by mguaypaq** [comment]
> So maybe that's a clue to the actual cause for the bug: the call to `mpl_plt`

That makes a lot of sense: I'm sure Jupyter does some magic so that the plots from `matplotlib.pyplot` (aka `mpl_plt`) can show up in the notebook itself. Ah yes, this involves `backend_inline`:
https://github.com/ipython/matplotlib-inline

How are you running SCT commands in the notebook? With a direct Python `import`, or something like `os.system()`, or something else?

**Comment by jcohenadad** [comment]
> How are you running SCT commands in the notebook? With a direct Python import, or something like os.system(), or something else?

something else, ie: `!sct_blabla`

**Comment by mguaypaq** [comment]
What does this say (assuming shell pipes are supported)?
```
!env | grep PATH
```
I'm curious about both `PATH` and `PYTHON_PATH` when running commands with exclamation marks.

**Comment by joshuacwnewton** [comment]
> > So maybe that's a clue to the actual cause for the bug: the call to `mpl_plt`
> 
> That makes a lot of sense: I'm sure Jupyter does some magic so that the plots from `matplotlib.pyplot` (aka `mpl_plt`) can show up in the notebook itself. Ah yes, this involves `backend_inline`: https://github.com/ipython/matplotlib-inline

Possibly related:

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4523
- https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4525

Though, given the above error message, I imagine this is distinct.

**Comment by jcohenadad** [comment]
> What does this say (assuming shell pipes are supported)?
> ~~~
> !env | grep PATH
> ~~~

~~~
PATH=/Users/julien/code/coil-qc-code/myenv/bin:/opt/homebrew/opt/binutils/bin:/Users/julien/fsl/share/fsl/bin:/Users/julien/fsl/share/fsl/bin:/Users/julien/code/spinalcordtoolbox/bin:/Users/julien/shimming-toolbox/bin:/Users/julien/miniconda3/bin:/Users/julien/miniconda3/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
VSCODE_CODE_CACHE_PATH=/Users/julien/Library/Application Support/Code/CachedData/65edc4939843c90c34d61f4ce11704f09d3e5cb6
PATH_DATA_ZURICH_MOUSE=/Users/julien/data.neuro/zurich-mouse
~~~

**Comment by SomeoneInParticular** [comment]
So, I believe this bug turns out to be due to a very complicated chain of events. In short:

* Our package does not require `IPython` as one of its dependencies, and is what is being used during our QC generation.
* `Jupyter` does use `IPython`, as does the `inline` back-end it uses for `matplotlib`, which explicitly requires `IPython`.
* Jupyter recently made it so `inline` is the default back-end; to do this, it updates the `matplotlib` parameters to reference the `inline` back-end. Therefore, it is what sets the back-end, but is _not_ available when we start trying to generate QCs.
* The `figure` function of `matplotlib.pyplot` checks against the back-end to see whether the figures should be drawn interactively (specifically [here](https://github.com/matplotlib/matplotlib/blob/c38f70a57277f661c7426c7d464c07c5ad0c2318/lib/matplotlib/pyplot.py#L1061)); this results in the `inline` back-end attempting to initialize and crashing our program (as SCT does _not_ have access to `IPython`)
* In contrast, requesting a `Figure` instance directly does _not_ check against the back-end, thus side-stepping the problem entirely.

I want to dig into this more before saying the issue is "solved", but there is now  #4838 which should fix the issue you were experiencing @jcohenadad.

**Comment by SomeoneInParticular** [comment]
I think this is now resolved, far as I can tell, with PR #4838. This is a patchy fix, though, and its likely something like this will crop up again until we unify how QC is managed entirely
