### ISSUE TITLE
`totalspineseg` fails for uncompressed images (`.nii`)

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4756]
While helping out @sriosq, we encountered an error for the 4D image file `cervical_exp_concat_mag.nii`:

```
Running step 1 model:
perform_everything_on_device=True is only supported for cuda devices! Setting this to False
Traceback (most recent call last):
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 398, in <module>
    main(sys.argv[1:])
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 298, in main
    im_lst, target_lst = inference.segment_non_ivadomed(path_model, model_type, input_filenames, thr,
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/deepseg/inference.py", line 134, in segment_non_ivadomed
    fnames_out, targets = inference(path_img=fname_in, tmpdir=tmpdir, predictor=net, device=device)
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/deepseg/inference.py", line 361, in segment_totalspineseg
    tss_inference(
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/totalspineseg/inference.py", line 388, in inference
    predict_nnunet(
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/totalspineseg/utils/predict_nnunet.py", line 241, in predict_nnunet
    predictor.predict_from_files(str(images_dir), str(output_dir), save_probabilities=save_probabilities,
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 245, in predict_from_files
    self._manage_input_and_output_lists(list_of_lists_or_source_folder,
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 166, in _manage_input_and_output_lists
    list_of_lists_or_source_folder = create_lists_from_splitted_dataset_folder(list_of_lists_or_source_folder,
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/nnunetv2/utilities/utils.py", line 42, in create_lists_from_splitted_dataset_folder
    identifiers = get_identifiers_from_splitted_dataset_folder(folder, file_ending)
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/nnunetv2/utilities/utils.py", line 27, in get_identifiers_from_splitted_dataset_folder
    files = subfiles(folder, suffix=file_ending, join=False)
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 69, in subfiles
    with os.scandir(folder) as entries:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/sct_2024-12-17_12-19-41_sct_deepseg_7pt5evfm/nnUNet_prediction/input'
```

Our tests worked fine, so this error was very confusing! But then I noticed this bit of code in `totalspineseg`:

```bash
    if input_path.name.endswith('.nii.gz'):
        # If the input is a single file, copy it to the input_raw folder
        (output_path / 'input_raw').mkdir(parents=True, exist_ok=True)
        shutil.copy(input_path, output_path / 'input_raw' / input_path.name.replace('.nii.gz', '_0000.nii.gz'))
```

This conditional leaves out images ending in `.nii`. (cc: @plbenveniste)

**Comment by plbenveniste** [comment]
Tagging @NathanMolinier who worked on this bit of code. 
But I guess this is a rather easy fix.

**Comment by NathanMolinier** [comment]
Yes this is definitely something we need to fix !

**Comment by NathanMolinier** [comment]
I realize that I fixed this but did not update the package

**Comment by NathanMolinier** [comment]
It should work with the new version of the package [20250205](https://pypi.org/project/totalspineseg/) @joshuacwnewton

**Comment by joshuacwnewton** [comment]
Thanks for the update! The changes should propagate automatically (since [`totalspineseg`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/49a88916993f5705e2708b8f94b75ddfa24c97e5/requirements.txt#L67) is unpinned). But, it would be nice if we could open a PR that includes tests for both this issue and https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4757, so I'm tempted to leave this issue open for now.

**Comment by joshuacwnewton** [comment]
Finally getting around to checking this now! I can confirm it works. :hearts:
