### ISSUE TITLE
`sct_deepseg` does not currently support 4D images

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4757]
While helping out @sriosq, after I fixed #4756 by gzipping the input file, I encountered another error during the resampling step:

```
Resampling step1_output to the input images space:
  0%|                                                                                                                                                                   | 0/1 [00:05<?, ?it/s]
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/totalspineseg/utils/transform_seg2image.py", line 191, in _transform_seg2image
    output_seg = transform_seg2image(
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/totalspineseg/utils/transform_seg2image.py", line 249, in transform_seg2image
    dilation_size = int(np.ceil(np.max(np.array(image.header.get_zooms()) / np.array(seg.header.get_zooms()))))
ValueError: operands could not be broadcast together with shapes (4,) (3,) 
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 398, in <module>
    main(sys.argv[1:])
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 298, in main
    im_lst, target_lst = inference.segment_non_ivadomed(path_model, model_type, input_filenames, thr,
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/deepseg/inference.py", line 134, in segment_non_ivadomed
    fnames_out, targets = inference(path_img=fname_in, tmpdir=tmpdir, predictor=net, device=device)
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/deepseg/inference.py", line 361, in segment_totalspineseg
    tss_inference(
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/totalspineseg/inference.py", line 801, in inference
    transform_seg2image_mp(
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/totalspineseg/utils/transform_seg2image.py", line 150, in transform_seg2image_mp
    process_map(
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 105, in process_map
    return _executor_map(ProcessPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/concurrent/futures/process.py", line 562, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
ValueError: operands could not be broadcast together with shapes (4,) (3,) 
```

I guess `totalspineseg` doesn't support 4D images? My guess is that `totalspineseg` should probably handle this inside the package, that way it can take advantage of its parallelization by splitting the 4D image into a batch of 3D images, then recombining. But, tagging @plbenveniste for input.

**Comment by valosekj** [comment]
> I guess totalspineseg doesn't support 4D images?

I guess so. @sriosq also had a similar issue with the contrast-agnostic model. Extracting only the first echo (a single 3D volume) from his 4D multi-echo image solved the problem for contrast-agnostic.

**Comment by plbenveniste** [comment]
Agree with your answer @valosekj. Tagging @NathanMolinier who worked on `totalspineseg`

**Comment by NathanMolinier** [comment]
4D images are converted into 3D images at the beginning of the pipeline by averaging according to the time dimension. However, because we try to resample back the final segmentation to the original shape at the end of the pipeline, we get an error due to the missing time dimension. This is an error we completely overlooked !

**Comment by NathanMolinier** [comment]
It should work with the new version of the package [20250205](https://pypi.org/project/totalspineseg/) @joshuacwnewton

**Comment by joshuacwnewton** [comment]
Thanks for the update! The changes should propagate automatically (since [`totalspineseg`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/49a88916993f5705e2708b8f94b75ddfa24c97e5/requirements.txt#L67) is unpinned). But, it would be nice if we could open a PR that includes tests for both this issue and https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4756, so I'm tempted to leave this issue open for now.

**Comment by joshuacwnewton** [comment]
Finally getting around to checking this now! I can confirm it works. :hearts:
